### ISSUE TITLE
Consider making a Homebrew Formula for Mac users

### ISSUE THREAD

**Issue by lqi** [oclint/oclint#12]

**Comment by skensell** [comment]
It's 2015 now, and there are still people like me out there who'd highly appreciate it. I guess I can get by with `brew cask` for now.

**Comment by ryuichis** [comment]
I am closing it now, please consider using brew cask.

**Comment by ryuichis** [comment]
I just made a tap for oclint, check it out https://github.com/oclint/homebrew-formulae

**Comment by hastyjw** [comment]
Remove me

John H.
