### ISSUE TITLE
Rule prohibiting use of system libraries.

### ISSUE THREAD

**Issue by aleffert** [oclint/oclint#142]
I want to make a rule that simulates the effect of `__attribute__((deprecated))` in cases where I can't actually use that.

In particular, I'd like to be able to just use `deprecated` itself, but clang doesn't pick it up when I try to add it to existing system libraries via categories like I have been doing with my previous rules.

e.g. if I do

```
@interface SomeSystemLibrary (StaticCategory)

- (void)someExistingMethod __attribute__(deprecated);

@end
```

I don't get an error using `someExistingMethod`.

This shouldn't be particularly different from the other rules I've been making, but I want to add a way for users of this rule to add a comment about what someone should be using instead that can appear as part of the error message.

This seems like a pretty general feature so I wanted to discuss it before implementing it.

There are several ways I see it working.
1. `__attribute__((annotate("oclint:enforce[prohibited,some comment]")))`
   We could update the attribute helper to look for a comment and pass it on to the code that sees if the attribute is present.
   2.`__attribute__((annotate("oclint:enforce[prohibited][some comment]“)))`
   Minor syntactic variant on the first option. Has the advantage that whitespace usage is clearer.
2. `__attribute__((annotate("oclint:enforce[prohibited, use_instead=someOtherMethod“)))`
   This last case is really proposing an arbitrary key value map that a rule could examine. Here, only this individual rule would know how to handle the “use_instead” key and other rules would be unchanged. It seems like having a mechanism for code to pass more information to the rule could be quite useful, but it’s also more complicated.

In all cases, the comment would be optional.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
