### ISSUE TITLE
oclint-json-compilation-database omitting files under directories containing spaces

### ISSUE THREAD

**Issue by chazu** [oclint/oclint#175]
The sources for my current project live in a directory which contains a space, unfortunately. As a result, when compile-commands.json is parsed by oclint-json-compilation-database, the current implementation of source_exist_at returns False for all of my relevant source files. 

Cursory research indicates that os.path.isfile() is the culprit:

```
Apatosaurus:science chazu$ python
Python 2.7.6 (default, Jan  4 2014, 23:54:12)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os 
>>> os.path.isfile('/Users/chazu/science/cat_picture.jpg')
True
>>> os.path.isfile('/Users/chazu/science/cat\ pictures/cat_picture.jpg')
False
>>> exit()
Apatosaurus:science chazu$ find . | grep cat_picture.jpg
./cat pictures/cat_picture.jpg
./cat_picture.jpg
```

I'm not sure exactly what the solution is, but I wanted to report the issue for now. I'm just going to hack my way around it for now, but if I make a satisfactory work-around I'll put in a PR. 

Meantime, please let me know if you would like me to provide additional information or an example repository.

Thanks,
Chaz

**Comment by gamugamu** [comment]
I have the same problem, and unfortunalty I can't change the directory

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
