### ISSUE TITLE
Improved script for integrating OCLint in Xcode

### ISSUE THREAD

**Issue by 1951FDG** [oclint/oclint#180]
While I was figuring out how to integrate OCLint in Xcode, I stumbled upon http://gavrix.wordpress.com/2013/02/28/integrating-oclint-in-xcode/, later your fork https://gist.github.com/lqi/5358513, and eventually I created a fork as well, https://gist.github.com/1951FDG/8146422. Improvement is the {oclint-json-compilation-database -- -p "${TARGET_TEMP_DIR}"} part and it handles file names with spaces correctly (hopefully one day OCLint will support file names with spaces, which it doesn't at the moment).

The articles involved which could be updated are:
http://oclint.org/news/2013/04/06/integration-oclint-06-in-xcode/
http://docs.oclint.org/en/dev/guide/xcode.html

My fork, https://gist.github.com/1951FDG/8146422, could be useful for users trying to make use of the original script by @gavrix.

**Comment by 1951FDG** [comment]
I have updated my fork again, https://gist.github.com/1951FDG/8146422. Improvements are support for multiple configurations, multiple projects in same working directory and oclint-xcodebuild is executed each time aggregate target is build.

**Comment by ryuichis** [comment]
All forks are now linked on http://docs.oclint.org/en/stable/guide/xcode.html
