### ISSUE TITLE
Improve build system to be "pure" CMake.

### ISSUE THREAD

**Issue by swizzlr** [oclint/oclint#181]
Current build system consists of two major pieces, CMake and bash scripts. Bash scripts call cmake under the hook, and cmake performs the actual build work. In addition, cmake maintains the project structure, running unit tests, bundling, dogFooding, and others to compile OCLint from source code into a working binary distribution.

We would like to use more help from CMake, and keep bash scripts for miscellaneous things.

This eases developers and other projects (e.g. [Big Tool Brewery](https://github.com/big-tool-brewery), homebrew) configuring OCLint and integrating it seamlessly.

This may end up needing to be a milestone, but a good first step is:
- [ ] add auto finding of LLVM, checking of version, and a way to configure this when cmake is called.
- [ ] add auto finding of googletest/googlemock
- [ ] bundle each module into artifacts with headers and generated binaries, and publish them. So that, other modules depend on artifacts rather than source code
- [ ] support build in both debug and release mode
- [ ] execute unit testing binaries
- [ ] package final binaries (including oclint-json-compilation-database, oclint-xcodebuild, etc), dynamic libraries, and clang dependencies
- [ ] support standard installation `prefix`
- [ ] able to run dog fooding with the generated oclint binary
- [ ] detect various types of versions, like versions of dependencies (LLVM, googletest), oclint release version, git revision, etc

I'll update this more when I have time on my hands.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
