### ISSUE TITLE
Use all cores for oclint-json-compilation-database

### ISSUE THREAD

**Issue by drewcrawford** [oclint/oclint#187]
I am using `oclint-json-compilation-database` to analyze a project.  This takes around 20 minutes.

Empirically, what seems to happen is that a single oclint process is spawned which pegs 1 core for 20 minutes.  Based on the debug output, this process seems to serially process every source code file in the project.

It would be quite a lot smarter to launch 1-2 oclint processes per core.  Most machines nowadays are 4/8 cores, and that is a significant reduction in analysis time.

**Comment by amendgit** [comment]
I have the same issue, is there any solution or workaround for this now. Thanks.
