### ISSUE TITLE
OCLint fatal error when I include some framework header file

### ISSUE THREAD

**Issue by caojianhua** [oclint/oclint#197]
I want to integrate OCLint to check my code when I do a git commit, and just only check this files about the commit.

If the source file contain some system framework header like this:<UIKit/UIKit.h>,  I will got this error:fatal error: 'UIKit/UIKit.h' file not found

How can i deal with it? 
Thanks!

**Comment by litianying137** [comment]
I am experiencing the same problem. how to deal with it?
@caojianhua @ozgur  thanks~!
