### ISSUE TITLE
oclint-xcodebuild incremental update

### ISSUE THREAD

**Issue by patspam** [oclint/oclint#199]
It would be nice if oclint-xcodebuild supported updating an existing compile_commands.json rather than building one from scratch.

That is, when processing file entries from xcodebuild.log:
* Add new entries
* Overwrite existing entries
* Leave others untouched

That would basically avoid the need to do a clean build and make the whole process a lot faster.

(Filing issue in top-level oclint project because I couldn't see an Issues tab in the oclint-xcodebuild sub-project)

**Comment by ryuichis** [comment]
I am closing this one, please consider using xcpretty instead of oclint-xcodebuild.
