### ISSUE TITLE
oclint: error: no rule loaded when checking trivial file.

### ISSUE THREAD

**Issue by elimirks** [oclint/oclint#200]
Hey guys, just installed oclint and have been trying to test it out on this trivial file, but it keeps failing:

main.m:
```objective-c
int main(int argc, char* argv[]) {
        return 0;
}
```

```
% oclint main.m 


oclint: error: no rule loaded
```

I tried both version 0.7 as well as the current dev release, still the same error.

I am running OS X Mavericks.

**Comment by NAThompson** [comment]
I got this error because I symlinked `oclint` into `/usr/bin`. If I give the absolute path to `oclint`, this error goes away.

**Comment by ryuichis** [comment]
Closing due to installation/folder structure issue. Consider using brew cask.
