### ISSUE TITLE
OClint-0.9 issue with disabling rule "SwitchSatementsDon'tNeedDefaultWhenFullyCovered"

### ISSUE THREAD

**Issue by My3VM** [oclint/oclint#206]
I have installed latest version of OClint(oclint-0.9.dev.90b12ca-x86_64-darwin) and analysing iOS project codebase.
I have setup .oclint file to configure the rules and thresholds, which is working fine except for the rule "SwitchSatementsDon'tNeedDefaultWhenFullyCovered". Here is how I have configured it, but OClint is not able to disable switchstatementdontneeddefaultwhenfullycovered rule, unlike other rules.
disable-rules:
- SwitchSatementsDon'tNeedDefaultWhenFullyCovered
  - LongLine
  - ReplaceWithBoxedExpression
  - ReplaceWithContainerLiteral

Please suggest solution.
P.S : Even tried with the name "SwitchSatementsDontNeedDefaultWhenFullyCovered", but in vain.

**Comment by ryuichis** [comment]
Using `CoveredSwitchStatementsDontNeedDefaultRule` should make this pass.
