### ISSUE TITLE
Wrong value in numberOfFilesWithViolations

### ISSUE THREAD

**Issue by onato** [oclint/oclint#207]
I am getting a value of 2 for numberOfFilesWithViolations even though there is only one violation. 

    {"version":"0.9dev","url":"http://oclint.org","timestamp":1402758376,"summary":\
    {"numberOfFiles":20,"numberOfFilesWithViolations":2,\
    "numberOfViolationsWithPriority":[{"priority":1,"number":0},\
    {"priority":2,"number":0},{"priority":3,"number":1}]}…

**Comment by ryuichis** [comment]
Addressed in P.R. #273.
