### ISSUE TITLE
passing the -enable-clang-static-analyzer flag can not generate report

### ISSUE THREAD

**Issue by wanyukang** [oclint/oclint#219]
I have generating compile_commands.json, and run it without clang flag like 
`oclint-json-compilation-database -v oclint_args "-o oclint-report.html -report-type html -stats"`
it just works fine, but when I passing the -enable-clang-static-analyzer flag like
 `oclint-json-compilation-database -v oclint_args "-o oclint-report.html -report-type html -stats -enable-clang-static-analyzer"`
 I can not get the report, OCLint generate notthing .

I have been try the oclint-0.8.dev.c1da4cc, oclint-0.9.dev.5f3418c, oclint-0.9.dev.5dba345
my env: OSX 10.9.2, XCode5.1.1, 
OSX 10.9.4 XCode6.1,

If I made ​​a mistake, please tell me what went wrong step.

**Comment by jtoce** [comment]
+1 to @cjtcwyk - seeing the same behavior. 

Here is the command I'm running:
oclint-json-compilation-database -e Pods -v -- -report-type html -o report.html -enable-clang-static-analyzer

Report generated fine if I leave off the -enable-clang-static-analyzer flag.
