### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by cuadue** [oclint/oclint#234]
Compiled `oclint-0.9.dev.02251e4` using the `oclint-scripts/make` program. When invoking `oclint myfile.cpp` in a directory containing a valid `compile_commands.json` (which in turn contains an entry for `myfile.cpp`), the program segfaults.

The program seems to have it's debugging symbols stripped. How can it be compiled for debug mode in order to run it through GDB?

**Comment by ryuichisaito6** [comment]
To compile in debug mode, go to `oclint-scripts` folder, and run the following two commands:

`./ci -reset`
`./ci -setup`
