### ISSUE TITLE
how to setup custom rules step by step?

### ISSUE THREAD

**Issue by GeekMin** [oclint/oclint#236]
hey,
   Have been learning OCLint for nearly one week and  I wanna define some custom rules, but "CMake" is new for me..."AST" is new for me...Based on the existing pattern, like "visitors Pattern", "ASTMatcher", I think I can do sth. But my problem is coming : Now I do not know how to setup custom rule incrementally... [How can I integrated one new rule into the existing rulesets, i.e. [.cpp -> .dylib?]]
 I need modify which file? [Now I am learning the whole compiled procedure of OCLint] I wanna sb to give some solution or hints.. If you think I do not ask a good question, please tell me..hmm...
  Maybe I think one document needed here~?

referenced before: 
http://docs.oclint.org/en/dev/devel/compiletest.html

**Comment by nicolasiJasica** [comment]
~~(╯﹏╰)

I have a same problem！

so，who can help us?

**Comment by GeekMin** [comment]
hmmm,, afterwards I solve it by myself... 

But now, I forget it... (after learning CMake and basic knowledge about Clang AST (& ASTMatcher etc.)
So keep moving~

**Comment by nicolasiJasica** [comment]
ok  thanks

**Comment by BigNewbiePlus** [comment]
me too!!! can't find any tutorials about this!!!

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
