### ISSUE TITLE
oclint-json-compilation-database issues with Xcode7 beta 'could not build module' issues 

### ISSUE THREAD

**Issue by maithrivm** [oclint/oclint#240]
Hello there,
I have been using Oclint V 0.9 (oclint-0.9.dev.648e9af), which is working fine so far till Xcode versions 6.3.
However, today I upgraded the same project to Xcode, but it is failing terribly with many issues as listed below:

~/Desktop/Template test/dzx/dzx/AppDelegate.h:9:9: could not build module 'UIKit'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/CoreData.framework/Headers/CoreData.h:8:9: could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: expected a type
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVOpenGLESTexture.h:23:10: could not build module 'OpenGLES'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLBlitCommandEncoder.h:8:9: could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMediaTiming.h:8:9: could not build module 'Foundation'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:28: unknown type name 'NSArray'

Any help /hint towards addressing this is greatly appreciated.

**Comment by ryuichisaito6** [comment]
The latest 0.9dev build is built by an older version of Xcode... you may need to compile oclint locally with your local toolset...
