### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by sahara108** [oclint/oclint#243]
I got the error "Compiling /Users/TuanNguyen/Working/Mine/.../Source/.../.../ProjectCoreController.mSegmentation fault: 11` when trying to use oclint. Here is my compiler flags
{
  "directory": "/Users/TuanNguyen/Working/Source/Project", 
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fobjc-arc -fmodules -fmodules-cache-path=/Users/TuanNguyen/Xcode_Build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/TuanNguyen/Xcode_Build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang Project -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DPJ_AUTOCONF=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=8.0 -I/Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/Project.hmap -I/Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../vendor/include -I../vendor/include/libotr -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/include/libxml2 -I/Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Products/../IntermediateBuildFilesPath/UninstalledProducts/include -I/Users/TuanNguyen/Working/Mine/.../Source/.../../vendor/opus-1.1/include/opus -I/Users/TuanNguyen/Working/Mine/.../Source/.../../vendor/pjlib/include -I../vendor/ZRTPCPP/libzrtpcpp -I../vendor/ZRTPCPP/libzrtpcpp/common -I../vendor/ZRTPCPP/libzrtpcpp/crypto -I../vendor/ZRTPCPP/libzrtpcpp/cryptocommon -I/Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/DerivedSources/x86_64 -I/Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/DerivedSources -F/Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Products/Debug-iphonesimulator -F/Users/TuanNguyen/Working/Mine/.../Source/.../../vendor -F/Users/TuanNguyen/Working/Mine/.../Source/Project -DSQLITE_HAS_CODEC -MMD -MT dependencies -MF /Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/x86_64/ProjectCoreController.d --serialize-diagnostics /Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/x86_64/ProjectCoreController.dia -c /Users/TuanNguyen/Working/Mine/.../Source/.../.../ProjectCoreController.m -o /Users/TuanNguyen/Xcode_Build/Project-dzfhofyobxpzhfhirkumlcnvcgqo/Build/Intermediates/Project.build/Debug-iphonesimulator/Project.build/Objects-normal/x86_64/ProjectCoreController.o", 
  "file": "/Users/TuanNguyen/Working/Mine/.../Source/.../.../ProjectCoreController.m"
}

**Comment by cyupa** [comment]
Having the same issue.

**Comment by cyupa** [comment]
Try using cling 0.9. It fixed this issue for me.

**Comment by tomek27** [comment]
Have the same issue.
Where did You get 0.9 version? On main page from CI got error page instead artefact.
Also i tried to compile it from last master on MacOS but it fails. I only managed to do it for Linux but that does not solve my problem.

**Comment by ryuichisaito6** [comment]
Feels like the issue can be fixed with the latest 0.9-dev version, so I am closing this issue since the download link is recently updated and should be working now.

**Comment by tomek27** [comment]
works like charm :+1: 
thank you
