### ISSUE TITLE
updated xcode 7,got "error generated"

### ISSUE THREAD

**Issue by RogerGan** [oclint/oclint#245]
![image](https://cloud.githubusercontent.com/assets/10350086/9984796/1bb010e0-6051-11e5-95a4-125016132652.png)

**Comment by mdsb100** [comment]
I got the same issuse

**Comment by RogerGan** [comment]
@lqi hi, how to resolve the problem

**Comment by garrettmoon** [comment]
Also seeing this. Any ideas?

**Comment by mdsb100** [comment]
Mac, OCLint version 0.8.1

**Comment by thelvis4** [comment]
I have the same issue.

Also, i've tried the latest ( 0.9.dev.8553ad2) build, and i got "LLVM ERROR: unknown module format"

**Comment by ryuichisaito6** [comment]
@thelvis4 I am working on a fix for it. And could you help me verify one thing: open your compile_commands.json file, search texts for `-fmodules` and `-gmodules`, and delete all matches. Let me know if it works for you?

**Comment by garrettmoon** [comment]
@ryuichisaito6 that got rid of the errors generated at the top, however, it may be a separate issue, but I still see errors after:

```
Compiler Errors:
      (please be aware that these errors will prevent OCLint from analyzing this source code)
      
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:25:28: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:32:4: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:53:4: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:54:4: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: expected ';' after @class
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:16: cannot find protocol declaration for 'ObjectType'
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:25: cannot find protocol declaration for 'ObjectType'
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:37: expected identifier or '('
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:4: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:25: cannot find protocol declaration for 'ObjectType'
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:1: duplicate interface definition for class 'NSEnumerator'
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:37: method type specifier must start with '-' or '+'
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:38: expected a type
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:1: expected selector for Objective-C method
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:28: unknown type name 'NSArray'
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:35: expected member name or ';' after declaration specifiers
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:1: property requires fields to be named
      /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:35: expected ';' at end of declaration list
      :0:0: too many errors emitted, stopping now
      
```

**Comment by RogerGan** [comment]
@ryuichisaito6 when i build oclint 0.9,  I got the python error message
![image](https://cloud.githubusercontent.com/assets/10350086/10036581/044b6012-61dc-11e5-9b98-ff4d558c834e.png)

**Comment by ryuichisaito6** [comment]
@RogerGan Building oclint requires you to clone the git repo, instead of downloading it as a zip/tar archive.

**Comment by thelvis4** [comment]
@ryuichisaito6 It was enough to just delete all ```-gmodules``` occurrences and 0.9.dev.8553ad2 worked perfectly. There was no need to remove ```-fmodules```.

**Comment by ryuichisaito6** [comment]
@thelvis4 I tried to understand this better, do you by any chance know what `-fmodules` and `-gmodules` do respectively?

**Comment by thelvis4** [comment]
@ryuichisaito6 I googled for them a little and i found nothing. The only thing I found was in clang's help:

`-fmodules               Enable the 'modules' language feature`

`-gmodules               Generate debug info that directly references modules or pch`

**Comment by thelvis4** [comment]
@ryuichisaito6 `-gmodules` flag is added when `Enable Clang Module Debugging` in `Build Settings` is YES.

**Comment by RogerGan** [comment]
@ryuichisaito6 If i build 0.9dev,can i solve the "updated xcode 7 problem"?

**Comment by thelvis4** [comment]
@RogerGan Yes, you can bypass the problem by adding `CLANG_ENABLE_MODULE_DEBUGGING=NO` to xcodebuild(or xctool) parameters.

**Comment by RogerGan** [comment]
@thelvis4 error msg:
![image](https://cloud.githubusercontent.com/assets/10350086/10069355/5547884e-62de-11e5-8417-4d50e20cd15d.png)

**Comment by mdsb100** [comment]
坑爹啊

**Comment by RogerGan** [comment]
@thelvis4 i can't find "CLANG_ENABLE_MODULE_DEBUGGING=NO"  in xcodebuild parameters,but in xcode  project config

**Comment by thelvis4** [comment]
@RogerGan If you make the build using `xcodebuild` CLI, you have to call it like this `xcodebuild CLANG_ENABLE_MODULE_DEBUGGING=NO build [other parameters]`.

You said that after setting `Enable Clang Module Debugging` to NO you still got the errors. Does your `compile_commands.json` file contain `-gmodules` or `-fmodules` options? (If you set CLANG_ENABLE_MODULE_DEBUGGING to NO, it should not contain -gmodules. For -fmodules I don't know the setting name because i've never met -fmodules in my `compile_commands.json` files).

**Comment by arturocandela** [comment]
Hi! xctool with the CLANG_ENABLE_MODULE_DEBUGGING=NO build has worked

**Comment by telmopmota** [comment]
Same issue here.

    $ oclint -version
    LLVM (http://llvm.org/):
      LLVM version 3.5.0svn
      Optimized build.
      Built Oct 19 2014 (09:55:19).
      Default target: x86_64-apple-darwin14.5.0
      Host CPU: core-avx2
    OCLint (http://oclint.org/):
      OCLint version 0.8.1.
      Built Oct 19 2014 (10:24:44)
    $ xcodebuild -version
    Xcode 7.0
    Build version 7A220

$ xcodebuild -scheme MyScheme -sdk iphoneos CLANG_ENABLE_MODULE_DEBUGGING=NO ONLY_ACTIVE_ARCH=NO ARCHS=armv7 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO > xcodebuild.log
$ oclint-xcodebuild

No gmodules parameters in compile_commands.json, but fmodules are found and error happens.
Disabling fmodules with CLANG_ENABLE_MODULES=NO gives compile error as we use @import and remove them is not an option. :(

**Comment by thelvis4** [comment]
@telmopmota It only works if you build `OCLint` from master branch by yourself. (as there is no official OCLint 9.0 yet)

**Comment by telmopmota** [comment]
Hi @thelvis4, 
I'm trying to build it, but...

$ git clone https://github.com/oclint/oclint.git
$ cd oclint-scripts
$ ./make
...
[ 61%] Generating ../../../../lib/clang/3.8.0/lib/macho_embedded/libclang_rt.soft_static.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't create temporary output file: /Users/telmomota/git/oclint/build/llvm/./lib/clang/3.8.0/lib/macho_embedded/libclang_rt.soft_static.a.lipo (No such file or directory)

I did not figure out the reason for the error yet. :(
I'm using Xcode 7.0 and cmake-3.3.2-Darwin-x86_64

**Comment by thelvis4** [comment]
@telmopmota Have you tried by any chance to `sudo ./make`?
I don't know why you get this error. It was able to compile it without any problems.

P.S. If you don't find a solution, I can send you the binary compiled on my machine(OS X 10.10.5). Just send me an email.

**Comment by telmopmota** [comment]
@thelvis4, I did not use sudo, but we managed to get it working.
In a second terminal window, while make is running, we did

    $ mkdir -p /Users/telmomota/git/oclint/build/llvm/lib/clang/3.8.0/lib/macho_embedded

**Comment by ryuichisaito6** [comment]
@telmopmota guess this is not an issue related to OCLint code, but it happens while building LLVM/Clang. Probably need to wait Clang community to apply a patch.

**Comment by ryuichisaito6** [comment]
An update on this: `-gmodules` is the only flag that needs to be removed. It can be done by either deleting occurrences from compile_commands.json file, or add `CLANG_ENABLE_MODULE_DEBUGGING=NO` to xcodebuild.

I am currently wondering if there is a way to ignore this flag at the tool level.

**Comment by telmopmota** [comment]
Thought so @ryuichisaito6. Is it the case to change anything on oclint make scripts to address this for the time being?

**Comment by PLJNS** [comment]
Just to add, I'm also getting this issue and I can't install `oclint` myself due to: 

<img width="1191" alt="screen shot 2015-10-01 at 2 40 39 pm" src="https://cloud.githubusercontent.com/assets/1176952/10230329/7bb79ef8-684a-11e5-9db6-3bd3d7efd1a3.png">

**Comment by ryuichisaito6** [comment]
@telmopmota nothing on oclint side that we can do to address llvm/clang broken changes. However, I have been wondering to change to semantic versioning model. Once that happens, will keep the master branch goes with the most recent llvm/clang release, and let the working-in-progress code in a separate branch.

@PLJNS thinking this is also the broken code from llvm/clang.

**Comment by mdsb100** [comment]
Use oclint-0.9.dev.d18b401 
```
Assertion failed: (!isAnnotation() && "getIdentifierInfo() on an annotation token!"), function getIdentifierInfo, file /Users/ryuichis/Projects/L/oclint-ci/oclint/llvm/tools/clang/include/clang/Lex/Token.h, line 181.
```

**Comment by ryuichisaito6** [comment]
I think this is fixed in the latest dev build. Closing this one.

**Comment by erictamlam** [comment]
@RogerGan Has this issue been fixed for you? I have encountered the same problem, and no solutions found yet;(
