### ISSUE TITLE
Xcode 7 - iOS 9

### ISSUE THREAD

**Issue by bbhagat** [oclint/oclint#246]
Hi,

Thanks for the amazing tool. But I have been facing a problem where I am not able to use the tool. The errors I get are as below:

"Expected umbrella, header, submodule or module export".
"Could not build module darwin"
"Could not build module CoreFoundation"

The above three messages are repeated like 100 times. I get this error in both Xcode or command line using the oclint-json-compilation-database tool. 

Is this a known issue?

Regards,
Bhavik

**Comment by ryuichisaito6** [comment]
Thanks @bbhagat. Yes, I am aware of the changes that have been made to Xcode 7 related to modules. Working on a fix.

**Comment by bbhagat** [comment]
Thanks for the confirmation @ryuichisaito6 :+1: 

Will wait for the new version.

Regards,
Bhavik

**Comment by ryuichisaito6** [comment]
I think this is fixed in the latest dev build.

**Comment by nenadvulic** [comment]
Hi,

Someone test the compatibility with xCode 7 ?

**Comment by maxkomarychev** [comment]
I saw this issue in build 0.8.1
```
LLVM (http://llvm.org/):
  LLVM version 3.5.0svn
  Optimized build.
  Built Oct 19 2014 (09:55:19).
  Default target: x86_64-apple-darwin14.5.0
  Host CPU: core-avx2
```
Latest build works fine for me:
```
$ oclint --version
LLVM (http://llvm.org/):
  LLVM version 3.7.0
  Optimized build.
  Built Oct 31 2015 (11:30:54).
  Default target: x86_64-apple-darwin14.5.0
  Host CPU: haswell

OCLint (http://oclint.org/):
  OCLint version 0.10.1.
  Built Oct 31 2015 (12:12:19).
```
made from

1148765c64d10f326b199677166915314fdfabb2

**Comment by bbhagat** [comment]
This issue is fixed in the latest dev build. I have been using the dev build since it was released and it has been working fine for me.
