### ISSUE TITLE
OCLint generates compile_commands.json correctly but does not generate reports

### ISSUE THREAD

**Issue by HireTullioSebastiani** [oclint/oclint#251]
Environment : OCLint version 0.8.1 on Mac OS X 10.11 Xcode 7.0.1.

compile_commands.json is generated correctly,by `oclint-xcodebuild` but when 

`oclint-json-compilation-database -v oclint_args "-report-type html -o report.html -rc=LONG_LINE=120"`

is issued, errors and warning are reported to stdout,

`1 error generated.
3 errors generated.
1 error generated.
1 error generated.
14 errors generated.
1 error generated.
1 error generated.`

but at the end no report is generated.
I tried to use absolute and relative paths, I tried also to use -- instead of oclint_args but the report is not present.

**Comment by ryuichisaito6** [comment]
Issues for supporting Xcode 7 should be fixed by the latest dev build. Please kindly give it a try. If issue still exists, please create a new issue with sample project, so that I can try to reproduce.
