### ISSUE TITLE
NSAssert mistaken as empty do/while statement 

### ISSUE THREAD

**Issue by DarkRockman** [oclint/oclint#258]
As of dev version 0.9.dev.d18b401, all NSAssert statements are mistakenly identified as empty do/while statements, that prevents from getting a correct number of violations, maybe code in macros should be avoided during code revision

**Comment by ws233** [comment]
Any updates on this? I also worry about it.

**Comment by mgrebenets** [comment]
Same with `0.10.2`, don't recall having this problem with `0.8.0`.

**Comment by AbigailBuccaneer** [comment]
This is a special case of #378.

**Comment by ryuichis** [comment]
#378
