### ISSUE TITLE
link error when rebuilding the source code on osx 10.11.1

### ISSUE THREAD

**Issue by xiedingbao** [oclint/oclint#260]
I got the following error when trying to rebuild the source code of oclint:
Linking CXX executable bin/oclint-0.10.1
Undefined symbols for architecture x86_64:
  "llvm::DebugFlag", referenced from:
      oclint::logger::debugStream() in libOCLintDriver.a(Logger.cpp.o)
      oclint::logger::verboseStream() in libOCLintDriver.a(Logger.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/oclint-0.10.1] Error 1

I use command python build to compile the source code.

**Comment by vigneshr89** [comment]
@xiedingbao  I have the same error. Why this issue was closed?. Did you find a solution?
