### ISSUE TITLE
oclint -p compile_commands.json <MyClass.mm> 'type_traits' file not found

### ISSUE THREAD

**Issue by johnofcamas** [oclint/oclint#261]
I have a file that builds just fine if I simply execute the build string in the compile_commands.json file, but when I try to lint it, I get the following error: 

/path/to/MyCastingClassImpl.h:104:10: 'type_traits' file not found

which is declared here:
#ifdef __cplusplus
#include <type_traits>
...

**Comment by johnofcamas** [comment]
One more thing I forgot to mention:
OCLint (http://oclint.org/):
  OCLint version 0.10.1.
  Built Nov 11 2015 (15:51:24).

**Comment by ryuichisaito6** [comment]
I am guessing you are on Mac OS X, so you may have to explicitly set `-I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1` in compile_commands.json file. Let me know if this works for you.

**Comment by johnofcamas** [comment]
Thanks for the quick reply

Two things:
1) I don't have that include directory
2) of/when I find that. how do I add that to my build command file?  Do I add it to each command individually via some regex?

**Comment by johnofcamas** [comment]
Follow up for myself:
1) subtly different location, but I found it (find to the rescue)
2) I'm including it by passing it as an oclint pass-through argument to oclint-json-compilation-database
