### ISSUE TITLE
clang analyzer results not included in json report

### ISSUE THREAD

**Issue by johnofcamas** [oclint/oclint#262]
I just ran oclint and included static analyzer results.  One additional (clang static analyzer results) error is reported when my report type is text, but when I select json, it does not include that error.

**Comment by rmaz** [comment]
They are not in the PMD results either

**Comment by ryuichisaito6** [comment]
Merge with #266.

**Comment by adudurant** [comment]
@johnofcamas   I wonder that you analyzer a simple file or a project?
