### ISSUE TITLE
Missing LLVMSupport linkage in final oclint linkage

### ISSUE THREAD

**Issue by lefta** [oclint/oclint#263]
Building oclint on Linux gives a link error because it is not linked on LLVMSupport.

If you want, here is my git diff : [fix_build.txt](https://github.com/oclint/oclint/files/46717/fix_build.txt)

**Comment by ryuichis** [comment]
@lefta May I know your linux environment? I am using it on Ubuntu 14.04 LTS, and I don't see the linker error.

**Comment by lefta** [comment]
I'm running Gentoo with LLVM 3.7. Please note that the patch is here only to give you an idea of what is wrong and to provide a quick and dirty fix for those who may be affected by the same problem.
I did not dig in your cmake files, so I can not say where the problem comes from exactly, but if you need I may try to figure out the real problem in next days.

**Comment by lefta** [comment]
Fixed in P.R #270
