### ISSUE TITLE
Failed to install llvm/LICENSE.txt when building with external llvm

### ISSUE THREAD

**Issue by lefta** [oclint/oclint#271]
Here is the traceback:
    Traceback (most recent call last):
      File "./bundle", line 118, in <module>
        install_licenses()
      File "./bundle", line 100, in install_licenses
        with open(llvm_license_path, 'r') as llvm_license_file:
    IOError: [Errno 2] No such file or directory: '/home/user/Documents/Code/oclint/llvm/LICENSE.TXT'

building with ./makeWithExternalClang. As llvm was not downloaded, its license file obviously does not exist.

Fixed in PR (ignoring license if the file is not found).

**Comment by ryuichis** [comment]
Fixed in P.R. #270
