### ISSUE TITLE
OCLint skips a bunch of files and presents no results

### ISSUE THREAD

**Issue by TiagoVeloso** [oclint/oclint#274]
I am running OCLint(0.10.1) with xctool with the following script:

```sh
xctool -workspace Project.xcworkspace/ -scheme Debug clean
xctool -workspace Project.xcworkspace/ -scheme Debug -reporter json-compilation-database:compile_commands.json build
oclint-json-compilation-database -v -e Pods \
	 -- -rc=LONG_LINE=200 \
	 -rc=NCSS_METHOD=60 \
	 -rc=LONG_METHOD=100 \
	 -rc=MINIMUM_CASES_IN_SWITCH=1
```

As output I get a bunch of lines saying files were skipped, by the looks of it all of my classes were.

Then the result is:
```sh
OCLint Report

Summary: TotalFiles=0 FilesWithViolations=0 P1=0 P2=0 P3=0

[OCLint (http://oclint.org) v0.10.1]
```

What am I doing wrong?

**Comment by ryuichis** [comment]
@TiagoVeloso is it possible that you can provide some samples like #280 so that I can reproduce locally?

**Comment by TiagoVeloso** [comment]
Hi,

Sorry for my late reply. I've managed to get this working. I think I had a space in my file paths that I wasn't seeing. 

Now all is working.

**Comment by ryuichis** [comment]
@TiagoVeloso thanks for the updates, and glad to know it works for you now.

**Comment by hastyjw** [comment]
Please remove me from this.

John H.

**Comment by hastyjw** [comment]
Please remove me from this.

John H.

> On Jan 18, 2016, at 12:45 PM, Ryuichi Saito <notifications@github.com> wrote:
> 
> @TiagoVeloso thanks for the updates, and glad to know it works for you now.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
John H.

**Comment by chatwyn** [comment]
I have the same question.This is my script
```
#import path
export PATH=${PATH}:/usr/local/bin
#import what we have in bash_profile
source ~/.bash_profile
#check for oclint
hash oclint &> /dev/null
if [ $? -eq 1 ]; then
echo >&2 "oclint not found, analyzing stopped"
exit 1
fi

hash xctool &> /dev/null
if [ $? -eq 1 ]; then
echo >&2 "xctool not found, analyzing stopped"
exit 1
fi

cd ${SRCROOT}
xctool -project SuperLoggerDemo.xcodeproj -scheme SuperLoggerDemo clean
xctool -project SuperLoggerDemo.xcodeproj -scheme SuperLoggerDemo -reporter json-compilation-database:compile_commands.json build
oclint-json-compilation-database \
-e Pods \
-- -rc=LONG_LINE=100 \
-rc=NCSS_METHOD=60 \
-rc=MINIMUM_CASES_IN_SWITCH=1 \
| sed 's/\(.*\.\m\{1,2\}:[0-9]*:[0-9]*:\)/\1 warning:/'
```
The output is
```
Skipping /Users/caowenbo/Desktop/SuperLogger/SuperLoggerDemo/. Compile command not found.
OCLint Report
Summary: TotalFiles=0 FilesWithViolations=0 P1=0 P2=0 P3=0 
```

And  what in my`compile_commands.json`is a empty array.
So what can I do to solve this problem.Thanks!

**Comment by ryuichis** [comment]
@chatwyn  If you have an empty compile_commands.json, please first of all check if the arguments you gave to xctool is correct. oclint relies on a proper configured compile_commands.json to be able to work in your case.

**Comment by ryuichis** [comment]
@chatwyn please also double check if you have spaces in your file path as discussed earlier in this thread.
