### ISSUE TITLE
Allow space after // in //!OCLINT suppress comments

### ISSUE THREAD

**Issue by mgrebenets** [oclint/oclint#276]
Formatters are often configured to force a space after `//` in C-style `// Line comments`. This automatically converts `//!OCLINT` to `// !OCLINT`. Looks like the [source code](https://github.com/lqi/oclint/commit/06079f00dbb177951d6e6f8f307d21c190e1d9f3) will only look for exact match with `find` method.

It would be great to allow space in suppress comments.

I'm having this issue when combined with `uncrustify`'s auto formatting feature (Xcode plugin for Objective-C). There is a work around: use triple slash `///!OCLINT`, but that may be broken by future changes to uncrustify config, so is not very future proof.

**Comment by ryuichis** [comment]
I think by default, `uncrustify` has `sp_cmt_cpp_start` flag turned on for Objective-C, maybe consider turning that off on the uncrustify side?

But frankly, the initial thought when I tried to implement this was like `// NOOCLINT`, but then feels it looks ugly... :wink:  And then decided to use `//OCLINT. Eventually, by intent, introduced the exclamation mark for the purposes that code formatting tools could be configured to ignore it... Apparently, the trick doesn't work. :smirk:

I will leave this issue open for a while, and if we can get several `+1`s, I will work on the code change to support both.

**Comment by mgrebenets** [comment]
Right, `uncrustify` has no option for special treatment of `//!` comments.
Anyway, looks like for clang `// !` is not a _raw_ comment, `//!` should come all together to be part of parsed AST and treated as [RawComment](http://clang.llvm.org/doxygen/classclang_1_1RawComment.html#a1d5ae0acdc245f39b71a158ec9932038). So makes no sense to have space there.

I've addressed this in https://github.com/oclint/oclint/pull/281.

**Comment by ryuichis** [comment]
@mgrebenets so just to understand this better, `//! OCLINT` will also make `uncrustify` happy?

**Comment by mgrebenets** [comment]
@ryuichis not really, if `sp_cmt_cpp_start` is on, it will break it into `// ! OCLINT` anyway. To a certain extent, nothing would make `uncrustify` happy :) 

This change is not a workaround `uncrustify`'s limitations, instead it's to allow `OCLint` spelling per documentation and space after `//!`, which seems to be standard approach for `clang`:

![image](https://cloud.githubusercontent.com/assets/350654/12339893/bb523a04-bb6b-11e5-8004-8d396bf1fb4c.png)

**Comment by ryuichis** [comment]
Thanks for the contribution and clarifications. I am thinking to close this issue, and guessing it might be better for `uncrustify` to support raw comment?

**Comment by mgrebenets** [comment]
What about `OCLint` vs `OCLINT` spelling though? 
Shouldn't either the documentation or the implementation be fixed?

**Comment by mgrebenets** [comment]
Since #281 is merged, this one is good to close.
