### ISSUE TITLE
Does oclint with xcodeIDE support xcode 7 ？

### ISSUE THREAD

**Issue by qiuhm** [oclint/oclint#278]
According to the documentation:http://docs.oclint.org/en/stable/guide/xcode.html
My project is OCLintSample, the script is 
cd ${SRCROOT}
'''xcodebuild -target OCLintSample clean
xcodebuild -target OCLintSample | xcpretty -r json-compilation-database
oclint-json-compilation-database -- -report-type xcode'''
But it doesn't work.

**Comment by ryuichis** [comment]
The OCLint 0.10.2 has the Xcode reporter. The screenshots from the link you posted above were taken from Xcode Version 7.2 (7C68). And for OCLint earlier versions, you may have to work with one of the scripts that do the conversion for you: https://gist.github.com/gavrix/5054182/forks

In addition, you may consider trying the script in your terminal, and make sure it first of all works there.

If you have this sample project available on github, I can grab it and take a look.

**Comment by qiuhm** [comment]
Thanks very much.
I have resolved the problem now.
