### ISSUE TITLE
Make Rule Identifier More Explicit

### ISSUE THREAD

**Issue by ryuichis** [oclint/oclint#279]
The confusions among the rule ID, the rule name, and the rule's dynamic lib name become a very frequently-asked issue recently. 

For example,
`ivar assignment outside accessors or init` is the rule name.
`IvarAssignmentOutsideAccessorsOrInit` is the rule id.
`ObjCAssignIvarOutsideAccessors` is the rule dynamic lib name.

The differences are not well-documented anywhere at the moment. So we need to make some improvements to address this.

**Comment by ryuichis** [comment]
@UnrealQuester I agree with having a more explicit rule identifier. After I opened this issue earlier this year, I have been thinking about it.

Some initial thoughts: 

We could add a new property `identifier` to `RuleBase`. Not sure if we want to default it to the similar implementation to the `convertSpacesInName` method inside `RulesetFilter`. Open for discussion on this.

If there isn't a default, then the scaffold script needs to be updated accordingly.

I was also wondering if an internal driver could be implemented to auto populate the documentation. 

// cc: #329 #319

**Comment by UnrealQuester** [comment]
> We could add a new property identifier to RuleBase. Not sure if we want to default it to the similar implementation to the convertSpacesInName method inside RulesetFilter. Open for discussion on this.

Sounds good. What about backwards compatibility? Changing an identifier might break existing setups.

> I was also wondering if an internal driver could be implemented to auto populate the documentation.

Good point. I don't think there currently is any documentation on the actual rule names, or is there?

**Comment by ryuichis** [comment]
> backwards compatibility

Maybe we can try our best to match the identifiers by applying the same rule as of today. However, I don't worry this too much for the sake of a better and determined approach. Tradeoffs.

> is there?

Ha! I thought there is one... And I just double checked the doc myself, and indeed, we are missing that. I can work on that by leveraging the same internal driver, oclint-dyn-doc-gen ;)

**Comment by UnrealQuester** [comment]
> Maybe we can try our best to match the identifiers by applying the same rule as of today. However, I don't worry this too much for the sake of a better and determined approach. Tradeoffs.

Sounds good to me. Will see if I can open up a PR this weekend.
