### ISSUE TITLE
Compile command not found

### ISSUE THREAD

**Issue by Soryu** [oclint/oclint#290]
I installed via https://github.com/oclint/homebrew-formulae

ran xctool: `xctool --workspace foo.xcworkspace -scheme "foo-Dev" -reporter json-compilation-database:compile_commands.json build`

but oclint gives an error:

```
$ oclint-json-compilation-database -e Pods -v -- -report-type html -o report.html -rc LONG_LINE=300
------------------------------ OCLint ------------------------------
/usr/local/bin/oclint -report-type html -o report.html -rc LONG_LINE=300 ""
--------------------------------------------------------------------
Skipping /Users/soryu/work/foo/foo-ios/. Compile command not found.

```

**Comment by ryuichis** [comment]
@Soryu do you have whitespaces in your file path? Trying to understand the issue. Could you provide a sample project for me to reproduce the issue locally?

**Comment by Soryu** [comment]
Sorry, I found the problem. The compile commands file, despite being multiple megabytes big, do not contain commands for the files I’m interested in. The problem was with xctool. I’m sorry.

**Comment by xhuihui** [comment]
我也遇到了这个问题，折腾半天，最后发现是 compile_commands.json 生成的问题。在项目的当前目录下，重新执行了clear build 命令后。重新执行代码检查就可以了

**Comment by chaiweiwei** [comment]
有具体的步骤吗？我xcodebuild clean了之后还是一样的error。 @xhuihui

**Comment by xhuihui** [comment]
@chaiweiwei 
有一段时间没有看了，放翻了一下wiki当时的命令是这样的
/usr/local/bin/xctool -scheme Autohome -workspace /Users/***/DevPlatform.xcworkspace -sdk iphonesimulator ARCHS=x86_64 VALID_ARCHS=x86_64 CURRENT_ARCH=x86_64 ONLY_ACTIVE_ARCH=NO -reporter json-compilation-database:compile_commands.json clean build;
不知道是否可以帮到你

**Comment by Yueeeeee** [comment]
@Soryu what did you do with xctool to solve the problem
