### ISSUE TITLE
Link error on ubuntu 15.10 for v0.10.2

### ISSUE THREAD

**Issue by arnaudgelas** [oclint/oclint#294]
[ 75%] Built target OCLintDriver
Linking CXX executable bin/oclint-0.10.2
lib/libOCLintDriver.a(Options.cpp.o): In function `oclint::option::process(char const*)':
/home/linux/tools/oclint/oclint-driver/lib/Options.cpp:(.text+0x1ef): undefined reference to `llvm::sys::findProgramByName(llvm::StringRef, llvm::ArrayRef<llvm::StringRef>)'
lib/libOCLintDriver.a(Driver.cpp.o): In function `oclint::Driver::run(clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, oclint::Analyzer&)':
/home/linux/tools/oclint/oclint-driver/lib/Driver.cpp:(.text+0x78): undefined reference to `clang::tooling::getAbsolutePath(llvm::StringRef)'
/home/linux/tools/oclint/oclint-driver/lib/Driver.cpp:(.text+0x5bf): undefined reference to `llvm::sys::fs::getMainExecutable(char const*, void*)'
lib/libOCLintDriver.a(Driver.cpp.o): In function `adjustArguments(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
/home/linux/tools/oclint/oclint-driver/lib/Driver.cpp:(.text+0x1633): undefined reference to `clang::tooling::getClangStripOutputAdjuster()'
/home/linux/tools/oclint/oclint-driver/lib/Driver.cpp:(.text+0x163d): undefined reference to `clang::tooling::getClangSyntaxOnlyAdjuster()'
lib/libOCLintDriver.a(Driver.cpp.o): In function `newCompilerInvocation(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool)':
/home/linux/tools/oclint/oclint-driver/lib/Driver.cpp:(.text+0x1b0f): undefined reference to `llvm::sys::getDefaultTargetTriple()'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/oclint-0.10.2.dir/build.make:148: recipe for target 'bin/oclint-0.10.2' failed
make[2]: *** [bin/oclint-0.10.2] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/oclint-0.10.2.dir/all' failed
make[1]: *** [CMakeFiles/oclint-0.10.2.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ryuichis** [comment]
@arnaudgelas may I know the commands you use for building oclint? I currently don't have a ubuntu 15.10 machine, our CI runs against the latest LTS, and I just checked on AWS and couldn't find an official 15.10 AMI, so, need your help for me to have a better understanding of the issue.

**Comment by ryuichis** [comment]
@arnaudgelas just found the AMI, will try it.

**Comment by arnaudgelas** [comment]
@ryuichis I followed the instructions, i.e. 
`$ cd oclint-scripts`
`$ ./make`

llvm and clang are first built fine, then core, metrics, reporters and rules build fine too...
If I go in build/oclint-drivers, I call make, it is failing...

Is it possible that some libraries are missing in the corresponding CMakeLists.txt file?

Thanks

**Comment by raynebc** [comment]
Ran into the same problem, also running Ubuntu 15.10 (x64).

**Comment by UnrealQuester** [comment]
Can you tell us your default python version?
```bash
python --version
```
I heard that the clang build scripts don't work very well with python3.

**Comment by raynebc** [comment]
Python 2.7.10

**Comment by raynebc** [comment]
Let me know if there's anything else you want me to check.  For now I guess OCLint is just broken on some *nix distros.

**Comment by UnrealQuester** [comment]
You could try using a prebuilt version of clang. While in oclint-scripts do
```bash
./clang prebuilt
./build
```

**Comment by raynebc** [comment]
Clang isn't the goal for me, I already had Clang.  OClint is meant to provide some different checking.

**Comment by UnrealQuester** [comment]
The above mentioned commands build and link oclint against a prebuilt version instead of the usual self compiled libraries when you do `./make`. This might help with the link errors.

**Comment by raynebc** [comment]
I tried your suggested command, but "./clang prebuilt" wasn't considered a valid command.

**Comment by UnrealQuester** [comment]
Did you execute the command from the `oclint-scripts` directory?

**Comment by raynebc** [comment]
I did.  Here is the console output:
```
osboxes@osboxes:~/Downloads/oclint-0.10.2/oclint-scripts$ ./clang prebuilt
usage: clang [-h] [-branch [{trunk,tags/RELEASE_370/final}]] [-rev REV]
             [-clean] [-release] [-j J]
             {checkout,co,update,up,build}
clang: error: argument task_name: invalid choice: 'prebuilt' (choose from 'checkout', 'co', 'update', 'up', 'build')
osboxes@osboxes:~/Downloads/oclint-0.10.2/oclint-scripts$ 
```

**Comment by UnrealQuester** [comment]
It looks like you are on the 0.10.2 tag. Try checking out the latest master.

**Comment by raynebc** [comment]
I downloaded the latest source zip from Github and tested the normal make, and it still failed.  Then I tried your suggestion of using the "clang" script via the "./clang prebuilt" command followed by "./build".  It ended in failure as well, with the culprit buried in a bunch of jibberish:

```
undefined reference to `vtable for llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
```

I've pasted the entire console output of both commands here:
http://pastebin.com/w7MtXpLY

**Comment by raynebc** [comment]
There's also an
```
undefined reference to `clang::tooling::combineAdjusters
```
near the end too.

**Comment by UnrealQuester** [comment]
Can you do `VERBOSE=1 ./build` and paste the output here? This will contain the actual linker command.

**Comment by raynebc** [comment]
Here is the verbose output:
http://pastebin.com/V3fQsDB4

**Comment by UnrealQuester** [comment]
Can you `cd` into `build/oclint-driver` and try the following command?
```
/home/osboxes/Downloads/oclint-master/build/llvm-install/bin/clang++   -O3 -DNDEBUG -std=c++11 -stdlib=libstdc++  -fno-rtti -Wno-c++11-extensions -fPIC -fcolor-diagnostics   CMakeFiles/oclint-0.10.2.dir/main.cpp.o CMakeFiles/oclint-0.10.2.dir/reporters_dlfcn_port.cpp.o CMakeFiles/oclint-0.10.2.dir/rules_dlfcn_port.cpp.o  -o bin/oclint-0.10.2  -L/home/osboxes/Downloads/oclint-master/build/oclint-core/lib -rdynamic lib/libOCLintDriver.a -L/home/osboxes/Downloads/oclint-master/build/llvm-install/lib -lOCLintRuleSet -lOCLintCore -lclangStaticAnalyzerFrontend -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangRewriteFrontend -lclangRewrite -lclangTooling -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMAsmParser.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMBitReader.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMInstrumentation.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMMCParser.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMOption.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMSupport.a -ldl /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMTransformUtils.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMipa.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMAnalysis.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMCore.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMMC.a /home/osboxes/Downloads/oclint-master/build/llvm-install/lib/libLLVMSupport.a -lrt -ldl -lpthread -lm -Wl,-rpath,/home/osboxes/Downloads/oclint-master/build/oclint-core/lib
```
This is the same command cmake generated with an additional `-L/home/osboxes/Downloads/oclint-master/build/llvm-install/lib`.

**Comment by raynebc** [comment]
The resulting output of that command:
http://pastebin.com/vBQ1ktit

**Comment by UnrealQuester** [comment]
I could reproduce the error on a 15.10 VM. The issue seems to be ABI incompatibilities in the libstdc++ versions. Upgrading to clang 3.8 might fix this. We will have to wait for #320.

**Comment by lefta** [comment]
Clang prebuilt version is for Ubuntu 14.04, using GCC <= 4.9. I did not find about Ubuntu 15.10 GCC version, but I'm quite sure it uses GCC >= 5.1. GCC 5.0 and 5.1 introduced libc++ ABI breakage, resulting in your link error. So using the prebuilt clang version will not work.

**Comment by ryuichis** [comment]
Believe the issue has been fixed along with #350. We now have Travis CI that runs both gcc v4 and v5.

**Comment by raynebc** [comment]
I downloaded the latest source code and ran the normal make script in Ubuntu 15.10.  It took quite a while (1.5 to 2 hours) and eventually ended with the following:
http://pastebin.com/KyqNHK30

I'm not sure what the git complaint at the end is all about, but I see that the oclint-master/build/oclint-driver/bin/oclint-0.10.4 binary was created, and the binary executes as expected if no arguments or the -help or -version parameters are given.  Should I conclude that the build succeeded and go ahead and use it?

**Comment by lefta** [comment]
Yups, its built, but the installation failed. The binaries can still be found in the project tree, unfortunately I don't remember where exactly.

You should fill a new bug report for this one, if it does not already exist.

**Comment by raynebc** [comment]
I created a new bug report for that behavioral problem:
https://github.com/oclint/oclint/issues/352
