### ISSUE TITLE
The rule in the command doesn't work

### ISSUE THREAD

**Issue by qiuhm** [oclint/oclint#296]
I execute the shell as below:
`oclint-json-compilation-database -- -o oclint.xml -rule LongLine,ConstantConditionalOperator,ConstantIfExpression,DeadCode,DoubleNegative,ForLoopShouldBeWhileLoop,GotoStatement,JumbledIncrementer,MisplacedNilCheck,MisplacedNullCheck,MultipleUnaryOperator,ObjCVerifyIsEqualHash,ObjCVerifyMustCallSuper,ObjCVerifyProtectedMethod,ObjCVerifySubclassMustImplement,AvoidBranchingStatementAsLastInLoop,CoveredSwitchStatementsDontNeedDefault,DefaultLabelNotLastInSwitchStatement,DestructorOfVirtualClass,MissingBreakInSwitchStatement,NonCaseLabelInSwitchStatement,ParameterReassignment,SwitchStatementsShouldHaveDefault,TooFewBranchesInSwitchStatement,EmptyCatchStatement,EmptyDoWhileStatement,EmptyElseBlock,EmptyFinallyStatement,EmptyForStatement,EmptyIfStatement,EmptySwitchStatement,EmptyTryStatement,EmptyWhileStatement,UnnecessaryNullCheckForCXXDealloc,UnusedLocalVariable`
It didn't analyze one issue.But I just set the rules in the configuration file.It works and finds out many issues.

**Comment by ryuichis** [comment]
I didn't look into your rule identifiers, but basically, you need to do `-rule A -rule B -rule C`. Let me know if this works for you.

**Comment by qiuhm** [comment]
Yes,It wroked.Thanks very much.
