### ISSUE TITLE
OCLint doesn't run rules against header files?

### ISSUE THREAD

**Issue by daniel-beard** [oclint/oclint#298]
- A common use case is checking `@property` declarations in Objective-C files.
- I can't get OCLint to analyze header files. Is this a known issue?

**Comment by ryuichis** [comment]
This is a good discussion to have, thanks for bringing this up.

The reason for not checking header files is to eliminate all sort of potential issues that comes from the system headers. We currently don't have a way to distinguish whether a particular header is from Apple, is from third-party libraries/frameworks, or is written by users. 

Open to suggestions.

**Comment by daniel-beard** [comment]
I think a good starting point would be the ability to specify a whitelist.
A common use case I have (working on a larger project) is that we don't often want to run linting against an entire project, but rather against a diff from a PR (so we know what files are user written).

Where's a good place to start looking into this? I'm guessing something within `oclint-driver`?

**Comment by daniel-beard** [comment]
I have some time and resources to contribute, so I can help out where I can, with a little guidance.

**Comment by ryuichis** [comment]
Thanks @daniel-beard for your interests in contributing to the project. 

`oclint-driver` is a good place to have the whitelist configurations. 

And if you look into 

https://github.com/oclint/oclint/blob/master/oclint-rules/include/oclint/AbstractASTVisitorRule.h#L31

You will find all header files at the moment are emitted for analysis. We probably need to think about a way to include certain header files based on the whitelist configurations. 

In addition, we also need to consider the duplications from header files. I think the default `UniqueResults` from take care of the duplicated issues from the report generations, however, it will be better to think about the cases where same header files are included by multiple implementation files.

**Comment by daniel-beard** [comment]
Cool, I'll take a look at this. I think a whitelist is a good starting point, but eventually I'd like to look into fuzzy matching (e.g. if we have a .m file, there is *probably* a matching .h file with the same name)

**Comment by ryuichis** [comment]
@daniel-beard great, we can definitely take baby steps.

**Comment by tinaprsl** [comment]
I think that you are probably going to find that's a real good idea( it was recommended to me), and worked great.

**Comment by daniel-beard** [comment]
Logging the output from https://github.com/oclint/oclint/blob/master/oclint-rules/include/oclint/AbstractASTVisitorRule.h#L31 I only get a couple of system files. The matching header file from my source file is not included. Any tips?

**Comment by tinaprsl** [comment]
Output the header file to match what you have for your source file; I believe that you will get a response from doing that. You should have a new system file when you do this somewhere in your system. Find it, and then place it where you want either with the other system files or a temporary file,but you may need to extract it.Seriously it will depend on what you want to use the header file for, either permanent or temporary...the system will tel you when it's ready.

**Comment by ryuichis** [comment]
@daniel-beard it makes me wonder if there are anything related to the clang modules http://clang.llvm.org/docs/Modules.html. I haven't worked with it myself, but still want to point it out to cause your attention.

**Comment by bok** [comment]
Hey guys,

At my job, we use OCLint internally with our own rule set. I have written the feature you are talking about in this thread, but implemented it with a blacklist (== excludes) instead of a whitelist.

You can find the code here [1], if you find it useful I can add some tests and make a PR.

[1] https://github.com/bok/oclint/tree/for-upstream/feature/user-headers-and-excludes

**Comment by daniel-beard** [comment]
Thanks @bok I'll check it out and see if it works for me!

**Comment by daniel-beard** [comment]
@bok your change works great for me. Wondering if we should hide it behind a flag and also have whitelist behavior as well. E.g. Whitelisting everything inside the root project folder, ignore all other headers.

**Comment by abigailbunyan** [comment]
A potentially simpler approach would be to generate warnings for includes from paths with `-I` but not with `-isystem` - this is the same approach as gcc and clang already use for generating warnings in header files, so it'd be nicely consistent.

**Comment by Beniamiiin** [comment]
@bok are you going to do pull-request this feature?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Comment by JohnCoates** [comment]
Great addition, @bok!
