### ISSUE TITLE
oclint: error: cannot find dynamic library for report type: text

### ISSUE THREAD

**Issue by qiuhm** [oclint/oclint#305]
When I run :  oclint-json-compilation-database -- -o oclint.xml -rule LongLine

It infos the error:oclint: error: cannot find dynamic library for report type: text

My enviroment infomation is as below:
LLVM (http://llvm.org/):

  LLVM version 3.7.0

  Optimized build.

  Built Dec 28 2015 (09:59:04).

  Default target: x86_64-apple-darwin14.5.0

  Host CPU: ivybridge

OCLint (http://oclint.org/):

  OCLint version 0.10.2.

  Built Dec 28 2015 (10:15:51).

So what's the problem?

**Comment by ryuichis** [comment]
I believe there must be something wrong with the installations. Please make sure your folder structure looks like this http://docs.oclint.org/en/stable/intro/installation.html

**Comment by qiuhm** [comment]
Thanks .
I have checked my folder structure,it is right.
But I changed the way to set my environment setting,it worked.It is so confusing,I don't get the point.
The way I used to set is : ln -s ~/software/oclint/bin/ /usr/bin
Now the way is modifying the file ~/.bash_profile，just add PATH= ~/software/oclint/bin:$PATH,it just worked.
