### ISSUE TITLE
Suppress warning for macro

### ISSUE THREAD

**Issue by dmigous** [oclint/oclint#309]
I am using third party logger log4cplus, which has macroses like `LOG4CPLUS_DEBUG(msg)` to do logging. OCLint shoots warning 
- double negative
- short variable name

Surely I can't write along each `LOG4CPLUS_DEBUG()` statement a comment to suppress `// !OCLINT`. Also I can't add to macro `__attribute__` even if I will wrap it into another macro. Wrapping into functions isn't a way to go because logger macrsoses use `__FILE__, __LINE__` to print traces.

Is there way to solve this issue?

**Comment by bart-kneepkens** [comment]
+1

**Comment by jeppefrandsen** [comment]
+1

**Comment by ryuichis** [comment]
#378
