### ISSUE TITLE
Could not find a package configuration file provided by "LLVM" with any of   the following names:      LLVMConfig.cmake     llvm-config.cmake

### ISSUE THREAD

**Issue by qiuhm** [oclint/oclint#317]
When I checkout all the source code ,I change the directory to ../oclint-rules/.
Then I execute ```cmake .```
It infos the errors as below:

Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
I just followed as the document as http://docs.oclint.org/en/stable/devel/checkout.html.

**Comment by UnrealQuester** [comment]
If you want to build oclint from source, you should follow [this document](http://docs.oclint.org/en/stable/intro/build.html).

**Comment by qiuhm** [comment]
Dear UnrealQuester,Thanks you。
I try to write customer rules。
Until now I have completed a customer rule.But I don't know how to build it and make it live?
Can you give me some help about that? I have [questioned](https://github.com/oclint/oclint/issues/318) befor.
Thanks again.
