### ISSUE TITLE
How to build rule in order to generate a dynamic library?

### ISSUE THREAD

**Issue by qiuhm** [oclint/oclint#318]
@UnrealQuester @ryuichis I have written the rule code,but I don't know how to build rule.
Could  anyone give me some specific introduction? Thanks very much.
I have read the document at http://docs.oclint.org/en/stable/devel/rules.html#build-it-and-make-it-live.

**Comment by UnrealQuester** [comment]
The easiest way to do this would probably be to put your rule file into
 `oclint-rules/rules/<Category>/` and add your rule file to the CMakeLists file in this directory. If you want to add a new category, you also need to add it to `oclint-rules/rules/CMakeLists.txt`.

**Comment by qiuhm** [comment]
Thanks for your advice  @UnrealQuester 
I just do it like you mentioned before.
Then I change the directory to the ```oclint-rules/``,I execute ```cmake .```,and after this ,I execute ```make```,it generates dynamic library in ```oclint-rules/rules.dl/```,then I copy the rules to the ```$(/path/to/bin/oclint)/../lib/oclint/rules```.
Then I execute ```xctool \
-project ${PROJECT_NAME}.xcodeproj  \
-scheme ${PROJECT_NAME} \
-reporter json-compilation-database:compile_commands.json \
build ```,it generate the compile_commands.json and execute ```oclint-json-compilation-database --```,it doesn't generate the oclint.xml.
But if I change the rules to what I donwload from your release package,it works fine.
I try to analysis the difference between the rule I generate and the rule I download from your [release package](https://github.com/oclint/oclint/releases/tag/v0.10.2)
I find that the size of the rule I genarate is >3M,but the rule I download from the github is >30 KB, is there anything wrong for me ?
I think the way I compile the rule and link against ```LLVMSupport, clangASTMatchers, OCLintMetric, OCLintUtil, and OCLintCore``` libraries may be wrong.
Could you give me the specific way how to compile the rule and link against ```LLVMSupport, clangASTMatchers, OCLintMetric, OCLintUtil, and OCLintCore``` libraries.
Thanks very much again!

**Comment by qiuhm** [comment]
@UnrealQuester Could you give me more introduction about how to compile the rule and link against ```LLVMSupport, clangASTMatchers, OCLintMetric, OCLintUtil, and OCLintCore```?
I am suspend here.
Thanks very much!

**Comment by UnrealQuester** [comment]
@qiuhm The build_dynamic_rule macro in oclint-rules/rules/CMakeLists.txt does this for you.

**Comment by qiuhm** [comment]
3ks very much.I have resolved the problem.

**Comment by nicolasiJasica** [comment]
I have the same problem.

Can u explain how to solve it?

**Comment by BigNewbiePlus** [comment]
I also have the same problem, can u share it? @qiuhm
