### ISSUE TITLE
Can't disable NcssMethodCount rule

### ISSUE THREAD

**Issue by herbert1119** [oclint/oclint#319]
Can't disable NcssMethodCount rule but can change thresholds

**Comment by UnrealQuester** [comment]
The rule is actually called "HighNcssMethod". The rule name are generated like this:

- Take the rule name that is displayed in the oclint output ("high ncss method")
- Capitalize every word ("HighNcssMethod")
- Remove spaces ("HighNcssMethod")

@ryuichis Maybe we can mention the actual rule name in the output? Would provide a PR for that if you agree.

**Comment by ryuichis** [comment]
@herbert1119 the issue has been address in #334, and I will update the doc hopefully in a week or so.
