### ISSUE TITLE
Some variables are meant to be unused

### ISSUE THREAD

**Issue by kees-jan** [oclint/oclint#32]
Consider the following:
```C++
#include <boost/thread.hpp>

boost::mutex mut;

int main()
{
  boost::mutex::scoped_lock lock(mut);
  // Do work
  
  return 0;
}
```

When running this through oclint 0.6, it claims (correctly)

    /home/kees-jan/src/tt/tt.cc:9:3: unused local variable P2

At this point, I do not want to disable the rule altogether (it might find some useful errors), but I also don't want to annotate each and every time I lock a mutex (or use a similar RAII style construct).

What is the recommended approach here?

**Comment by ryuichisaito6** [comment]
This is addressed in #249, so I am closing this one.
