### ISSUE TITLE
How to use this to check for Swift Code?

### ISSUE THREAD

**Issue by steve21124** [oclint/oclint#321]

**Comment by ryuichis** [comment]
Short answer: unfortunately no. 

Long answer:

With very minimal changes, oclint-core, oclint-metrics, oclint-reporters, oclint-driver can be ported to swiftlint-* easily. Considering the nature differences between Objective-C and Swift, we need to come up with new set of rules for linting Swift code. 

I am not intending to work on the swiftlint from oclint, but I believe the community would highly appreciate if someone start working on this on a branch. 

[realm/swiftlint](https://github.com/realm/SwiftLint) is one available option in the market for swift lintint based on SourceKit.

**Comment by thelvis4** [comment]
@steve21124 Try [Taylor](https://github.com/yopeso/Taylor). It doesn't support all the rules oclint has, but it's fast and works pretty well.

**Comment by ryuichis** [comment]
Just an update to this, I am working on a static code analyzer for Swift language, check it out from http://yanagiba.org/swift-lint. It's still working in progress, but may help some people already.
