### ISSUE TITLE
segmentation fault or no output

### ISSUE THREAD

**Issue by pvinis** [oclint/oclint#322]
i run `oclint-json-compilation-database` and get no output. then i run `oclint-json-compilation-database` and copy the whole verbose command, run that, and i get a segmentation fault just with that `zsh: segmentation fault  oclint`.

**Comment by UnrealQuester** [comment]
Can you give us some more more information on your system and evironment?

**Comment by pvinis** [comment]
i have the latest oclint, osx, xcode and xcpretty. but the files getting compiled are almost 900.
On Wed, May 4, 2016 at 20:06, Alexander Freiherr von Buddenbrock <notifications@github.com> wrote:
Can you give us some more more information on your system and evironment?

**Comment by UnrealQuester** [comment]
By 'latest oclint' do you mean the current 0.10.2 release or the version from the latest master?

If the project is open source, can you post a link so we can try to reproduce the issue? If not, you will have to try to reduce the number of files until you can narrow down the problem so we can reproduce it.

**Comment by pvinis** [comment]
0.10.2. latest on homebrew from your tap. its not open source, so yea i will try reduce them and see.

On Thu, May 5, 2016 at 20:10, Alexander Freiherr von Buddenbrock <notifications@github.com> wrote:
By 'latest oclint' do you mean the current 0.10.2 release or the version from the latest master?

If the project is open source, can you post a link so we can try to reproduce the issue? If not, you will have to try to reduce the number of files until you can narrow down the problem so we can reproduce it.

**Comment by UnrealQuester** [comment]
Maybe this is the same problem as #323. Does the PR in #333 help?
