### ISSUE TITLE
EXC_BAD_ACCESS crash report

### ISSUE THREAD

**Issue by LiVincent-Zhang** [oclint/oclint#336]
Process:               oclint [7566]
Path:                  /usr/local/bin/oclint
Identifier:            oclint
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Python [7563]
Responsible:           iTerm2 [1134]
User ID:               501

Date/Time:             2016-05-24 11:40:08.106 +0800
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        9CEEE24F-802C-C27B-1644-BBA5EA7C7902

Time Awake Since Boot: 6800 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007ff5e4806268

VM Regions Near 0x7ff5e4806268:
    MALLOC_SMALL           00007ff5e0800000-00007ff5e2800000 [ 32.0M] rw-/rwx SM=PRV  
--> 
    STACK GUARD            00007fff595df000-00007fff5cddf000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   oclint                        	0x00000001031aef6e clang::SourceManager::getBufferData(clang::FileID, bool*) const + 142
1   libLongLineRule.dylib         	0x000000010b30455c oclint::AbstractSourceCodeReaderRule::apply() + 76 (AbstractSourceCodeReaderRule.cpp:17)
2   oclint                        	0x000000010262e4fd oclint::RulesetBasedAnalyzer::analyze(std::__1::vector<clang::ASTContext*, std::__1::allocator<clang::ASTContext*> >&) + 333
3   oclint                        	0x0000000102628cf0 invoke(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, clang::tooling::CompileCommand>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, clang::tooling::CompileCommand> > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, oclint::Analyzer&) + 1120
4   oclint                        	0x000000010262819c oclint::Driver::run(clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, oclint::Analyzer&) + 1212
5   oclint                        	0x000000010262379c main + 268
6   libdyld.dylib                 	0x00007fff81e0e5ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007ff5e092f3a8  rbx: 0x0000000000000000  rcx: 0x000000000000000e  rdx: 0x0000000000004000
  rdi: 0x00007ff5e0431440  rsi: 0x00000000e09489f0  rbp: 0x00007fff5d5ddb50  rsp: 0x00007fff5d5ddb10
   r8: 0x5353414c435f474e   r9: 0x0000000000000000  r10: 0x0000000103495401  r11: 0x00000001031aeee0
  r12: 0x00007ff5e040a0a0  r13: 0x00000000007dadd8  r14: 0x00007ff5e0431440  r15: 0x000000001f6b760e
  rip: 0x00000001031aef6e  rfl: 0x0000000000010202  cr2: 0x00007ff5e4806268
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14

**Comment by UnrealQuester** [comment]
Thankl you for submitting a bug report and appending the stack trace.
Are you using the latest master or the official 0.10.2 release?
If the code is not propietary, can you also post the file you were trying to check?

**Comment by LiVincent-Zhang** [comment]
@UnrealQuester The version of oclint I used is latest official release. After I clone the master and compiled it myself, oclint works fine. It seems that the bug is solved somehow.

**Comment by UnrealQuester** [comment]
@LiVincent-Zhang I see. This particular issue might have been fixed in #314.

**Comment by LiVincent-Zhang** [comment]
@UnrealQuester Yeah, let me close this issue
