### ISSUE TITLE
oclint-json-compilation-database failed

### ISSUE THREAD

**Issue by hujiachun** [oclint/oclint#340]
XXXXXX
** CLEAN SUCCEEDED ** (18255 ms)

hujiachun:PALifeApp-master hujiachun684$ xctool -workspace  /Users/hujiachun684/Downloads/PALifeApp-master/PALifeApp.xcworkspace -scheme PALifeApp -reporter json-compilation-database:compile_commands.json build 
hujiachun:PALifeApp-master hujiachun684$ oclint-json-compilation-database -e Pods -v -- -report-type html -o report.html
------------------------------ OCLint ------------------------------

XXXXX
--------------------------------------------------------------------

oclint: error: violations exceed threshold
P1=1[0] P2=4227[10] P3=17872[20]

**Comment by UnrealQuester** [comment]
> oclint: error: violations exceed threshold

You may want to raise the threshold for all violations. See http://docs.oclint.org/en/stable/manual/oclint.html
Ensure the max-priority settings are higher than the number of violations in your project for that priority level.
