### ISSUE TITLE
Specify compile_commands.json file path

### ISSUE THREAD

**Issue by cerberillo** [oclint/oclint#342]
I wold like to be able to specify `compile_commands.json` file path

``` bash
oclint -c <PATH_TO_JSON>
#OR
oclint -compile <PATH_TO_JSON>
```

This will allow not just to specify different compilation files (like generating a compilation files per platform or configuration flavors).

So, if instead of reading directly from `compile_commands.json` where the command is being invoked I would be able to specify It manually (specially useful for CI servers that I don't manage)

**Comment by ryuichis** [comment]
Thanks @cerberillo  for bringing this up. And I also notice the pull request you sent on the other repo, appreciate that as well.

I think oclint already provide a way to specify the compile_command.json file name. Do you want to give it a try, and see if it works?

```
Ryuichis-MacBook-Pro:oclint ryuichis$ oclint --help
USAGE: oclint [options] <source0> [... <sourceN>]

...

-p <build-path> is used to read a compile command database.

	For example, it can be a CMake build directory in which a file named
	compile_commands.json exists (use -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
	CMake option to get this output). When no build path is specified,
	a search for compile_commands.json will be attempted through all
	parent paths of the first input file . See:
	http://clang.llvm.org/docs/HowToSetupToolingForLLVM.html for an
	example of setting up Clang Tooling on a source tree.

...

For more information, please visit http://oclint.org
Ryuichis-MacBook-Pro:oclint ryuichis$ 
```
