### ISSUE TITLE
Error thrown at end of make script

### ISSUE THREAD

**Issue by raynebc** [oclint/oclint#352]
As originally reported here:
https://github.com/oclint/oclint/issues/294#issuecomment-232155673

I downloaded the source zip file as of today (commit SHA 0cafd451123d7f80125619eac5528239d896c9b9) and ran the make script in a VM running Ubuntu 15.10.  It took 1.5 to 2 hours to complete, but when it did, this was the end of the console output:
http://pastebin.com/KyqNHK30

The oclint executable seems to work, but lefta believes the above output reflects an install error and asked for a ticket to be created.

I ran make install to see what would happen, but it was taking ages and then it reported that svn timed out, so I guess it was downloading source code and it nuked the build that had just taken a couple hours to get.  Oh well, back to the drawing board.

**Comment by ryuichis** [comment]
I don't think it's related to the linker error, as you mentioned, the binary has been generated.

It's more of an issue about how the build script is being used. May I know how you compile the project?

And will `./bundle -release` work for you?

**Comment by raynebc** [comment]
I followed the normal process of changing directory to oclint-master/oclint-scripts and using ./make

My calling "./make install" seemed to destroy the binaries created from the regular ./make, and no matter how many times I ran that command it always kept timing out somewhere in the process of downloading source files from SVN.

"./bundle -release" fails with the following output:
http://pastebin.com/EuzDPL47

I suppose I'll just re-run the standard ./make command to get a working executable again.

**Comment by ryuichis** [comment]
Okay, following the following command, we'll see

```
./ci -reset
./clang prebuilt
./build -release
./bundle -release
```

**Comment by raynebc** [comment]
Those first two commands completed without any errors, but the third one was more of a doozy:
http://pastebin.com/eh7bXY1m

Since the third line didn't succeed, I didn't try the fourth one.

**Comment by ryuichis** [comment]
What ubuntu version you are running?

**Comment by raynebc** [comment]
Ubuntu 15.10.  I can also test with Ubuntu 16 if you think it makes any difference.

**Comment by ryuichis** [comment]
@raynebc Ubuntu 16 should work, would you try that?

I can think of another potential solution, but I have not been it myself, so I am not quite sure. However would you also try to edit `oclint-scripts/clang` file, and insert a newline at line 107 (https://github.com/oclint/oclint/blob/master/oclint-scripts/clang#L107) with `binary_url = 'http://clang-snapshots.oclint.org/llvm-3.8.1-final-ubuntu-16.04-oclint-16.07.11.tar.gz'`?

**Comment by ryuichis** [comment]
Actually, another possible solution, but it requires a stable network

```
./ci -reset
./clang co
./clang build -release
./build -release
./bundle -release
```

**Comment by raynebc** [comment]
I booted my Ubuntu 16 VM and after installing cmake, that earlier set of commands succeeded without error and created an oclint binary:
```
./ci -reset
./clang prebuilt
./build -release
./bundle -release
```

I booted up the Ubuntu 15 VM and retried with your suggested edit of the clang script.  The third line still failed though (earlier than before):
http://pastebin.com/UJi7a4wK

On the Ubuntu 15 VM again, I undid the suggested edit of the clang script and tried your last set of 5 commands:
```
./ci -reset
./clang co
./clang build -release
./build -release
./bundle -release
```
Each step other than the first and last took quite some time to complete, but no errors were given and an oclint binary was created.  I'm not sure why SVN checkout would have been necessary in the steps though, just running the alternate build command should have given identical results and saved quite a bit of time.  Does the checkout somehow give different source code results to downloading Github's zip file of the latest codebase?

**Comment by raynebc** [comment]
After some trial and error I made a script to run it for each source file in my project and redirect the output to file for review.  I did find that if the path given to a source file includes a backslash as the folder separator instead of the correct forward slash for *nix environments, oclint segment faults.  Is that something I should mention in another bug report?

**Comment by UnrealQuester** [comment]
> After some trial and error I made a script to run it for each source file in my project and redirect the output to file for review.

Depending on your build system setup in your project you can use oclint-json-compilation-database for that. See the documentation for [CMake](http://docs.oclint.org/en/stable/guide/cmake.html) or [general makefiles](http://docs.oclint.org/en/stable/guide/bear.html).

> I did find that if the path given to a source file includes a backslash as the folder separator instead of the correct forward slash for *nix environments, oclint segment faults. Is that something I should mention in another bug report?

It would be great if you could create a separate issue for this.

**Comment by raynebc** [comment]
I looked at the JSON database stuff for a little bit, but decided a script was easy enough and wouldn't require learning how to build and use another tool.

I've reported the crash issue in ticket #353.

**Comment by ryuichis** [comment]
#356 is submitted to fix the initial issue reported in this thread. 

@raynebc could you help download the changes with https://github.com/ryuichis/oclint/archive/make-with-source-code.zip, and simply run `./make` as you initially did on Ubuntu 15.10? It probably will take another 2 hours... Thanks!

**Comment by raynebc** [comment]
The script failed immediately after it reported that oclint was built:
http://pastebin.com/57NKgbdW

**Comment by ryuichis** [comment]
@raynebc it has been a while, but I just updated the `make-with-source-code` branch. I made sure it's working on my Ubuntu 16.04 machine. Could you help double check if it's working for you on 15.10? Thanks. 

Link for the updated changes: https://github.com/ryuichis/oclint/archive/make-with-source-code.zip

**Comment by raynebc** [comment]
I downloaded your updated version and followed the normal process of changing directory to oclint-master/oclint-scripts and using ./make

The build failed after performing checkout of some packages because cmake 3.4.3 or higher wasn't installed.  From what I could immediately understand, Ubuntu 15.10 doesn't officially seem to support a version higher than 3.2.2 without some kind of apt-get sources hack of some kind.  I could try on Ubuntu 16, but for the time being it doesn't seem like Ubuntu 15 will support oclint out of the box anymore due to this requirement.

**Comment by ryuichis** [comment]
Yeah, I hear you.  Even though we actually only require cmake 2.8, unfortunately, a higher cmake version is a requirement for LLVM/Clang, which is out of our control.

I think it is an issue for oclint devs, who need to upgrade cmake in order to compile and build oclint; and for people who customize oclint and build locally. For people who use oclint by downloading our prebuilt binary, they are fine.

**Comment by ryuichis** [comment]
I also tried with downloading cmake 3.6.1 from https://cmake.org/download/ to a Ubuntu 14.04 box, and then add its bin folder to my path. It's quite straight forward

**Comment by raynebc** [comment]
I could do such a thing in Windows without batting an eye, but I'm less familiar with Linux.  Does the above cmake offering not have a make script that allows formally installing to the system and require editing the user/system path environment variable?

**Comment by ryuichis** [comment]
I am not aware of any. I tried with apt-get, however, I think it is not caught up with the LLVM requirements yet. Not sure if http://llvm.org/docs/CMake.html will help. 

I downloaded https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.sh the other day, and `sh cmake-3.5.2-Linux-x86_64.sh` for installation. Then I just `export PATH=/path/to/cmake/bin:$PATH`. Hope this helps a little.

**Comment by raynebc** [comment]
Running the bootstrap script, make and then make install seemed to install the latest cmake without any difficulty.  After that, the source code package you provided built and resulted in a "oclint-0.10.4" binary.  I didn't really do much to test it yet, just ran it without arguments to make sure it complained about that.  It seems to have worked.

**Comment by ryuichis** [comment]
Great, thanks @raynebc for the help! I will merge the pull request so that a larger group of users can also help test.
