### ISSUE TITLE
oclint doesn't read .oclint configuration file. 

### ISSUE THREAD

**Issue by masters3d** [oclint/oclint#361]
http://stackoverflow.com/questions/38516125/how-to-tell-oclint-to-load-oclint-file-on-traviscl

Reference 

https://github.com/exercism/xobjective-c/pull/110

**Comment by masters3d** [comment]
I moved away from .oclint file and instead gave the rules directly to the command line.

**Comment by guzuqing** [comment]
oclint doesn't read .oclint configuration file 
i met this error too,  if i do not want to moved away from .oclint file and instead gave the rules directly to the command line..how can i do to solve this error? need your help !thank you
