### ISSUE TITLE
frequently hit assert on DeclKind != Decl::LinkageSpec

### ISSUE THREAD

**Issue by simpleease** [oclint/oclint#364]
when using debug  version for  oclint 0.10.3,  the following assert is frequently hitted,  seems not to a specified .m file, but to any one.

Assertion failed: (DeclKind != Decl::LinkageSpec && "Should not perform lookups into linkage specs!"), function lookup, file /Volumes/DataHD/src/oclint-src/oclint-src/llvm/tools/clang/lib/AST/DeclBase.cpp, line 1370.

The above assertion still exist even only one rule, such as libBaseClassDestructorShouldBeVirtualOrProtectedRule.dylib,  is applied.

The backtrace as follow:

0   oclint                              0x000000010522243f _ZNK5clang11DeclContext6lookupENS_15DeclarationNameE + 111
1   oclint                              0x000000010445b328 _ZN5clang9ASTWriter23GenerateNameLookupTableEPKNS_11DeclContextERN4llvm15SmallVectorImplIcEE + 2360
2   oclint                              0x000000010445cb96 _ZN5clang9ASTWriter29WriteDeclContextVisibleUpdateEPKNS_11DeclContextE + 150
3   oclint                              0x000000010446dc52 _ZN5clang9ASTWriter12WriteASTCoreERNS_4SemaEN4llvm9StringRefERKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEPNS_6ModuleE + 11634
4   oclint                              0x000000010446ad56 _ZN5clang9ASTWriter8WriteASTERNS_4SemaERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEPNS_6ModuleEN4llvm9StringRefEb + 326
5   oclint                              0x00000001044e2139 _ZN5clang12PCHGenerator21HandleTranslationUnitERNS_10ASTContextE + 905
6   oclint                              0x0000000104118417 _ZN5clang17MultiplexConsumer21HandleTranslationUnitERNS_10ASTContextE + 455
7   oclint                              0x00000001045004e0 _ZN5clang8ParseASTERNS_4SemaEbb + 1280
8   oclint                              0x00000001040da035 _ZN5clang17ASTFrontendAction13ExecuteActionEv + 485
9   oclint                              0x00000001040d95d0 _ZN5clang14FrontendAction7ExecuteEv + 112
10  oclint                              0x0000000104022124 _ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE + 1828
11  oclint                              0x00000001040313b7 _ZZL17compileModuleImplRN5clang16CompilerInstanceENS_14SourceLocationEPNS_6ModuleEN4llvm9StringRefEENK3$_1clEv + 39
12  oclint                              0x0000000104031385 _ZN4llvm12function_refIFvvEE11callback_fnIZL17compileModuleImplRN5clang16CompilerInstanceENS4_14SourceLocationEPNS4_6ModuleENS_9StringRefEE3$_1EEvl + 21
13  oclint                              0x0000000105757569 _ZNK4llvm12function_refIFvvEEclEv + 25
14  oclint                              0x0000000105756d7d _ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE + 221
15  oclint                              0x00000001057570ef _ZL26RunSafelyOnThread_DispatchPv + 79
16  oclint                              0x000000010583d0d0 _ZL24ExecuteOnThread_DispatchPv + 48
17  libsystem_pthread.dylib             0x00007fff8f2b499d _pthread_body + 131
18  libsystem_pthread.dylib             0x00007fff8f2b491a _pthread_body + 0
19  libsystem_pthread.dylib             0x00007fff8f2b2351 thread_start + 13

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
