### ISSUE TITLE
oclint-json-compilation-database -- -o oclint.xml -rule customRule doesn't work

### ISSUE THREAD

**Issue by qiuhm** [oclint/oclint#365]
I wrote custom rules.
When I use oclint-json-compilation-database -- -o oclint.xml，it works and finds the bug.
But when I use -rule argument like oclint-json-compilation-database -- -o oclint.xml -rule customRule，it doesn't work and can't find the bug.
Is something wrong?
Thanks very much.

**Comment by UnrealQuester** [comment]
My first guess would be that the rule identifier (the nam you pass to `-rule`) is incorrect. The identifier is generated like so:

- Take the string returned by `name()`
- Capitalize every word
- Remove spaces

In the case of `customRule` the identifier would be `CustomRule`. Alternatively in the newest version of oclint you can specify the identifier directly using the `identifier()` method.

**Comment by qiuhm** [comment]
3ks very much.
I modified the rule name.It worked.
