### ISSUE TITLE
improper warning on "constant conditional operator"

### ISSUE THREAD

**Issue by simpleease** [oclint/oclint#366]
The following codes hit "constant conditional operator" rule:

`double playbaleProgress = 100.0
    if (isnan(playbaleProgress) || !isfinite(playbaleProgress))
{
}`

But, isnan and isfinite is macro from sdk. Could this situation avoid?  Or just add skip comment？

**Comment by UnrealQuester** [comment]
As those are macros they probably expand to an expression that can be evaluated at compile time if the value of playableProgress is known. In your case you could remove the conditional as the value is known at compile time or [suppress the warning](http://docs.oclint.org/en/stable/howto/suppress.html) with `//!OCLint`.

**Comment by ryuichis** [comment]
Another macro expansion issue. Thanks for bringing this up again for our attention. I am closing this one just to reduce duplications, but we are thinking a solution for this. Before that happens, please suppress the warning as @UnrealQuester suggested.
