### ISSUE TITLE
oclint can not support LLVM 8.0

### ISSUE THREAD

**Issue by zqxiaojin** [oclint/oclint#368]
Hi, 
    I found that the  XCode 8 beta6 with LLVM 8.0  has the following new grammar:

@property (class, nonatomic, copy) NSUUID *identifier;

  OClint can not support it. What can I do to oclint my project with iOS 10 sdk ?

**Comment by ryuichis** [comment]
The master branch now support LLVM 3.9, which means Xcode 8 GM is supported. We still need to do some testings though. Before we have an official release, you can try to build locally yourself or check out our snapshots from Travis CI. If it's still not working for you, please file another issue. Thanks.
