### ISSUE TITLE
objective-c high cyclomatic complexity false positives

### ISSUE THREAD

**Issue by masters3d** [oclint/oclint#373]
https://github.com/exercism/xobjective-c/blob/8bb5f57d7f07f2eaa850470188e94fcb0d7a1e1a//exercises/space-age/SpaceAgeTest.m#L24v

https://github.com/exercism/xobjective-c/blob/8bb5f57d7f07f2eaa850470188e94fcb0d7a1e1a/exercises/allergies/AllergiesTest.m#L19

https://github.com/exercism/xobjective-c/pull/121

⚠️  /exercises/space-age/SpaceAgeTest.m#L24 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L29 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L35 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L41 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L47 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L53 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L59 - high cyclomatic complexity
⚠️  /exercises/space-age/SpaceAgeTest.m#L65 - high cyclomatic complexity
📖    exercises/allergies/AllergiesTest.m#L19 - high cyclomatic complexity
📖    exercises/allergies/AllergiesTest.m#L26 - high cyclomatic complexity
📖    exercises/allergies/AllergiesTest.m#L33 - high cyclomatic complexity
📖    exercises/allergies/AllergiesTest.m#L40 - high cyclomatic complexity

**Comment by ryuichis** [comment]
Thanks for providing the real code that we can take a look, highly appreciate it.

I am pretty sure the root problem of what you see is the same as #378 and #280. Basically, `XCTAssertNotEqualWithAccuracy` and other XCTest _methods_ are actually macros. And they are expended during the compilation time. So OCLint here tries to work really hard and analyze on a really complex system implementation other than your own code. 😞 

All of these issues are all categorized into the macro expansion issue. So even though I am closing this one, your point is well taken.

**Comment by masters3d** [comment]
Thanks for the explanation! I forgot about macros. Makes sense.
