### ISSUE TITLE
Xcode8 master branch - malloc failures

### ISSUE THREAD

**Issue by daniel-beard** [oclint/oclint#377]
- Not sure why this is happening but I only started seeing this after upgrading to master branch (from 9 days ago)
- Building on a Mac Pro, El Capitan 10.11.6, Xcode 8

```
oclint(66739,0x7fff734cb000) malloc: *** mach_vm_map(size=18446744073621438464) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
```

**Comment by UnrealQuester** [comment]
std::bad_alloc is usually thrown when you run out of memory. In this case it looks like oclint is trying to allocate way too much memory.

Can you tell us how you are invoking oclint? Are you using it as a checker in xcode or manually from the command line?

**Comment by daniel-beard** [comment]
I'm invoking from the command line. The project itself has too many files to run in a single command, so I chunk the files and lint in groups of 500-1000 files.

I am running this on a Mac Pro with 64GB of RAM, watching as it runs, I'm never going above 15GB used in total (not just OCLint)

**Comment by UnrealQuester** [comment]
You said you were using the latest master. Does the problem also occur with the 0.11 or 0.10.3 release?

Could you also try to reduce the problem down to a single file or code snippet? I know this is asking for a lot but it would greatly help to track down the problem.

**Comment by daniel-beard** [comment]
Closing this. I figured out what the issue was. It was in some of my own code inside a rule that transforms an AST node to a string, wasn't taking into account macro locations so the char buffer would be wrong sometimes.

**Comment by daniel-beard** [comment]
@UnrealQuester thanks for the quick replies, and I'm glad this was my own code breaking :) and not a serious issue.

**Comment by HappyMary** [comment]
@daniel-beard 

> It was in some of my own code inside a rule that transforms an AST node to a string, wasn't taking into account macro locations so the char buffer would be wrong sometimes.
Can you tell me more information? I can not really understand. Thank you very much.

**Comment by yaoweili** [comment]
@daniel-beard  How do you locate the problem in which class

**Comment by daniel-beard** [comment]
@yaoweili I stepped through my code using lldb, was fairly obvious once it started crashing reproducibly with a single "bad" file.
