### ISSUE TITLE
Skipping <Path>. Compile command not found.

### ISSUE THREAD

**Issue by tanhuiya** [oclint/oclint#379]
I use xcodebuild | xcpretty -r json-compilation-database generate a compile_commands.json,
and when I use oclint-json-compilation-database command , it can get a output file.

But when I use oclint action in fastlane ,it turn out a problem .Skipping /xxx/xxx/. Compile command not found,and the compile_commands.json file can be analyzed by oclint-json-compilation-database command.

fastlane lint

the fastlane file 

lane :lint do
oclint(
       compile_commands: "compile_commands.json",    # The JSON compilation database, use xctool reporter "json-compilation-database"
       select_regex: /Controller.m,Pods/,     # Select all files matching this regex
       exclude_regex: /Test.m/,    # Exclude all files matching this regex
       report_type: "pmd",         # The type of the report (default: html)
       max_priority_1: 10,         # The max allowed number of priority 1 violations
       max_priority_2: 1000,        # The max allowed number of priority 2 violations
       max_priority_3: 2000,       # The max allowed number of priority 3 violations
       thresholds: [     # Override the default behavior of rules
         "LONG_LINE=200",
         "LONG_METHOD=200"
       ],
     )
end

$ cd /xxxxx/xxxxx/xxxxx && oclint -report-type=pmd -o=oclint_report.pmd -rc=LONG_LINE=200 -rc=LONG_METHOD=200 -max-priority-1=10 -max-priority-2=1000 -max-priority-3=2000 -p . ""
[21:53:24]: ▸ Skipping /xxxxx/xxxxx/xxxxx/. Compile command not found.

**Comment by UnrealQuester** [comment]
The `oclint` binary expects a list of source files. Fastlane appears to be passing an empty list to oclint. 

Try removing the include and exclude regex to see if oclint still gets no files.

I have no idea how fastlane actually works so you might want to open up an issue on the fastlane bugtracker instead.

**Comment by ChenTF** [comment]
Did you solve the problem? I also have a problem. https://github.com/oclint/oclint/issues/380 @tanhuiya @UnrealQuester

**Comment by nicolasiJasica** [comment]
i have the same problem. can u resolve?

**Comment by fusunlang** [comment]
请问问题解决了么？
