### ISSUE TITLE
no output when scanning a project with more than 700 files

### ISSUE THREAD

**Issue by xiahaoran** [oclint/oclint#381]
The Issue:  
              Using self-made rules with the command " oclint-json-compilation-database -- -R ~/ht_ios_coding_style_rules/rules/" , to scanning a project with 700 files, found no output, also no error message shown. 
              But , Using oclint original rules to scanning the same project , it had outputs, everything is fine.
              And, using the self-made rules to scanning another project with 200 files, it had output, everything is also OK.
             Can anybody help me figure out why ? Thanks in advance!

PS: 
      the oclint version used: 0.11
      the xcode version : xcode 8

**Comment by ryuichis** [comment]
I am closing this one, and others that do not provide enough information for us to reproduce the issues locally. If this issue still bothers, please share some code so that we have a starting place to dig into.
