### ISSUE TITLE
Support for rewriting source rules?

### ISSUE THREAD

**Issue by daniel-beard** [oclint/oclint#388]
### Issue Summary
Hi, first of all thanks for the fantastic linting tool. The maintainers hard work is much appreciated!

I'd like to use OCLint for rewriting source code (an example is re-ordering property attributes by type). While I could probably get away with writing a normal `ASTMatcher` or `ASTVisitor` rule that produces no warnings but rewrites the source, I was wondering if official support for this had been considered?

I'm ok if this is 'out of scope' for OCLint, but if not I wouldn't mind working on support and some examples for this!

**Comment by UnrealQuester** [comment]
This sounds like something oclint might do. Some of our warnings like `UselessParentheses` could be automatically resolved. Are you thinking about something like the FixItRewriter from clang?

As this is something that can likely be maintained without breaking existing functionality I would be happy to see some examples. What do you think @ryuichis?

**Comment by ryuichis** [comment]
I like the idea of fixing certain rule violations automatically. Would highly appreciate it if you can provide us a quick prototype for further discussions. Highly appreciate it.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
