### ISSUE TITLE
brew install oclint failed

### ISSUE THREAD

**Issue by loveace** [oclint/oclint#391]
I run the command like this:
   $ brew tap oclint/formulae
   $ brew install oclint

![image](https://cloud.githubusercontent.com/assets/7259540/21350180/f16167e6-c6f0-11e6-992d-cb4f288614e7.png)

**Comment by ryuichis** [comment]
According to the other issue #392 created by the same user, this issue has a large chance to be a temporary network issue, and has been resolved later on.
