### ISSUE TITLE
Extreme memory usage

### ISSUE THREAD

**Issue by oskargargas** [oclint/oclint#397]
### Issue Summary
I research usability of OCLint in project I work on. It's quite big. It's a beast in fact. Underneath there is C++ core shared with Android, with whole custom networking and security layer build on customized openSSL and curl (build from source as a project dependency). And on top of that there is some 113k lines of Objective-C code.

Anyway, I have compile_commands.json generated via xcpretty (little above 32MiB if that matters) and I run oclint-json-compilation-database with xcode target.

After few minutes according to Activity Monitor oclint used only 1 thread and over 13GiB of ram. kernel_task also ate about 3gigs more then usual. I canceled this run as my macbook was dying... 

I run it again with html report... and canceled it after hitting 8gigs to not loose these writeup.

Is it normal? Or I hit some nasty memory leak? I could live with oclint not being multithreaded (or maybe it can be?) but what amount of RAM would I need to lint such project?

### Environment
- Operation system name and version: macOS 10.11.6
- OCLint version: 0.11.1
- How OCLint is installed: binary downloaded from github

**Comment by ryuichis** [comment]
Based on the data points you provided, I think the memory consumption is _reasonable_. 

However, I am aware of the memory leaking at the underneath compiler level. For example: https://github.com/oclint/oclint/blob/master/oclint-driver/lib/Driver.cpp#L330

Pull requests are highly welcomed.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichis** [comment]
Merge to #413
