### ISSUE TITLE
Reports: present only p1 warnings and custom tools for visualization

### ISSUE THREAD

**Issue by SPopenko** [oclint/oclint#399]
Hi guys, 
I have two questions:

1.  Is it possible to generate report that have only **p1** warnings and omit all p2 and p3? 
2. Could you suggest any third party tools that could visualize report? Since standard HTML report is nice but don't have some useful options like filtration by warning type, priority etc.

**Comment by UnrealQuester** [comment]
There is currently no way I know of to completly disable a warning type short of disabling every single rule of that type via `-disable-rule`. In your case it might be easier to just enable the p1 rules with `-rule`.

Most ci/build systems have support for pmd reports if you want to go down that route. If you are not using a build system or just want to run oclint on your local machine, a json report together with some scripting might get you what you want.
