### ISSUE TITLE
Feature request: ignore macros

### ISSUE THREAD

**Issue by michaeleiselsc** [oclint/oclint#405]
### Issue Summary
In my code base, there are cases where using macros can lead to odd-looking code when fully unraveled. For example, we have an assert fail macro that, roughly speaking, gets translated from `NSAssertFail("msg")` to `NSAssert(false, "msg")`, which is a standard macro in iOS programming that we have no control over. So these sorts of things would be great to skip.

**Comment by UnrealQuester** [comment]
This seems to be a duplicate of #378
