### ISSUE TITLE
Feature request: Only report the diff between two oclint runs

### ISSUE THREAD

**Issue by michaeleiselsc** [oclint/oclint#407]
### Issue Summary
I work on a large code base that is just now integrating OCLint, and I only want to report oclint issues to people that have arisen specifically from the code they've added. It would be great to just run a diff tool and give them that result. I could try diffing myself manually, but of course the line numbers might change, etc.

**Comment by UnrealQuester** [comment]
I feel like this is something that should be handled by external tools instead of oclint itself.
We simply do not have any integration with version control systems that are required for this to work.

**Comment by ryuichis** [comment]
@michaeleiselsc this is a very good point, if you are interested in discuss further, could you send an email to ryuichi@ryuichisaito.com. and we take it from there?
