### ISSUE TITLE
Enhancement: reformat rules class to remove (possible) redundancies

### ISSUE THREAD

**Issue by vinyldarkscratch** [oclint/oclint#409]
When working on the short and long variable name rules, I was taking a closer look at it's structure.  I noticed something that seemed like a strange convention, and even though I haven't seen any particular reason while skimming through the code of why those conventions are used, there may be something beyond what meets the eye.

While looking at [LongVariableNameRule.cpp](https://github.com/oclint/oclint/blob/master/oclint-rules/rules/naming/LongVariableNameRule.cpp#L13), I noticed the use of `virtual const override` functions to supply simple variables such as the rule name, priority, category, etc.  I got somewhat confused, and thought "well, why not just make std::string, int, std::map, etc. variables?"  So, I suggest that something like the following for rules:

### [oclint-core/include/oclint/RuleBase.h](https://github.com/oclint/oclint/blob/master/oclint-core/include/oclint/RuleBase.h#L26)
```patch
    virtual ~RuleBase() {}
    virtual void apply() = 0;
-    virtual const std::string name() const = 0;
+    std::string name;
-    virtual const std::string attributeName() const;
+    std::string attributeName;
-    virtual const std::string identifier() const;
+    std::string identifier;
-    virtual const std::string category() const = 0;
+    std::string category;
-    virtual int priority() const = 0;
+    int priority;
```

### [oclint-rules/rules/naming/LongVariableNameRule.cpp](https://github.com/oclint/oclint/blob/master/oclint-rules/rules/naming/LongVariableNameRule.cpp#L13)

```patch
-    virtual const string name() const override
-    {
-        return "long variable name";
-    }
+    name = "long variable name";

-    virtual int priority() const override
-    {
-        return 3;
-    }
+    priority = 3;

-    virtual const string category() const override
-    {
-        return "naming";
-    }
+    category = "naming";
```

This is definitely an enhancement that will reduce backwards compatibility with users' custom rules, as well as cause any forks modifying the rules to need updating.  However, I would definitely prefer writing `priority=3;` than `virtual int priority() const override {return 3;}` if I were creating rules.  What would you guys think?

(Also, yes, I'm willing to tackle the conversion process!)

**Comment by UnrealQuester** [comment]
I personally prefer a pure virtual method because forgetting to override it results in an error instead of things silently not working/doing what you want at runtime.

**Comment by vinyldarkscratch** [comment]
Actually @UnrealQuester, you have a good point there.  I admittedly forgot about pure virtual functions and their benefits, thank you for the reminder!  Personally, I still feel like it's more vertical space than what is really needed (pure virtual variables, where art thou?), but at the same time I have my own conventions, and others might work for other projects.  :P

**Comment by ryuichis** [comment]
Closing this issue based on the same reason @UnrealQuester pointed out. Thanks @vinyldarkscratch for bringing this up.
