### ISSUE TITLE
How to show the clang analyzer results in the report？

### ISSUE THREAD

**Issue by adudurant** [oclint/oclint#416]
As the title， I  saw the clang analyzer results in the report，but the  number is 0. 
If the  clang analyzer results showed  as well as the  the oclint warnings，it would be helpful to build  continuous environment. 
Thanks！

**Comment by UnrealQuester** [comment]
What kind of report are you generating? Most report types already show the clang analyzer results with `-enable-clang-static-analyzer`.

**Comment by adudurant** [comment]
Thanks!  In fact, I had already found the way and written some custom rulers. But ,there still some limits,like the macro  ,the header ...cannot be analyzed , for it can be done in the clang .      So, I wonder if  the improvement can be done ?

**Comment by ryuichis** [comment]
@adudurant I think we avoid analyzing on header files, if you have that requirement, please check out `https://github.com/oclint/oclint/blob/master/oclint-rules/include/oclint/AbstractASTVisitorRule.h#L31`.

**Comment by adudurant** [comment]
@ryuichis Nice to get your reply. I have reviewed the source code,but could't find any information about analyzing the header, would you show something more detail ?

**Comment by adudurant** [comment]
@ryuichis   In addition, why not analyze on head files?

**Comment by adudurant** [comment]
@ryuichis   I have some ideas about  oclint.  Sometimes, when oclint  tells us the code may have errors,but we want to ignore the warnings.   In this case，what could we do?  Some other tools could add comments to ignore the code that show warning,like  Parasoft C++ Test.

**Comment by ryuichis** [comment]
@adudurant many of your questions can be found at our documentation, for example, http://docs.oclint.org/en/stable/howto/suppress.html

And if you comment out the line of the code that I pointed you to, then it will analyze the header files.

**Comment by ryuichis** [comment]
Since the conversation in this issue becomes out of the initial scope, I am closing in favor of separate discussions.

**Comment by adudurant** [comment]
@UnrealQuester  Thanks！ But when I use the command to analyze a project，I can‘t get the report. Do you get the  report?
