### ISSUE TITLE
Oclint   doesn‘t  exist  the  command line？

### ISSUE THREAD

**Issue by adudurant** [oclint/oclint#420]
I find that  when  Oclint  has analyzed the code and generated the report，but  it does't leave the command line。  Sometime，it takes a long time or I has to ctrl+z to force interrupt。

**Comment by adudurant** [comment]
Well，this condition bothers me a lot。Who could help？

**Comment by ryuichis** [comment]
@adudurant could you open a new issue by following our issue template and providing a sample project? It will enable us to replicate the same issue that you have on our end. I understand your concern, but with the description that you have in this thread, there is really nothing we can help.

**Comment by adudurant** [comment]
@ryuichis  It's a  big project.The  log  that  generate  by   command "xcodebuild ” can reach 60MB. However,I solve this problem by some other way. I wonder if there is something wrong with the I/O  stream.
