### ISSUE TITLE
OCLint generate html report error

### ISSUE THREAD

**Issue by yaoweili** [oclint/oclint#423]
The OCLint scrips has a report-type parameter, so i can create an html report with this command:

oclint-json-compilation-database -- -max-priority-1 10000 -max-priority-2 10000 -max-priority-3 10000 -rc LONG_LINE=150 -report-type pmd -o oclint.xml

but here error with this command:

1 error generated.
1 error generated.

oclint: error: cannot open report output file /Users/liyaowei/Desktop/ffstpcommon_V1.6.0/SecondHand/oclint.xml

**Comment by bart-kneepkens** [comment]
You won't be generating a HTML report with `-report-type pmd -o oclint.xml`. Use the `html` report type. 

Furthermore, it seems somewhat related to #422 and #302.

**Comment by ryuichis** [comment]
The original question has been answered by @bart-kneepkens (thanks for that), and the remaining issue will be discussed in #302 with the hope that additional information could be provided.
