### ISSUE TITLE
OCLint reporter failed

### ISSUE THREAD

**Issue by yaoweili** [oclint/oclint#424]
I use OCLint with this command:

sudo oclint-json-compilation-database -- -max-priority-1 10000 -max-priority-2 10000 -max-priority-3 10000 -rc LONG_LINE=3000 -report-type html -o oclint.html

and then,throw an error :

1 error generated.
2 errors generated.
3 errors generated.
1 error generated.
1 error generated.
6 errors generated.
7 errors generated.
1 error generated.
1 error generated.
2 errors generated.
1 error generated.
2 errors generated.
1 error generated.
7 errors generated.
15 errors generated.
oclint(99389,0x700002850000) malloc: *** mach_vm_map(size=7506766579137802240) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

**Comment by ryuichis** [comment]
@yaoweili I hope I can help you, but can you provide a sample project for me to replicate the same issue that you have? 

I am closing this one, and we can continue the conversation in #302.
