### ISSUE TITLE
oclint: error: cannot open report output file /Users/lxx/xx.xml

### ISSUE THREAD

**Issue by yaoweili** [oclint/oclint#425]
I Use Oclint commond to output an xml file but,system throw an error like this:

oclint: error: cannot open report output file /Users/liyaowei/Desktop/ffstpcommon_V1.6.0/SecondHand/oclint.xml
 
but,in the project path :/Users/liyaowei/Desktop/ffstpcommon_V1.6.0/SecondHand/oclint.xml,there
hava an oclint.xml,

[Uploading 86157E9B-5D7B-405E-A901-9D08EC42B8FE.png…]

Does anyone know about it?

**Comment by ryuichis** [comment]
I don't think we ship any oclint.xml file in our package, so it should be a file under your control. If it is your output destination, then is it a file that the `user` that runs oclint command doesn't have the permission to write to? And your screenshot wasn't uploaded successfully.

**Comment by ryuichis** [comment]
interesting, `ls -al /Users/liyaowei/Desktop/ffstpcommon_V1.6.1/SecondHand/oclint.html`, what you see?

**Comment by yaoweili** [comment]
noting,and I  use commond : ls  in my project finder  ,no file named colint.html  ,and  I use the commond  you gived me, systeme notice me "ls: /Users/liyaowei/Desktop/ffstpcommon_V1.6.1/SecondHand/oclint.html: No such file or directory",so I think ,the commond :
sudo oclint-json-compilation-database - -max-priority-1 10000 -max-priority-2 10000-max-priority-3 10000 -rc LONG_LINE = 150 - report-type html -o oclint.html

  is failed，but I dont konw the reasion  of the problem。

**Comment by ryuichis** [comment]
k, how is the permissions look for its containing folders?

For example, what you see for
`ls -al /Users/liyaowei/Desktop/ffstpcommon_V1.6.1/SecondHand`
and
`ls -al /Users/liyaowei/Desktop/ffstpcommon_V1.6.1`

**Comment by Frenzyfeng** [comment]
Why does this issue closed? 
I met the same issue and i didn't see any solution in the answer?
@ryuichis 

oclint: error: cannot open report output file /Users/ios/Documents/Work/iOSVivaVideo/XiaoYingApp/oclint.html

And sure i have the permissions for its containing folder: 
 ls -al  /Users/ios/Documents/Work/iOSVivaVideo/
drwxr-xr-x  26 ios  staff      832 12 20 15:09 XiaoYingApp

**Comment by AugustRush** [comment]
+1

**Comment by ZhiyongPan** [comment]
+1

**Comment by SamiYousef** [comment]
I met the same issue and i didn't see any solution in the answer?
@ryuichis

**Comment by KacyInGitHub** [comment]
I met the same issue and is there any solution?@ryuichis
