### ISSUE TITLE
oclint cannot report an

### ISSUE THREAD

**Issue by yaoweili** [oclint/oclint#428]
I  use commond like this to report a  xml in my project finder：
 
sudo oclint-json-compilation-database -- -max-priority-1 10000 -max-priority-2 10000 -max-priority-3 10000 -rc LONG_LINE=150 -report-type pmd -o oclint.xml

and there is an error like this：
oclint: error: cannot open report output file /Users/liyaowei/Desktop/1.60/ffstpcommon_V1.6.0/SecondHand/oclint.xml

**Comment by ryuichis** [comment]
What's the difference between this one and #425? Closing this one for now.
