### ISSUE TITLE
When oclint meet the chinese

### ISSUE THREAD

**Issue by adudurant** [oclint/oclint#429]
When  there are some Chinese symbols in the project path,the error as follows,

/oclint-release/bin/oclint-json-compilation-database", line 85, in <module>
    print(oclint_invocation)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 193-196: ordinal not in range(128) 

Anyone could help?

**Comment by ryuichis** [comment]
Sorry I can't. It's a Python error https://wiki.python.org/moin/UnicodeEncodeError, not an OCLint error. Please submit a fix to Python language.
