### ISSUE TITLE
oclint-json-compilation-database  work with -enable-clang-static-analyze ？

### ISSUE THREAD

**Issue by adudurant** [oclint/oclint#430]
Could oclint-json-compilation-database  work with -enable-clang-static-analyze ？ I know oclint work with  -enable-clang-static-analyze ，and get the report。But，oclint-json-compilation-database ？

**Comment by ryuichis** [comment]
Please refer to http://docs.oclint.org/en/stable/manual/oclint-json-compilation-database.html for passing the oclint arguments through `oclint-json-compilation-database`.

**Comment by adudurant** [comment]
@ryuichis  Sorry .But the result shows that oclint could run with --enable-clang-static-analyze not as well as the  oclint-json-compilation-database. A litter big project can't generate the report,and becomes ok without --enable-clang-static-analyze.   The same as https://github.com/oclint/oclint/issues/219. Is there any way?
