### ISSUE TITLE
Warnings on 3rd party functions

### ISSUE THREAD

**Issue by bart-kneepkens** [oclint/oclint#433]
I am using CocoaLumberjack for logging. With every `DDLog...` call, I get the warnings `ConstantIfExpression` and `BitwiseOperatorInConditional`, even though I have excluded the `Pods` folder using the `-e Pods` flag in `oclint-json-compilation-database`.

Is there any way to tackle these warnings? They are valid when you look at CocoaLumberjack code, but since my code simply calls that, it should be excluded right?

**Comment by ryuichis** [comment]
This is a duplicated issue due to the lack of capability of handling marco properly. We will fix that (if we can) and then this will be addressed along the way.
