### ISSUE TITLE
build too large size rules!!!(tried ubuntu and fedora)

### ISSUE THREAD

**Issue by BigNewbiePlus** [oclint/oclint#442]
### Issue Summary
I build the oclint according to the Development,  I build rules and use **oclint sample.cpp -- -c** to test. All my test is ok and the only difference is that when i **./build rules**, every my build rule size>15M and not as the oclint pre-built binary version with size >300k, anyone met the same issue?

### Environment
- Ubuntu16.0 and Fedora-Workstation-Live-x86_64-25-1.3:
- OCLint version: 0.12
- How OCLint is installed: according to the Development(http://docs.oclint.org/en/stable/#development)

### Reproduction Steps
./build rules 
./bundle
./oclint sample.cpp -- -c

du -al

Command to run OCLint with the code above.

### Expected Behavior
356K    ./libTooManyParametersRule.so
356K    ./libRedundantConditionalOperatorRule.so
356K    ./libDefaultLabelNotLastInSwitchStatementRule.so
356K    ./libCoveredSwitchStatementsDontNeedDefaultRule.so
352K    ./libDoubleNegativeRule.so
696K    ./libAvoidPrivateStaticMembersRule.so
500K    ./libTooFewBranchesInSwitchStatementRule.so
352K    ./libEmptyElseBlockRule.so
360K    ./libUnnecessaryNullCheckForCXXDeallocRule.so
352K    ./libJumbledIncrementerRule.so
640K    ./libObjCAssignIvarOutsideAccessorsRule.so
352K    ./libObjCVerifyIsEqualHashRule.so
360K    ./libObjCObjectSubscriptingRule.so
356K    ./libPreferEarlyExitRule.so
656K    ./libBrokenNullCheckRule.so
368K    ./libNcssMethodCountRule.so
360K    ./libBaseClassDestructorShouldBeVirtualOrProtectedRule.so
352K    ./libConstantIfExpressionRule.so
364K    ./libNestedBlockDepthRule.so
352K    ./libEmptySwitchStatementRule.so
352K    ./libEmptyIfStatementRule.so
352K    ./libEmptyDoWhileStatementRule.so
360K    ./libObjCBoxedExpressionsRule.so
496K    ./libMissingBreakInSwitchStatementRule.so
692K    ./libGotoStatementRule.so
356K    ./libSwitchStatementsShouldHaveDefaultRule.so
696K    ./libAvoidDefaultArgumentsOnVirtualMethodsRule.so
356K    ./libObjCVerifyProhibitedCallRule.so
496K    ./libObjCVerifyMustCallSuperRule.so
364K    ./libUnusedLocalVariableRule.so
420K    ./libObjCVerifyProtectedMethodRule.so
352K    ./libEmptyCatchStatementRule.so
360K    ./libObjCContainerLiteralsRule.so
356K    ./libDestructorOfVirtualClassRule.so
352K    ./libDeadCodeRule.so
352K    ./libCollapsibleIfStatementsRule.so
720K    ./libBitwiseOperatorInConditionalRule.so
652K    ./libThrowExceptionFromFinallyBlockRule.so
352K    ./libUselessParenthesesRule.so
352K    ./libEmptyFinallyStatementRule.so
364K    ./libUnusedMethodParameterRule.so
352K    ./libInvertedLogicRule.so
352K    ./libForLoopShouldBeWhileLoopRule.so
384K    ./libNPathComplexityRule.so
352K    ./libMultipleUnaryOperatorRule.so
500K    ./libNonCaseLabelInSwitchStatementRule.so
356K    ./libTooManyMethodsRule.so
360K    ./libLongClassRule.so
356K    ./libAvoidBranchingStatementAsLastInLoopRule.so
356K    ./libConstantConditionalOperatorRule.so
508K    ./libParameterReassignmentRule.so
352K    ./libEmptyWhileStatementRule.so
656K    ./libMisplacedNullCheckRule.so
356K    ./libUnnecessaryElseStatementRule.so
352K    ./libEmptyForStatementRule.so
352K    ./libRedundantLocalVariableRule.so
356K    ./libLongVariableNameRule.so
356K    ./libTooManyFieldsRule.so
356K    ./libRedundantIfStatementRule.so
360K    ./libObjCNSNumberLiteralsRule.so
504K    ./libCyclomaticComplexityRule.so
360K    ./libShortVariableNameRule.so
216K    ./libLongLineRule.so
356K    ./libObjCVerifySubclassMustImplementRule.so
380K    ./libLongMethodRule.so
508K    ./libRedundantNilCheckRule.so
500K    ./libReturnFromFinallyBlockRule.so
356K    ./libBrokenOddnessCheckRule.so
352K    ./libEmptyTryStatementRule.so
28M     .

### Actual Behavior
15M     ./libTooManyParametersRule.so
16M     ./libRedundantConditionalOperatorRule.so
16M     ./libDefaultLabelNotLastInSwitchStatementRule.so
16M     ./libCoveredSwitchStatementsDontNeedDefaultRule.so
15M     ./libDoubleNegativeRule.so
33M     ./libAvoidPrivateStaticMembersRule.so
17M     ./libTooFewBranchesInSwitchStatementRule.so
15M     ./libEmptyElseBlockRule.so
16M     ./libUnnecessaryNullCheckForCXXDeallocRule.so
16M     ./libJumbledIncrementerRule.so
19M     ./libObjCAssignIvarOutsideAccessorsRule.so
15M     ./libObjCVerifyIsEqualHashRule.so
16M     ./libObjCObjectSubscriptingRule.so
16M     ./libPreferEarlyExitRule.so
19M     ./libBrokenNullCheckRule.so
16M     ./libNcssMethodCountRule.so
16M     ./libBaseClassDestructorShouldBeVirtualOrProtectedRule.so
15M     ./libConstantIfExpressionRule.so
16M     ./libNestedBlockDepthRule.so
15M     ./libEmptySwitchStatementRule.so
15M     ./libEmptyIfStatementRule.so
16M     ./libEmptyDoWhileStatementRule.so
16M     ./libObjCBoxedExpressionsRule.so
17M     ./libMissingBreakInSwitchStatementRule.so
33M     ./libGotoStatementRule.so
16M     ./libSwitchStatementsShouldHaveDefaultRule.so
33M     ./libAvoidDefaultArgumentsOnVirtualMethodsRule.so
16M     ./libObjCVerifyProhibitedCallRule.so
17M     ./libObjCVerifyMustCallSuperRule.so
16M     ./libUnusedLocalVariableRule.so
17M     ./libObjCVerifyProtectedMethodRule.so
15M     ./libEmptyCatchStatementRule.so
16M     ./libObjCContainerLiteralsRule.so
16M     ./libDestructorOfVirtualClassRule.so
16M     ./libDeadCodeRule.so
16M     ./libCollapsibleIfStatementsRule.so
33M     ./libBitwiseOperatorInConditionalRule.so
19M     ./libThrowExceptionFromFinallyBlockRule.so
15M     ./libUselessParenthesesRule.so
16M     ./libEmptyFinallyStatementRule.so
16M     ./libUnusedMethodParameterRule.so
15M     ./libInvertedLogicRule.so
16M     ./libForLoopShouldBeWhileLoopRule.so
16M     ./libNPathComplexityRule.so
16M     ./libMultipleUnaryOperatorRule.so
17M     ./libNonCaseLabelInSwitchStatementRule.so
15M     ./libTooManyMethodsRule.so
16M     ./libLongClassRule.so
16M     ./libAvoidBranchingStatementAsLastInLoopRule.so
16M     ./libConstantConditionalOperatorRule.so
17M     ./libParameterReassignmentRule.so
15M     ./libEmptyWhileStatementRule.so
19M     ./libMisplacedNullCheckRule.so
16M     ./libUnnecessaryElseStatementRule.so
15M     ./libEmptyForStatementRule.so
16M     ./libRedundantLocalVariableRule.so
15M     ./libLongVariableNameRule.so
15M     ./libTooManyFieldsRule.so
16M     ./libRedundantIfStatementRule.so
16M     ./libObjCNSNumberLiteralsRule.so
19M     ./libCyclomaticComplexityRule.so
16M     ./libShortVariableNameRule.so
12M     ./libLongLineRule.so
16M     ./libObjCVerifySubclassMustImplementRule.so
16M     ./libLongMethodRule.so
17M     ./libRedundantNilCheckRule.so
17M     ./libReturnFromFinallyBlockRule.so
15M     ./libBrokenOddnessCheckRule.so
15M     ./libEmptyTryStatementRule.so
1.2G

### Even Better
everything is ok, only the rule size is too big!!!

**Comment by self-creative** [comment]
I think oclint is extinct and unsupported by contributers...because i hava a big probrlem,but nobody can help me:   my issue is : https://github.com/oclint/oclint/issues/441

**Comment by BigNewbiePlus** [comment]
absolutely right!!! but we can help each other!!!

**Comment by ryuichis** [comment]
I think you are building oclint in debug mode, which results in large file sizes. Building it with release mode will help.

@self-creative I suggest you read http://contributor-covenant.org/version/1/4/ before making such comments. Open source community is designed to help each other as @BigNewbiePlus pointed out. Please be advised that all open source contributors have their work and life as well as you do, so a mutual respect is very fundamental to achieve a health community. With this said, I am going to delete your comments.

**Comment by BigNewbiePlus** [comment]
Very appreciate for @ryuichis awesome answer，I will try it!!!

**Comment by self-creative** [comment]
@ryuichis ,I will read http://contributor-covenant.org/version/1/4/. Thanks so much, and oclint is a  nice project
