### ISSUE TITLE
oclint-json-compilation-database not running (0.12)  iOS project

### ISSUE THREAD

**Issue by vicwan** [oclint/oclint#444]
### Issue Summary
cd into my iOS project directory and I ran the script (see Sample Code below) using Bash. And as #312 described, everything was fine until running the *oclint-json-compilation-database* command. OCLint just stopped there and last for around 30 mins without any output. So, I interrupted the process manually using *ctrl + c* and got the information:
```
^CTraceback (most recent call last):
  File "/usr/local/bin/oclint-json-compilation-database", line 87, in <module>
    exit_code = subprocess.call(oclint_invocation, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
-----分析失败-----
```
The project was successfully built and the *compile_commands.json* file (8.7 M) was generated as expected. 

However, one thing is very important. I succeeded in generating an HTML report at the very first time after I had installed OCLint and the data in the report was as expected. But after a few hours, I could not succeed in running the same script again. I don't know if I have changed something by accident 
 
Since @UnrealQuester asked about CPU and memory usage as well as the number of source files contained in the project in issue #312, I can provide as follows:
- CPU usage: 65%-70% idle while running *oclint-json-compilation-database* command, around 95% idle after interrupted.
- Memory usage: 22% using while running that command, around 22% using after interrupted.
- The number of source files: after running *find . "(" -name "*.m" -or -name "*.mm" -or -name "*.cpp" -or -name "*.h" ")" -print | wc -l*, I got 2270.

### Environment
- OS X 10.12 Sierra, Xcode 8.3.2
- OCLint version: 0.12
- How OCLint is installed: Homebrew install

### Reproduction Steps
Detailed steps to reproduce the issue.

#### Sample code

```
#!/bin/bash

myproj=XXX.xcodeproj
myscheme=XXX # 替换scheme的名字
xcodebuild -project $myproj -scheme $myscheme clean&&
xcodebuild -project $myproj -scheme $myscheme \
-configuration Debug \
| tee xcodebuild.log \
| xcpretty -r json-compilation-database -o compile_commands.json&&
oclint-json-compilation-database -e Pods -- \
-report-type html -o oclint_result.html \
-rc LONG_LINE=200 \
-max-priority-1=100000 \
-max-priority-2=100000 \
-max-priority-3=100000; \
rm compile_commands.json;
if [ -f ./oclint_result.html ]; then echo '-----分析完毕-----'
else echo "-----分析失败-----"; fi
```

Command to run OCLint with the code above.

### Even Better
I am so sorry that I cannot provide the source code of the project. :(

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichis** [comment]
I do appreciate your detailed description, and I am happy to hear it runs successfully for the first time. Now we need to figure out what has been changed between the first run and sequential ones. 

1. Any new dependency libraries have been added? If they are third-party open source cocoapods, what are they? Any internal private pods?
2. How about force clean the DerivedData folder? I am currently wondering if some intermediate files are preserved by Xcode, which results in ill-generated `compile_commands.json` file in the sequential runs.

**Comment by vicwan** [comment]
Sorry for being so late cuz I was developing new features and the Jenkins task has been suspended.

The command worked well by cleaning up the DerivedData folder before I ran the shell script. So, the xcodebuild clean is not powerful enough in this case. Thanks for your answer and the nice tool! :) @ryuichis

**Comment by colourful987** [comment]
I used python script wrote by @wuwen1030 , because the size of compile_commands.json file is too large that could produce "OSError: [Errno 7] Argument list too long"。However the `oclint-json-compilation-database` python script always waiting for the exit code of ` subprocess.call(oclint_arguments)` command。 I followed @ryuichi-assistant suggestions，deleted DerivedData File and `xcodebuild clean` ，it still doesn't work。

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
