### ISSUE TITLE
sonarqube+OClint 统计显示问题

### ISSUE THREAD

**Issue by liuluchang** [oclint/oclint#452]
当我通过执行oclint-json-compilation-database -e Pods -v -- -report-type pmd -o report.xml -max-priority-1=19999 -max-priority-2=19999 -max-priority-3=19999  -rc=LONG_LINE=500 -rc=NCSS_METHOD=1000，生成xml后缀的文件后并将结果传送到sonarqube后，我发现sonarqube的界面只会显示坏味道的统计，而不会显示bugs的数量，我试了三个工程都是一样的结论，请问这样的结果合适吗？不合适的话有木有解决的办法
![69ca9350-c21e-4638-9292-289861223154](https://user-images.githubusercontent.com/8243170/28903189-145bb6ba-7836-11e7-858a-da6a73f7fbcd.png)

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
