### ISSUE TITLE
Execute oclint for source directory

### ISSUE THREAD

**Issue by vlnj** [oclint/oclint#460]
### Issue Summary
I'm running oclint using command line parsing each files as arguments, is there a way to run oclint for a particular source folder instead of parsing every source file.

### Environment
- Operation system name and version: Mac
- OCLint version: 0.12
- How OCLint is installed: prebuilt binary downloaded from github

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by vlnj** [comment]
done

**Comment by vlnj** [comment]
Hi any update on this?

**Comment by UnrealQuester** [comment]
You could use [oclint-json-compilation-database](http://docs.oclint.org/en/stable/manual/oclint-json-compilation-database.htmll) with a compile_commands.json produced by your build system and then use `-include` to only select the the folder you want.

**Comment by vlnj** [comment]
Thank you .
