### ISSUE TITLE
so many problems i have met, but i don't wanna give up!

### ISSUE THREAD

**Issue by xiaoyier** [oclint/oclint#464]
### Issue Summary
1 could not build module 'UIKit' 
2 generate errors
3 report empty
4 multi jobs problem
5 olin-json-compilation-database command not found

### Environment
- Xcode9  macOS10.12.6
- OCLint version:
- 0.12 local build 

### Reproduction Steps
i just doubt that can i use oclint successfully? there are so many problems, and i have spend almost one week on it, but how can i fix so many problems?

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichis** [comment]
I really hope I can help, but based on the information you provided, there is nothing I can do about it. If you can help provide detailed steps of how to reproduce your issue, then maybe we could have more serious conversations.
