### ISSUE TITLE
Compile OCLINT 0.13 on Solaris

### ISSUE THREAD

**Issue by stevereaver** [oclint/oclint#466]
### Issue Summary
I am a sysadmin and am attempting to compile OCLINT 0.13 on Solaris 11.3 for our developers, however it keeps failing at 18% 

My tool chain is such that I am able to compile the latest versions of llvm and clang. However OCLINT fails. How do I find out what has broken here ?

### Environment
- Operation system name and version: SunOS itgcore0 5.11 11.3 sun4v sparc SUNW,Sun-Fire-T200 Solaris
- OCLint version: 0.13
- How OCLint is installed: compiling from source

### Reproduction Steps
Simply compile using the ./make script in oclint-scipts directory.

#### Sample code
The end of the output from the compile.

```
[ 18%] Copying clang's cuda_wrappers/algorithm...
[ 18%] Copying clang's cuda_wrappers/complex...
[ 18%] Copying clang's cuda_wrappers/new...
[ 18%] Building arm_neon.h...
make[2]: *** [tools/clang/lib/Headers/arm_neon.h.tmp] Segmentation Fault (core dumped)
make[1]: *** [tools/clang/lib/Headers/CMakeFiles/clang-headers.dir/all] Error 2
[ 18%] Linking CXX executable ../../bin/not
[ 18%] Built target not
[ 18%] Linking CXX executable ../../bin/llvm-mcmarkup
[ 18%] Linking CXX executable ../../bin/llvm-cxxfilt
[ 18%] Built target llvm-mcmarkup
[ 18%] Built target llvm-cxxfilt
[ 18%] Linking CXX executable ../../bin/yaml-bench
[ 18%] Built target yaml-bench
[ 18%] Linking CXX static library ../../libLLVMTestingSupport.a
[ 18%] Built target LLVMTestingSupport
[ 18%] Linking CXX executable ../../bin/llvm-config
[ 18%] Built target llvm-config
[ 18%] Linking CXX executable ../../bin/FileCheck
[ 18%] Built target FileCheck
make: *** [all] Error 2`
```

### Expected Behavior
as above

### Actual Behavior
as above

### Even Better
none

**Comment by ryuichis** [comment]
OCLint depends on LLVM/Clang, and your error happens at the compilation phase of LLVM. Do you know if LLVM works on Solaris? http://clang.llvm.org/ may help on that front.

I am humbly thrilled to see people try to use OCLint on Solaris, so I'll let this issue open for a while. Let us know if you get LLVM/Clang to work on Solaris, and I will try to help the next steps.

**Comment by stevereaver** [comment]
I think I am getting close now. When I compile clang using  ./clang build -j 1  The build and install completed. I had to explicitly set the jobs to 1 because the linking was using so much memory it was getting mmap error.  So my assumption is that the above error is also due to memory, how do I set the job count when using the ./make script to build ?  can I just change the ci script as follows ?

` if args.release:
        process.call('python clang build -release -clean - j 1')`

**Comment by ryuichis** [comment]
I would suggest creating your own `makeOnSolaris` file, and have something like this:

```
./ci -reset
./clang build -release -clean -j 1
./build -release -clean -j 1
./bundle
./bundle -archive -release
```

Can you help verify if this script works for you? If it does, maybe you can create a pull request with this.

**Comment by stevereaver** [comment]
Firstly, let me thank you for the above. I was able to use it however I have had to make a few changes;

`./ci -reset
./ci -setup
./clang build -j 1
./build -j 1
./bundle
./bundle -archive -release`

I was not able to use the -release option for ./clang as it seems that it does not honour the -j option if -release is set. That causes a problem on this system as it has 16 cores and when the linking occurs the memory gets full as there are 16 threads trying to link each needing several GB each, this system only has 16GB.

Then the next issue was that I did not have Ninja available for ./build, that was easy to compile and fix.

Now the current issue is that when I run ./build it fails, and I'm not sure why.

`-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LLVM_ROOT: /bancroft-src/oclint/oclint-0.13/build/llvm-install
-- Found LLVM LLVM_PACKAGE_VERSION: 5.0.0svn-r316539 - LLVM_VERSION_RELEASE: 5.0.0
-- Using LLVMConfig.cmake in: /bancroft-src/oclint/oclint-0.13/build/llvm-install/lib/cmake/llvm
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CRYPTO_STATIC_LIB
    linked by target "oclint-0.13" in directory /bancroft-src/oclint/oclint-0.13/oclint-driver
SSL_STATIC_LIB
    linked by target "oclint-0.13" in directory /bancroft-src/oclint/oclint-0.13/oclint-driver

-- Configuring incomplete, errors occurred!
See also "/bancroft-src/oclint/oclint-0.13/build/oclint-driver/CMakeFiles/CMakeOutput.log".`

The log file mentioned there does not have anything in it regarding any error, so I am a little puzzled.

**Comment by UnrealQuester** [comment]
Looks like you are missing a few libs. Maybe this is the same error as #470?
Maybe you could try building with `-no-analytics`.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichis** [comment]
For my personal curiosity, I was wondering how this effort goes, @stevereaver?

**Comment by stevereaver** [comment]
I'm on summer holidays, so no work happening at the moment. Also been very busy at work and the machine I was working on was very slow. We will be upgrading it in the new year so things will move a little quicker. I can give a better uodated after the 8th Jan.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by stevereaver** [comment]
Finally we have a new 64 thread system with 128Gb ram and I have been able to succesfull compile OCLINT on Solaris 11.3

`bancroft@itgcore0:/src/oclint/oclint-0.13.1/build/oclint-0.13.1/bin$ uname -a 
SunOS itgcore0 5.11 11.3 sun4v sparc sun4v Solaris
bancroft@itgcore0:/src/oclint/oclint-0.13.1/build/oclint-0.13.1/bin$ ./oclint-0.13.1 -version
LLVM (http://llvm.org/):
  LLVM version 5.0.1
  DEBUG build with assertions.
  Default target: sparc-sun-solaris2.11
  Host CPU: (unknown)
OCLint (http://oclint.org/):
  OCLint version 0.13.1.
  Built Apr 20 2018 (14:36:40).`


To achieve this I had to install all of the necessary libraries as supplied with Solaris, and compile more recent versions of cmake and make, chaining my path the pick up the new tools. Finally I used this script to build. 

`#! /bin/sh -e
./ci -reset
./ci -setup
./clang build
./googleTest build
./build -release -no-analytics
./bundle
./bundle -archive -release`

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
