### ISSUE TITLE
want to know how to debug the oclint source code!!

### ISSUE THREAD

**Issue by garnetwzy** [oclint/oclint#472]
### Issue Summary
I have the need to change the oclint source code to meet my need, but I don't know use what IDE to excuate the souce code of oclint. So the only way to debug my version of oclint code is to compile the source code and test on the  program, feeling very stupid..
I am new to oclint, and I want to know use what IDE to debug the oclint source code, thank you!
### Environment
- Operation system name and version:
MacOS Sierra 10.12.6
- OCLint version:
0.13
- How OCLint is installed: local build
### Reproduction Steps
Detailed steps to reproduce the issue.
#### Sample code

Command to run OCLint with the code above.

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

### Actual Behavior
What currently happens as a result of the reproduction steps?

### Even Better
Is your project open sourced? If yes, can you point us to your repository?
If not, is it possible to make a small project that fails the Travis CI?
If not, can you create a gist with your sample code for us?

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by garnetwzy** [comment]
need answer! Thank you.

**Comment by UnrealQuester** [comment]
I just run oclint under `gdb` to debug. Which is probably how most IDEs do it, just with a nicer interface.

**Comment by garnetwzy** [comment]
@UnrealQuester I see. But I have another question: when I change the oclint source code a little bit, I don't know if my code can run right, so I need to use the ./make to compile the source code and see the result. It usually takes me a lot of time, and if my code has something wrong, then I need to correct my code and do the ./make again, waste a lot of time and feeling very stupid. Do you have a clever way to do this?

**Comment by UnrealQuester** [comment]
If you did a full build once using `./make`, you can do incremental builds by first doiing `./build` followed by `./bundle`.

**Comment by garnetwzy** [comment]
@UnrealQuester I see. Thanks a lot~
