### ISSUE TITLE
out of bounds 

### ISSUE THREAD

**Issue by maddin200** [oclint/oclint#473]
oclint-reporters\reporters\XMLReporter.cpp  line 52 

char charNow[20];
        sprintf(charNow,
            "%04i-%02i-%02iT%02i:%02i:%02iZ",  (**** = 20 ****)
            tmNow->tm_year + 1900,
            tmNow->tm_mon,
            tmNow->tm_mday,
            tmNow->tm_hour,
            tmNow->tm_min,
            tmNow->tm_sec);

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by UnrealQuester** [comment]
Yup, looks like the output is exactly 20 characters long, meaning we would write a null byte outside of the array.
