### ISSUE TITLE
[oclint-docs] Community link is 404

### ISSUE THREAD

**Issue by NicolasCARPi** [oclint/oclint#476]
### Issue Summary
The "getting involved" link found at the bottom of https://github.com/oclint/oclint-docs/blob/master/intro/overview.rst is not working.

### Reproduction Steps
* Go to http://docs.oclint.org/en/stable/intro/overview.html#get-involved
* Click [getting involved](http://oclint.org/community.html) link
* "Houston, we have a problem!"

### Expected Behavior
See how to get involved :p 

### Actual Behavior
The requested URL was not found.

Cheers,
~Nico

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by NicolasCARPi** [comment]
@ryuichi-assistant That's because I removed the irrelevant parts, being a documentation issue.

**Comment by ryuichis** [comment]
Good catch. Just fix it on the oclint-docs repo.
