### ISSUE TITLE
/usr/bin/ld: 找不到 -lOCLintMetric

### ISSUE THREAD

**Issue by BigNewbiePlus** [oclint/oclint#482]
**When I run `./test rules`  I meet these bugs, I donnt know how to fix it, Any Advise?**
LLVM_ROOT: /home/fdh/oclint/build/llvm-install
-- Found LLVM LLVM_PACKAGE_VERSION: 5.0.0svn-r319156 - LLVM_VERSION_RELEASE: 5.0.0
-- Using LLVMConfig.cmake in: /home/fdh/oclint/build/llvm-install/lib/cmake/llvm
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fdh/oclint/build/oclint-rules-test
[1/79] Linking CXX executable bin/CanaryTest
FAILED: bin/CanaryTest 
: && /usr/bin/c++  -O0 -g -std=c++11 -stdlib=libstdc++  -fno-rtti -Wno-c++11-extensions -fPIC -fcolor-diagnostics  -rdynamic test/CMakeFiles/CanaryTest.dir/CanaryTest.cpp.o  -o bin/CanaryTest -L/home/fdh/oclint/build/googletest  -L/home/fdh/oclint/build/llvm-install/lib/clang/5.0.0/lib/linux  -L/home/fdh/oclint/build/oclint-core-test/lib  -L/home/fdh/oclint/build/oclint-metrics-test/lib -Wl,-rpath,/home/fdh/oclint/build/googletest:/home/fdh/oclint/build/llvm-install/lib/clang/5.0.0/lib/linux:/home/fdh/oclint/build/oclint-core-test/lib:/home/fdh/oclint/build/oclint-metrics-test/lib test/libtest_helper.a lib/libOCLintAbstractRule.a -lOCLintMetric lib/helper/libOCLintHelper.a lib/util/libOCLintUtil.a -lOCLintCore -lOCLintRuleSet -lgmock -lgmock_main -lclang_rt.profile-x86_64 --coverage -lclangTooling -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic /home/fdh/oclint/build/llvm-install/lib/libLLVMAsmParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBitReader.a /home/fdh/oclint/build/llvm-install/lib/libLLVMInstrumentation.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMCParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMOption.a /home/fdh/oclint/build/llvm-install/lib/libLLVMSupport.a /home/fdh/oclint/build/llvm-install/lib/libLLVMTransformUtils.a /home/fdh/oclint/build/llvm-install/lib/libLLVMAnalysis.a /home/fdh/oclint/build/llvm-install/lib/libLLVMProfileData.a /home/fdh/oclint/build/llvm-install/lib/libLLVMObject.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBitReader.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMCParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMCore.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBinaryFormat.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMC.a /home/fdh/oclint/build/llvm-install/lib/libLLVMSupport.a -lrt -ldl -lpthread -lz -lm /home/fdh/oclint/build/llvm-install/lib/libLLVMDemangle.a && :
/usr/bin/ld: 找不到 -lOCLintMetric
/usr/bin/ld: 找不到 -lOCLintCore
/usr/bin/ld: 找不到 -lOCLintRuleSet
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
[2/79] Linking CXX executable bin/HelperTests
FAILED: bin/HelperTests 
: && /usr/bin/c++  -O0 -g -std=c++11 -stdlib=libstdc++  -fno-rtti -Wno-c++11-extensions -fPIC -fcolor-diagnostics  -rdynamic test/helper/CMakeFiles/HelperTests.dir/AttributeHelperTest.cpp.o test/helper/CMakeFiles/HelperTests.dir/SuppressHelperTest.cpp.o  -o bin/HelperTests -L/home/fdh/oclint/build/googletest  -L/home/fdh/oclint/build/llvm-install/lib/clang/5.0.0/lib/linux  -L/home/fdh/oclint/build/oclint-core-test/lib  -L/home/fdh/oclint/build/oclint-metrics-test/lib -Wl,-rpath,/home/fdh/oclint/build/googletest:/home/fdh/oclint/build/llvm-install/lib/clang/5.0.0/lib/linux:/home/fdh/oclint/build/oclint-core-test/lib:/home/fdh/oclint/build/oclint-metrics-test/lib test/libtest_helper.a lib/libOCLintAbstractRule.a -lOCLintMetric lib/helper/libOCLintHelper.a lib/util/libOCLintUtil.a -lOCLintCore -lOCLintRuleSet -lgmock -lgmock_main -lclang_rt.profile-x86_64 --coverage -lclangTooling -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic /home/fdh/oclint/build/llvm-install/lib/libLLVMAsmParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBitReader.a /home/fdh/oclint/build/llvm-install/lib/libLLVMInstrumentation.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMCParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMOption.a /home/fdh/oclint/build/llvm-install/lib/libLLVMSupport.a /home/fdh/oclint/build/llvm-install/lib/libLLVMTransformUtils.a /home/fdh/oclint/build/llvm-install/lib/libLLVMAnalysis.a /home/fdh/oclint/build/llvm-install/lib/libLLVMProfileData.a /home/fdh/oclint/build/llvm-install/lib/libLLVMObject.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBitReader.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMCParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMCore.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBinaryFormat.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMC.a /home/fdh/oclint/build/llvm-install/lib/libLLVMSupport.a -lrt -ldl -lpthread -lz -lm /home/fdh/oclint/build/llvm-install/lib/libLLVMDemangle.a && :
/usr/bin/ld: 找不到 -lOCLintMetric
/usr/bin/ld: 找不到 -lOCLintCore
/usr/bin/ld: 找不到 -lOCLintRuleSet
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
[3/79] Linking CXX executable bin/AbstractTests
FAILED: bin/AbstractTests 
: && /usr/bin/c++  -O0 -g -std=c++11 -stdlib=libstdc++  -fno-rtti -Wno-c++11-extensions -fPIC -fcolor-diagnostics  -rdynamic test/abstract/CMakeFiles/AbstractTests.dir/LanguageSelectionTest.cpp.o test/abstract/CMakeFiles/AbstractTests.dir/MacroLocationTest.cpp.o test/abstract/CMakeFiles/AbstractTests.dir/TagBasedViolationTest.cpp.o  -o bin/AbstractTests -L/home/fdh/oclint/build/googletest  -L/home/fdh/oclint/build/llvm-install/lib/clang/5.0.0/lib/linux  -L/home/fdh/oclint/build/oclint-core-test/lib  -L/home/fdh/oclint/build/oclint-metrics-test/lib -Wl,-rpath,/home/fdh/oclint/build/googletest:/home/fdh/oclint/build/llvm-install/lib/clang/5.0.0/lib/linux:/home/fdh/oclint/build/oclint-core-test/lib:/home/fdh/oclint/build/oclint-metrics-test/lib test/libtest_helper.a lib/libOCLintAbstractRule.a -lOCLintMetric lib/helper/libOCLintHelper.a lib/util/libOCLintUtil.a -lOCLintCore -lOCLintRuleSet -lgmock -lgmock_main -lclang_rt.profile-x86_64 --coverage -lclangTooling -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic /home/fdh/oclint/build/llvm-install/lib/libLLVMAsmParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBitReader.a /home/fdh/oclint/build/llvm-install/lib/libLLVMInstrumentation.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMCParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMOption.a /home/fdh/oclint/build/llvm-install/lib/libLLVMSupport.a /home/fdh/oclint/build/llvm-install/lib/libLLVMTransformUtils.a /home/fdh/oclint/build/llvm-install/lib/libLLVMAnalysis.a /home/fdh/oclint/build/llvm-install/lib/libLLVMProfileData.a /home/fdh/oclint/build/llvm-install/lib/libLLVMObject.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBitReader.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMCParser.a /home/fdh/oclint/build/llvm-install/lib/libLLVMCore.a /home/fdh/oclint/build/llvm-install/lib/libLLVMBinaryFormat.a /home/fdh/oclint/build/llvm-install/lib/libLLVMMC.a /home/fdh/oclint/build/llvm-install/lib/libLLVMSupport.a -lrt -ldl -lpthread -lz -lm /home/fdh/oclint/build/llvm-install/lib/libLLVMDemangle.a && :
/usr/bin/ld: 找不到 -lOCLintMetric
/usr/bin/ld: 找不到 -lOCLintCore
/usr/bin/ld: 找不到 -lOCLintRuleSet
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
[6/79] Building CXX object test/basic/CMakeFiles/BasicTests.dir/CollapsibleIfStatementsRuleTest.cpp.o
ninja: build stopped: subcommand failed.

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by BigNewbiePlus** [comment]
Sorry for that I run the command uncorrectly. I run `./test rules` before `./test` .when i first run `./test` and then `./test rules` It works fine!  I have closed this issue.
