### ISSUE TITLE
when i use -enable-clang-static-analyzer option, how can i specify  parameters for selection clang rules?

### ISSUE THREAD

**Issue by eiauo** [oclint/oclint#484]
### Issue Summary
when i use -enable-clang-static-analyzer option,  which  analyzer-checker is selected?

How can i specify  parameters for selection another clang rules checker?

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by BigNewbiePlus** [comment]
Look at this [clang-static-analyzer-options](http://docs.oclint.org/en/stable/manual/oclint.html#clang-static-analyzer-options) It means the oclint will collect your info  and  analysis but not for rule check. however, it is anonymous analytics

**Comment by UnrealQuester** [comment]
With `-enable-clang-static-analyzer` we simply add the ouput of https://clang-analyzer.llvm.org/ to the generated report. AFAIK this analyzer does not take any options, so you cannot change its behaviour.

**Comment by eiauo** [comment]
Thanks for your replay.
