### ISSUE TITLE
How to debug custom rule in XCode?

### ISSUE THREAD

**Issue by silan-liu** [oclint/oclint#485]
I use CMake command to generate XCode project, and write some rules，and when I build it, it will generate a xx.dylib, but i don't know how to debug it in Xcode.

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by litianying137** [comment]
@silan-liu 
一、create xcode floder for each oclint module
![image](https://user-images.githubusercontent.com/3120145/34067989-bf012698-e26e-11e7-87dc-8cfeef31dc7f.png)
二、Use CMake command generate xcode project in xcode floder for each module
```
cmake -G Xcode -D CMAKE_CXX_COMPILER=../build/llvm-install/bin/clang++ -D CMAKE_C_COMPILER=../build/llvm-install/bin/clang -D OCLINT_BUILD_DIR=../build/oclint-core -D OCLINT_SOURCE_DIR=../oclint-core -D OCLINT_METRICS_SOURCE_DIR=../oclint-metrics -D OCLINT_METRICS_BUILD_DIR=../build/oclint-metrics -D LLVM_ROOT=../build/llvm-install/ ../countly
```
三、build each alone xcode project successed
   some link info need fixed。
四、create xcode workspace
need fixed each project target dependent .
need fixed some searh path 
![image](https://user-images.githubusercontent.com/3120145/34068062-71b47b4a-e270-11e7-9feb-d122932a333b.png)

五、select oclint target to run in debug model。
you can debug oclint source and custome rule。

**Comment by silan-liu** [comment]
Thanks! I've tried and I found that it only need to generate the oclint_driver and oclint_rules xcode project,build oclint_driver succeed. Then it can work.

**Comment by yangshengtao** [comment]
how oclint_driver build?

**Comment by silan-liu** [comment]
1.cd oclint root dir
2.mkdir oclint-xcode-driver
3.touch create.sh

```
#! /bin/sh -e

cmake -G Xcode \
    -D CMAKE_CXX_COMPILER=../build/llvm-install/bin/clang++  \
    -D CMAKE_C_COMPILER=../build/llvm-install/bin/clang \
    -D OCLINT_BUILD_DIR=../build/oclint-core \
    -D OCLINT_SOURCE_DIR=../oclint-core \
    -D OCLINT_METRICS_SOURCE_DIR=../oclint-metrics \
    -D OCLINT_METRICS_BUILD_DIR=../build/oclint-metrics \
    -D LLVM_ROOT=../build/llvm-install/ ../oclint_drivers
```

4.sh create.sh

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.
