### ISSUE TITLE
The rule 'OCLint:compiler warning' does not exist.

### ISSUE THREAD

**Issue by EngErik** [oclint/oclint#486]
### Issue Summary
In sonar-scanner step, i found this error: 

_**The rule 'OCLint:compiler warning' does not exist.**_

Plugin is already installed at SonarQube and i can see all rules from Objective-c and Oclint. 

### Environment
- Operation system name and version: OS X El Capitan - 10.11.6
- OCLint version: 0.13
- How OCLint is installed: Homebrew install

### Reproduction Steps
Detailed steps to reproduce the issue.

1 - Execute run-sonar.sh in the project root and wait for results. 

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?
Content results from oclint.xml have to be inserted in SonarQube Dashboard

### Actual Behavior
What currently happens as a result of the reproduction steps?
The rule 'OCLint:compiler warning' does not exist.

### Even Better
Is your project open sourced? If yes, can you point us to your repository?
If not, is it possible to make a small project that fails the Travis CI?
If not, can you create a gist with your sample code for us?

**Comment by croustibapt** [comment]
Same problem here...

**Comment by croustibapt** [comment]
I figured out what's going on. The problem is that OCLint cannot handle user defined warnings (ex: #warning My custom warning). Commenting each occurence solves the issue.

**Comment by croustibapt** [comment]
It's more than that. All compiler warnings make OCLint stop...

**Comment by croustibapt** [comment]
Ok! Got it! The problem cames from Backelite and no from OCLint: https://github.com/Backelite/sonar-objective-c/pull/50
Should be closed.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
