### ISSUE TITLE
OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by cissusnar** [oclint/oclint#488]
### Issue Summary
oclint-json-compilation-database report error with "OSError: [Errno 7] Argument list too long"

### Environment
- Operation system name and version:
macOS 10.13.2 

- OCLint version:
LLVM (http://llvm.org/):
  LLVM version 5.0.0svn-r313528
  Optimized build.
  Default target: x86_64-apple-darwin17.3.0
  Host CPU: haswell

OCLint (http://oclint.org/):
  OCLint version 0.13.
  Built Sep 18 2017 (08:58:40).

- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
homebrew

### Reproduction Steps
1. use xcpretty generate oclint-json-compilation-database json file
2. my project is very large, and size of json file is 45Mb
3. run oclint-json-compilation-database
4. OSError: [Errno 7] Argument list too long

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichis** [comment]
Thanks for causing our attention again about this issue. It's a known one in #233, and a solution/workaround has been provided. If you have better way to handle this, feel free to comment on there.
