### ISSUE TITLE
Network.cpp:103:27: error: ‘memset’ was not declared in this scope

### ISSUE THREAD

**Issue by gdonald** [oclint/oclint#491]
### Issue Summary
Compilation fails:
oclint-0.13/countly/lib/Network.cpp:103:27: error: ‘memset’ was not declared in this scope

### Environment
- Operation system name and version: 
> uname -a
Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

- OCLint version:  0.13

- How OCLint is installed: local build?

From source: v0.13.tar.gz

### Reproduction Steps
cd oclint-0.13/oclint-scripts; ./make

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by gdonald** [comment]
Not sure what else you need, fix it or don't.

**Comment by UnrealQuester** [comment]
Could not reproduce on a debian 9.3 VM. The required header for memset (cstring) is also included. Does the problem also occur if you just do `./countly co && ./countly build`?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by gdonald** [comment]
The latest version ends telling me my cmake program is not set.  I have cmake install so I have no idea what it actually needs me to do.

I'm going to close this ticket.  It's failed to build for me twice now and given the length of time since my first failed attempt I don't really recall why I wanted to install it in the first place.  Thanks anyway.
