### ISSUE TITLE
Using OCLint in Xcode 9 seems to be broken

### ISSUE THREAD

**Issue by fetzig** [oclint/oclint#494]
### Issue Summary

oclint integration/usage with xcode seems to be incompatible with xcode 9. since there is no info about compatibilty (xcode, oclint, xctool), especially no info about xcode  setup (project vs. workspace, cocoapods, ...), I have no idea where to even start.

### Environment

mac os 10.13.3
oclint 0.13
xctool 0.3.4
xcode 9.2 
xcpretty 0.2.8

use any of the run scripts linked in the documentation http://oclint-docs.readthedocs.io/en/stable/guide/xcode.html

tried all kinds of run scripts using xctool or xcpretty.

### Reproduction Steps

http://oclint-docs.readthedocs.io/en/stable/guide/xcode.html within an existing ios xcode workspace (code base objective-c and swift, cocoapods)

### Expected Behavior

get some lint warnings/errors after build "OCLint" target.

### Actual Behavior

The result is always:

either "Error: compile_commands.json not found at...${SRCROOT}" 

or 

"Build Succeeded" and no output at all

depending on used runscript.

Side note: integration of swiftlint took not even a minute...like any other linting tool I ever used. it seems like i'm doing something very wrong. is there a cocoapods integration of oclint like swiftlint has?

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by fetzig** [comment]
@ryuichi-assistant have restructured the issue description according to the template.

**Comment by silverhammermba** [comment]
I'm not having any issue _running_ oclint with Xcode 9 if I apply the #497 patch and use the COMPILER_INDEX_STORE workaround, but even then the output seems really messed up.

I run with

    xcodebuild ... clean build COMPILER_INDEX_STORE_ENABLE=NO | xcpretty -r json-compilation-database -o compile_commands.json
    oclint-json-compilation-database -- -report-type=pmd > oclint.xml

And the output is... pretty much worthless:
* For some reason it analyzes about a hundred Foundation files, which I don't care about
* Another 50 or so files get the error "Too many open files" (why can't oclint wait for some file handles to free up?)
* Another 50 or so just complain "could not build module 'Foundation/UIKit/CoreFoundation" etc.
* The rest of the output is about variable names or line lengths being too long

I can assure you that this is not a high-quality codebase, so I suspect that oclint isn't actually fully analyzing everything. I'm pretty disappointed in this tool so far.

**Comment by ryuichis** [comment]
Closing this one as Xcode 9 is obsolete.
