### ISSUE TITLE
Interface/enum redefinition related compiler errors in OCLint report

### ISSUE THREAD

**Issue by ravimandala** [oclint/oclint#496]
### Issue Summary
When a JSON compilation database is created from xcodebuild log (using `oclint-xcodebuild` or `xcpretty`), the resultant `compile_commands.json` is leading to compiler errors in OCLint report. Typical errors in **Objective-C** code are...

* duplicate interface definition for class 'XYZObservable'
* property has a previous declaration
* redefinition of 'XYZDataManagerBackedResourceOptions' (which is an enum)
* redefinition of enumerator 'XYZDataManagerBackedResourceOptionsFetchFromCache'
etc.,

The clang command from `compile_commands.json` works fine without compilation errors in the command line. But when it goes through OCLint, I see compiler errors in the html report.

### Environment
- Operation system name and version: macOS Sierra 10.12.6
- OCLint version: 0.13
- How OCLint is installed: build manually by checking out a fork of OCLint repo.

### Reproduction Steps
Detailed steps to reproduce the issue.
```
xcodebuild -workspace '...' -scheme '...' -configuration 'Debug' clean build -derivedDataPath ./build/xyz -sdk iphonesimulator CLANG_ENABLE_MODULE_DEBUGGING=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO COMPILER_INDEX_STORE_ENABLE=NO | tee xcodebuild.log | oclint-xcodebuild
oclint-json-compilation-database -e Pods -v -- -extra-arg=-Wno-everything -list-enabled-rules -no-analytics -verbose -report-type html -o lint_report.html
```

#### Sample code

```
<Not available yet>
```

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?
Since the xcodebuild did not result in any compiler errors, the outcome is expected to be a lint report with a list of violations and no compiler errors.

### Actual Behavior
What currently happens as a result of the reproduction steps?
A lint report where some files are analyzed and some files are not compiled due to compiler errors.

### Even Better
Is your project open sourced? 
No.
If not, is it possible to make a small project that fails the Travis CI? 
Can do if needed.
If not, can you create a gist with your sample code for us?
Yes.

\cc @ryuichis @UnrealQuester

**Comment by ravimandala** [comment]
@ryuichis I need your help on this. Can you please look into it?

**Comment by ravimandala** [comment]
Unfortunately, I can't share the `compile_commands.json` and I don't have a sample project where this issue can be reproduced. But, yes, I too suspect the clang parity. 

The clang version used by my Xcode 9.1 installation is (and clang that is part of `compile_commands.json`)...
```
$ /Applications/Xcode9.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode9.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

where as my custom OCLint build has the below version... 
```
$ ./Linter/bin/oclint -version
LLVM (http://llvm.org/):
  LLVM version 5.0.0svn-r326849
  DEBUG build with assertions.
  Default target: x86_64-apple-darwin16.7.0
  Host CPU: skylake

OCLint (http://oclint.org/):
  OCLint version 0.13.
  Built Mar  6 2018 (18:43:09).
```

Do I need to rebuild my binary with a different revision? If yes, which one? Any pointers on how this can be mitigated is greatly appreciated.

**Comment by UnrealQuester** [comment]
You could try building oclint with your systems LLVM version. Check out a clean build and run [makeWithSystemLLVM](https://github.com/oclint/oclint/blob/master/oclint-scripts/makeWithSystemLLVM) with the path to your LLVM installation.
This is not officially supported but might work for you.

**Comment by ravimandala** [comment]
Tried buildWithSystemLLVM with my local latest LLVM+Clang build. It did not build successfully and it was throwing errors about missing files in the specified LLVM_PATH.

We built OCLint with https://github.com/apple/swift-clang but ended up seeing the same redefinition errors.
```
LLVM (http://llvm.org/):
  LLVM version 6.0.0
  DEBUG build with assertions.
  Default target: x86_64-apple-darwin17.4.0
  Host CPU: skylake

OCLint (http://oclint.org/):
  OCLint version 0.13.1.
  Built Mar 15 2018 (19:50:50).
```

Overall, I believe the #import is not taking care of redundant inclusions, if any. I believe OCLint is widely used for linting ObjC projects. I wonder how our project could be different!!!
\cc @UnrealQuester @ryuichis

**Comment by ravimandala** [comment]
@UnrealQuester @ryuichis @ryuichi-assistant 

This is most likely a bug in OCLint. The possible issue is oclint creating a **SyntaxOnlyAction** that bypasses the _normal_ header parsing logic, which probably bypasses the real preprocessor.

Here is a repo to reproduce the error.
https://github.com/ravimandala/linter-issue

Please take a look into it and let us know your thoughts.

**Comment by UnrealQuester** [comment]
Sadly I do not have a mac system to reproduce this error and no experience with the language, so I cannot help here. Maybe someone else can reproduce the error on their machine and can help.

@ravimandala regarding the SyntaxOnlyAction: Would compiling with clangs `-fsyntax-only` option have the same effect?

**Comment by ob** [comment]
I've tracked down the problem to `oclint` not honoring the `-ivfsoverlay` flag in the compiler. It seems the way `oclint` is initializing the `compilerInvocation` class is missing setting up the filesystem properly so that it has a VFS. I'm trying to understand the code in `oclint` but I don't get the reason why it's creating an array of `FileManager` objects... I'm still poking at it, but if anyone has any context on what it's trying to do that would be helpful.

**Comment by ob** [comment]
I submitted #497 which I believe fixes this.

**Comment by RayCyder** [comment]
here is my oclint debug info  . similar problem:  compile command can run in cmd line,but oclint exit with 6.  seems same header had compiled twice ,given diag::err_duplicate_xxx error
(lldb) p PDecl->dump()
ObjCPropertyDecl 0x1079e5338 </Users/ray/Documents/gitPro/xxx/src/common/kgcommon/commonThirdPart/SharedOtherSDK/QQSDK/TencentOpenAPI.framework/Headers/TencentMessageObject.h:118:1, col:50> col:50 nSdkVersion 'NSInteger':'long'
`-FullComment 0x1079e5450 <line:117:4, col:26>
  `-ParagraphComment 0x1079e5420 <col:4, col:26>
    `-TextComment 0x1079e53f0 <col:4, col:26> Text=" 请求的SDK版本号 "
(lldb) p prevDecl->dump()
ObjCPropertyDecl 0x1079c86d8 </Users/ray/Documents/gitPro/xxx/src/common/kgcommon/commonThirdPart/SharedOtherSDK/QQSDK/TencentOpenAPI.framework/Headers/TencentMessageObject.h:118:1, col:50> col:50 nSdkVersion 'NSInteger':'long' readonly assign nonatomic unsafe_unretained
`-FullComment 0x1079e5520 <line:117:4, col:26>
  `-ParagraphComment 0x1079e54f0 <col:4, col:26>
    `-TextComment 0x1079e54c0 <col:4, col:26> Text=" 请求的SDK版本号 "
