### ISSUE TITLE
OCLint should use LLVM from swift

### ISSUE THREAD

**Issue by ob** [oclint/oclint#498]
While playing with OCLint I found differences between Xcode’s clang compiler and the clang compiler shipped with OCLint. I think Xcode ships with the fork of clang used in Swift (available in github). 

I think bundling the latest LLVM from the Swift project would cause less problems for iOS projects.

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by UnrealQuester** [comment]
Could not find any prebuilt packages on first glance. Do you happen to know if there are any?
These are pretty much required for ci as building it from source takes too long for travis.

**Comment by ob** [comment]
Hmm... good point. I don't know if any binary releases for the LLVM/Clang of swift. I wonder if it would be something worth bringing up with the swift project... that they should make binary releases of the LLVM/Clang parts of swift available as part of _their_ release process...

**Comment by UnrealQuester** [comment]
Would linking against the system LLVM be an option? I suggested this in #496 but it looked like it did not work out for the original poster.

**Comment by ob** [comment]
I'm not sure what you are calling the "system LLVM". Apple's Xcode application doesn't include a full LLVM release per-se... for example, all the header files of the clang compiler are missing. So if you are referring to Xcode as the system's LLVM then I don't think we can use that.

If you mean the LLVM you get from running something like `brew install llvm`, then I think we could use that but from [their formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb) it seems they are using the release version of clang/llvm and not the clang/llvm bundled with Swift. So if you mean the brew version then I don't think we can use that.

I didn't check Linux, but my guess would be that it also doesn't use the Swift version of Clang/LLVM.

**Comment by UnrealQuester** [comment]
I was hoping that Xcode would bundle a complete LLVM package. If this is not the case, users might still be able to use the swift/llvm package by downloading the source manually and putting it where the oclint script would put it.

But this would probably be infeasible to test in travis, so we are unlikely to officially support that.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
