### ISSUE TITLE
Custom rule cause segmentation fault

### ISSUE THREAD

**Issue by rickytan** [oclint/oclint#499]
### Issue Summary
I built my first rule using LLVM 6.0.0, and it successfully generated a `x.dylib`. But when I load it to oclint-0.13, it crashs with **segmentation fault 11**

### Environment
- Operation system name and version: macOS Sierra 10.12.6
- OCLint version: 0.13
- LLVM version: 6.0.0, installed via homebrew
- How OCLint is installed: homebrew install

### Reproduction Steps
Detailed steps to reproduce the issue.

#### Sample code
https://github.com/rickytan/oclint/blob/master/oclint-rules/rules/style/CompoundStatementStyleRule.cpp

Command to run OCLint with the code above.

### Expected Behavior
Not crash

### Actual Behavior
Crash

**Comment by UnrealQuester** [comment]
Does the crash occur because you import the rule or is it in the code of the rule itself? What have you done so far to narrow down the crash?

You could try commenting out blocks of code until the segfault no longer occurs or run oclint under a debugger to see where the segfault happens.

**Comment by rickytan** [comment]
I re-compile my rule under **LLVM 5.0.1**, and it works fine! Thanks
