### ISSUE TITLE
-j option for oclint-scripts/tests not working

### ISSUE THREAD

**Issue by codedraughtsman** [oclint/oclint#506]
### Issue Summary
running `oclint-scripts/tests -j1` uses 6 processes instead of one to build the oclint tests.

By default, `ninja` runs with 6 processes if the `-j` option is not set. This leads me to believe that `oclint-scripts/tests` is not correctly passing the `-j` option to the `ninja` command call.  

Each of the build processes were consuming about 3GB of RAM causing my computer to run out of RAM and swap space. I worked around this issue by navigating to the test build folder (i.e. `build/oclint-reporters-test` ) and manually running  `ninja -j1` This correctly used one process to build the tests.

Could someone please check this out and verify that it is a bug (and not just my computer)?
Thank you.

### Environment
- Operation system name and version: Ubuntu 16.04.4 LTS
- OCLint version: git ID [8d45128](https://github.com/oclint/oclint/commit/8d4512888982b4aae5047b63c43ea89f26dcb65c) (the latest version available from git hub).
- How OCLint is installed: Local build following the oclint documentation [instructions](http://docs.oclint.org/en/stable/devel/compiletest.html)

### Reproduction Steps
`#start in the oclint root directory` 
`cd oclint-scripts/`
`./test -j1`

Check the number of processes spawned to build the test folders. I used the system monitor application to do this while the `./test -j1` command was running.

### Expected Behavior
Only one process should be used to compile and link the tests.

### Actual Behavior
You should see more than one process going flat tack compiling and linking the tests.

**Comment by UnrealQuester** [comment]
Thank you for your bug report. We indeed seem to ignore this option when invoking ninja. As a workaround you could try using `--no-ninja` to invoke make instead.

**Comment by codedraughtsman** [comment]
@UnrealQuester Thank you for your quick response and fix.
