### ISSUE TITLE
oclint website link gives "requested URL was not found" error

### ISSUE THREAD

**Issue by codedraughtsman** [oclint/oclint#508]
### Issue Summary
The community link on the top right hand side of the oclint docs website ([http://docs.oclint.org/en/stable/index.html](http://docs.oclint.org/en/stable/index.html)) is giving a "requested URL was not found" error.

Thank you.

### Environment
I'm using Firefox 6.00.1 on ubuntu.

### Reproduction Steps
Go to [http://docs.oclint.org/en/stable/index.html](http://docs.oclint.org/en/stable/index.html) and click on the community link in the top right hand corner (see picture). It should take you to [http://oclint.org/community.html](http://oclint.org/community.html) and display a page not found result.
![screenshot-2018-6-30 oclint - 0 13 documentation - documentation](https://user-images.githubusercontent.com/40680543/42120945-4db9a3bc-7c78-11e8-8812-4a1917d27678.png)

### Expected Behavior
I expect to see a page explaining where, and how, to ask questions about contributing to oclint. 

I personally like to know where I can discuss potential changes about what additions should or should not be added. For example, I am considering using doxygen to generate documentation about the oclint internals. Should this be added to the oclint repository?

### Actual Behavior
You should get a "requested URL was not found" error.
![screenshot-2018-6-30 oclint - page not found](https://user-images.githubusercontent.com/40680543/42120912-ca7b0f86-7c77-11e8-95c2-2eaeb2e58569.png)

**Comment by UnrealQuester** [comment]
It appears that link is only on the oclint docs subpages and not on the start page (http://oclint.org).
Maybe we should consider merging the community and github links.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
