### ISSUE TITLE
oclint-json-compilation-database: Unable to run oclint on Xcode project

### ISSUE THREAD

**Issue by f2prateek** [oclint/oclint#509]
### Issue Summary
Unable to run `oclint-json-compilation-database` on my project successfully, it fails with `oclint: error: one compiler command contains multiple jobs:`

### Environment
- Operation system name and version: macOs 10.13.5
- OCLint version:oclint-0.13.1
- How OCLint is installed: Using the Prebuilt binary download from Github for OS X from https://github.com/oclint/oclint/releases/download/v0.13.1/oclint-0.13.1-x86_64-darwin-17.4.0.tar.gz

### Reproduction Steps
1. Clone https://github.com/segmentio/analytics-ios
2. Run `make clean`
3. Run `make build | xcpretty -r json-compilation-database -o compile_commands.json`. This should create a `compile_commands.json` file. Mine looks like this https://cloudup.com/coTEo-zLY2M.
4. Run `oclint-json-compilation-database -v -e Pods -- -report-type html -o oclint.html`. This fails with the following message https://cloudup.com/cDFDSUufr41.

#### Sample code
The project I'm running this on is open source at https://github.com/segmentio/analytics-ios. I haven't been able to narrow down the issue yet.

### Expected Behavior
Expected that an HTML report would be generated.

### Actual Behavior
The command fails with an error and no report is generated.

### Even Better
Is your project open sourced? If yes, can you point us to your repository?: Yes - the project is open source at https://github.com/segmentio/analytics-ios.
If not, is it possible to make a small project that fails the Travis CI? N/A
If not, can you create a gist with your sample code for us? N/A

I'll continue to try to make a smaller sample, but I suspect that since this is the first time I'm using oclint, I am using it incorrectly.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
