### ISSUE TITLE
Getting error while building the with the OClint target

### ISSUE THREAD

**Issue by jprossardalia** [oclint/oclint#511]
### Issue Summary
Getting error while building the with the OClint target after following the instruction from the tutorial.

### Environment
- Operation system name and version:macOS High Serria 10.13.6
- OCLint version: 0.13
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others? Homebrew

### Reproduction Steps
As per the tutorial instruction, I have created a new aggregate target and added the following script 

source ~/.bash_profile
cd ${SRCROOT}
xcodebuild -scheme OClint -workspace TestLeak2.xcworkspace clean
xcodebuild -scheme OClint -workspace TestLeak2.xcworkspace | xcpretty -r json-compilation-database --output compile_commands.json
oclint-json-compilation-database -exclude Pods -exclude build -exclude Internal -exclude ThirdParties -- -report-type xcode

I got the above script from here: https://gist.github.com/ryuichis/755e6297aec13c900cdf
#### Sample code
[TestLeak2.zip](https://github.com/oclint/oclint/files/2192386/TestLeak2.zip)

### Expected Behavior
A report or information about the code in the project.

### Actual Behavior
Getting this error:
..Xcode/DerivedData/TestLeak2-gzbxapwlyenklwcrrpccxzqiafcj/Build/Intermediates.noindex/TestLeak2.build/Debug-iphonesimulator/OClint.build/Script-BA5B473720F8A85F00A76D76.sh: line 5: xcpretty: command not found

Build log:
[Build OClint_2018-07-13T16-15-39.txt](https://github.com/oclint/oclint/files/2192417/Build.OClint_2018-07-13T16-15-39.txt)

Even though the xcpretty is  installed 
![screen shot 2018-07-13 at 4 40 01 pm](https://user-images.githubusercontent.com/22931369/42688817-75e079b8-86bb-11e8-9e1f-e944dbf4f758.png)

### Even Better
Is your project open sourced? If yes, can you point us to your repository? No
If not, is it possible to make a small project that fails the Travis CI? I have attached a small project above 
If not, can you create a gist with your sample code for us? N/A

**Comment by Nguyentung79** [comment]
Cgjnnkv

**Comment by Nguyentung79** [comment]
Vhkkbvv

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
