### ISSUE TITLE
get the wrong Cyclomatic Complexity of a function

### ISSUE THREAD

**Issue by lmy690043305** [oclint/oclint#520]
### Issue Summary
get the wrong Cyclomatic Complexity of a function through oclint
### Environment
 OCLint version 0.13.

### Reproduction Steps
oclint-json-compilation-database -e Pods -v -- -rc=LONG_LINE=150 -rc=NCSS_METHOD=60 -report-type pmd -o sonar-reports/lizard-report.xml -max-priority-1 300000  -max-priority-2 300000  -max-priority-3 300000

#### Sample code

(void)initMyScrollViewContentView{

self.myScrollViewContentView = [[UIView alloc] initWithFrame:CGRectZero];
self.myScrollViewContentView.backgroundColor = RGBCOLOR(0xff, 0xff, 0xff);
[self.myScrollView addSubview:self.myScrollViewContentView];
[self.myScrollViewContentView mas_makeConstraints:^(MASConstraintMaker *make) {
make.edges.mas_equalTo(self.myScrollView);
make.width.mas_equalTo(self.myScrollView);
make.height.mas_equalTo(ScreenHeight-kNavBar_H-kBottomSafeArea_H-50+self.headerHeight);
}];
}
#define RGBCOLOR(r,g,b) ([UIColor colorWithRed:(r)/255.0 green:(g)/255.0 blue:(b)/255.0 alpha:1])
Command to run OCLint with the code above.

### Expected Behavior
Cyclomatic Complexity Number is 2
### Actual Behavior
Cyclomatic Complexity Number 25 exceeds limit of 10
### Even Better
This method has a macro definition method RGBCOLOR, macro definition inside the cyclomatic complexity is 1, the cyclomatic complexity of the above method should be 2, but the final scan cyclomatic complexity is 25, is wrong, someone encountered similar problems

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
