### ISSUE TITLE
ld: library not found for -lgmock

### ISSUE THREAD

**Issue by vaibhav-shah** [oclint/oclint#523]
### Issue Summary
A brief but thorough description of the issue.
This happens when I run the test script: "clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation) ld: library not found for -lgmock"
I can see that this is an error that also shows up in Travis CI for OCLint when running this with AppleClang.

### Environment
- Operation system name and version: OSX 10.13.6 (High Sierra)
- OCLint version: 0.13.1
- How OCLint is installed: I checkout this version above into my project. I have a build script I run which calls `make` inside oclint-scripts and then runs the `test` script.
### Reproduction Steps
I ran my build script. It came up with this error. Then I ran `make` with no error, and after that I ran `test`. This error was produced.

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?
Test modules are built and I see my tests run.

### Actual Behavior
What currently happens as a result of the reproduction steps?
Get a linker command error, and as a result tests do not get run.

### Even Better
If not, is it possible to make a small project that fails the Travis CI? It's already failing Travis CI.

**Comment by vaibhav-shah** [comment]
From what I've seen trying to fix the issue, the `gmock` and `gtest` library files are being expected to be inside `build/googletest/` and `build/googletest/gtest`, but they don't show up there.

They show up inside `build/googletest/lib`. I have not been able to determine a root cause for this.

**Comment by carusd** [comment]
Me too. And I try to copy the library file to the expected dir and test again, still failed.

here's the output: 

`
Undefined symbols for architecture x86_64:
  "testing::InitGoogleTest(int*, char**)", referenced from:
      void testing::internal::InitGoogleMockImpl<char>(int*, char**) in libgmock.a(gmock-all.cc.o)
  "testing::InitGoogleTest(int*, wchar_t**)", referenced from:
      void testing::internal::InitGoogleMockImpl<wchar_t>(int*, wchar_t**) in libgmock.a(gmock-all.cc.o)
  "testing::AssertionResult::AssertionResult(testing::AssertionResult const&)", referenced from:
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::PolymorphicMatcher<testing::internal::IsNullMatcher> >::operator()<clang::ASTContext*>(char const*, clang::ASTContext* const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::internal::EqMatcher<int> >::operator()<int>(char const*, int const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::PolymorphicMatcher<testing::internal::StrEqualityMatcher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::operator()<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::internal::EqMatcher<oclint::RuleBase*> >::operator()<oclint::RuleBase const*>(char const*, oclint::RuleBase const* const&) const in RuleCarrierTest.cpp.o
  "testing::AssertionFailure()", referenced from:
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::PolymorphicMatcher<testing::internal::IsNullMatcher> >::operator()<clang::ASTContext*>(char const*, clang::ASTContext* const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::internal::EqMatcher<int> >::operator()<int>(char const*, int const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::PolymorphicMatcher<testing::internal::StrEqualityMatcher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::operator()<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::internal::EqMatcher<oclint::RuleBase*> >::operator()<oclint::RuleBase const*>(char const*, oclint::RuleBase const* const&) const in RuleCarrierTest.cpp.o
  "testing::AssertionSuccess()", referenced from:
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::PolymorphicMatcher<testing::internal::IsNullMatcher> >::operator()<clang::ASTContext*>(char const*, clang::ASTContext* const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::internal::EqMatcher<int> >::operator()<int>(char const*, int const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::PolymorphicMatcher<testing::internal::StrEqualityMatcher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::operator()<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in RuleCarrierTest.cpp.o
      testing::AssertionResult testing::internal::PredicateFormatterFromMatcher<testing::internal::EqMatcher<oclint::RuleBase*> >::operator()<oclint::RuleBase const*>(char const*, oclint::RuleBase const* const&) const in RuleCarrierTest.cpp.o
  "testing::Test::SetUp()", referenced from:
      vtable for RuleCarrierTest_Initializationasdf_Test in RuleCarrierTest.cpp.o
      vtable for RuleCarrierTest_AddViolation_Test in RuleCarrierTest.cpp.o
      vtable for RuleCarrierTest_AddViolationWithEmptyFilePath_Test in RuleCarrierTest.cpp.o
  "testing::Test::TearDown()", referenced from:
      vtable for RuleCarrierTest_Initializationasdf_Test in RuleCarrierTest.cpp.o
      vtable for RuleCarrierTest_AddViolation_Test in RuleCarrierTest.cpp.o
      vtable for RuleCarrierTest_AddViolationWithEmptyFilePath_Test in RuleCarrierTest.cpp.o
  "testing::Test::Test()", referenced from:
      RuleCarrierTest_Initializationasdf_Test::RuleCarrierTest_Initializationasdf_Test() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolation_Test::RuleCarrierTest_AddViolation_Test() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolationWithEmptyFilePath_Test::RuleCarrierTest_AddViolationWithEmptyFilePath_Test() in RuleCarrierTest.cpp.o
  "testing::Test::~Test()", referenced from:
      RuleCarrierTest_Initializationasdf_Test::~RuleCarrierTest_Initializationasdf_Test() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolation_Test::~RuleCarrierTest_AddViolation_Test() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolationWithEmptyFilePath_Test::~RuleCarrierTest_AddViolationWithEmptyFilePath_Test() in RuleCarrierTest.cpp.o
  "testing::Message::Message()", referenced from:
      RuleCarrierTest_Initializationasdf_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolation_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolationWithEmptyFilePath_Test::TestBody() in RuleCarrierTest.cpp.o
      testing::AssertionResult& testing::AssertionResult::operator<<<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in RuleCarrierTest.cpp.o
      testing::internal::UnorderedElementsAreMatcherImplBase::Elements(unsigned long) in libgmock.a(gmock-all.cc.o)
      testing::internal::GoogleTestFailureReporter::ReportFailure(testing::internal::FailureReporterInterface::FailureType, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libgmock.a(gmock-all.cc.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > testing::internal::StreamableToString<char*>(char* const&) in libgmock.a(gmock-all.cc.o)
      ...
  "testing::Message::operator<<(wchar_t*)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > testing::internal::StreamableToString<wchar_t*>(wchar_t* const&) in libgmock.a(gmock-all.cc.o)
  "testing::UnitTest::GetInstance()", referenced from:
      RUN_ALL_TESTS() in RuleCarrierTest.cpp.o
      testing::internal::Log(testing::internal::LogSeverity, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libgmock.a(gmock-all.cc.o)
      testing::Mock::RegisterUseByOnCallOrExpectCall(void const*, char const*, int) in libgmock.a(gmock-all.cc.o)
  "testing::UnitTest::Run()", referenced from:
      RUN_ALL_TESTS() in RuleCarrierTest.cpp.o
  "testing::internal::ParseInt32(testing::Message const&, char const*, int*)", referenced from:
      testing::internal::ParseGoogleMockIntFlag(char const*, char const*, int*) in libgmock.a(gmock-all.cc.o)
  "testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)", referenced from:
      RuleCarrierTest_Initializationasdf_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolation_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolationWithEmptyFilePath_Test::TestBody() in RuleCarrierTest.cpp.o
      testing::internal::GoogleTestFailureReporter::ReportFailure(testing::internal::FailureReporterInterface::FailureType, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libgmock.a(gmock-all.cc.o)
  "testing::internal::AssertHelper::~AssertHelper()", referenced from:
      RuleCarrierTest_Initializationasdf_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolation_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolationWithEmptyFilePath_Test::TestBody() in RuleCarrierTest.cpp.o
      testing::internal::GoogleTestFailureReporter::ReportFailure(testing::internal::FailureReporterInterface::FailureType, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libgmock.a(gmock-all.cc.o)
  "testing::internal::GetTestTypeId()", referenced from:
      ___cxx_global_var_init in RuleCarrierTest.cpp.o
      ___cxx_global_var_init.5 in RuleCarrierTest.cpp.o
      ___cxx_global_var_init.16 in RuleCarrierTest.cpp.o
  "testing::internal::PrintStringTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)", referenced from:
      testing::internal::PrintTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in RuleCarrierTest.cpp.o
      testing::internal::PrintTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in libgmock.a(gmock-all.cc.o)
  "testing::internal::FormatFileLocation(char const*, int)", referenced from:
      testing::internal::FunctionMockerBase<void ()>::DescribeDefaultActionTo(std::__1::tuple<> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const in RuleCarrierTest.cpp.o
      testing::internal::ExpectationBase::DescribeLocationTo(std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const in RuleCarrierTest.cpp.o
      testing::internal::FunctionMockerBase<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const ()>::DescribeDefaultActionTo(std::__1::tuple<> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const in RuleCarrierTest.cpp.o
      testing::internal::FunctionMockerBase<int ()>::DescribeDefaultActionTo(std::__1::tuple<> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const in RuleCarrierTest.cpp.o
      testing::internal::ExpectationBase::DescribeLocationTo(std::__1::basic_ostream<char, std::__1::char_traits<char> >*) const in libgmock.a(gmock-all.cc.o)
      testing::(anonymous namespace)::MockObjectRegistry::~MockObjectRegistry() in libgmock.a(gmock-all.cc.o)
  "testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)", referenced from:
      ___cxx_global_var_init in RuleCarrierTest.cpp.o
      ___cxx_global_var_init.5 in RuleCarrierTest.cpp.o
      ___cxx_global_var_init.16 in RuleCarrierTest.cpp.o
  "testing::internal::GetCurrentOsStackTraceExceptTop(testing::UnitTest*, int)", referenced from:
      testing::internal::Log(testing::internal::LogSeverity, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in libgmock.a(gmock-all.cc.o)
  "testing::internal::IsTrue(bool)", referenced from:
      testing::internal::MutexBase::AssertHeld() const in RuleCarrierTest.cpp.o
      testing::internal::MaxBipartiteMatchState::Compute() in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::AssertHeld() const in libgmock.a(gmock-all.cc.o)
      testing::internal::ThreadLocal<testing::Sequence*>::ValueHolder* testing::internal::CheckedDowncastToActualType<testing::internal::ThreadLocal<testing::Sequence*>::ValueHolder, testing::internal::ThreadLocalValueHolderBase>(testing::internal::ThreadLocalValueHolderBase*) in libgmock.a(gmock-all.cc.o)
  "testing::internal::String::CaseInsensitiveCStringEquals(char const*, char const*)", referenced from:
      testing::internal::CaseInsensitiveCStringEquals(char const*, char const*) in RuleCarrierTest.cpp.o
  "testing::internal::GTestLog::GTestLog(testing::internal::GTestLogSeverity, char const*, int)", referenced from:
      testing::internal::MutexBase::Lock() in RuleCarrierTest.cpp.o
      testing::internal::MutexBase::Unlock() in RuleCarrierTest.cpp.o
      testing::internal::MutexBase::AssertHeld() const in RuleCarrierTest.cpp.o
      testing::internal::MaxBipartiteMatchState::Compute() in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::AssertHeld() const in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::Unlock() in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::Lock() in libgmock.a(gmock-all.cc.o)
      ...
  "testing::internal::GTestLog::~GTestLog()", referenced from:
      testing::internal::MutexBase::Lock() in RuleCarrierTest.cpp.o
      testing::internal::MutexBase::Unlock() in RuleCarrierTest.cpp.o
      testing::internal::MutexBase::AssertHeld() const in RuleCarrierTest.cpp.o
      testing::internal::MaxBipartiteMatchState::Compute() in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::AssertHeld() const in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::Unlock() in libgmock.a(gmock-all.cc.o)
      testing::internal::MutexBase::Lock() in libgmock.a(gmock-all.cc.o)
      ...
  "testing::Message::GetString() const", referenced from:
      testing::AssertionResult::AppendMessage(testing::Message const&) in RuleCarrierTest.cpp.o
      testing::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, testing::Message const&) in libgmock.a(gmock-all.cc.o)
      testing::Message::Message(testing::Message const&) in libgmock.a(gmock-all.cc.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > testing::internal::StreamableToString<char*>(char* const&) in libgmock.a(gmock-all.cc.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > testing::internal::StreamableToString<wchar_t*>(wchar_t* const&) in libgmock.a(gmock-all.cc.o)
  "testing::UnitTest::current_test_info() const", referenced from:
      testing::Mock::RegisterUseByOnCallOrExpectCall(void const*, char const*, int) in libgmock.a(gmock-all.cc.o)
  "testing::internal::AssertHelper::operator=(testing::Message const&) const", referenced from:
      RuleCarrierTest_Initializationasdf_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolation_Test::TestBody() in RuleCarrierTest.cpp.o
      RuleCarrierTest_AddViolationWithEmptyFilePath_Test::TestBody() in RuleCarrierTest.cpp.o
      testing::internal::GoogleTestFailureReporter::ReportFailure(testing::internal::FailureReporterInterface::FailureType, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libgmock.a(gmock-all.cc.o)
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
`


It just seems like the googleTest script build a gmock lib that either simply be a bad one, or can't be linked.
