### ISSUE TITLE
Missing privacy policy

### ISSUE THREAD

**Issue by 4hopp** [oclint/oclint#524]
The link to the Privacy Policy mentioned in this document: http://oclint.org/news/2016/09/14/anonymous-analytics.html is dead.

Please provide a new Privacy Policy.

**Comment by vaibhav-shah** [comment]
+1

**Comment by ryuichis** [comment]
I am removing countly component in the coming release, so there will be no more analytics, thus, privacy policy will be no longer needed.

**Comment by ryuichis** [comment]
Countly is now removed, so no data is collected at this point. I am closing this one.
