### ISSUE TITLE
Debug OCLint in oclint-xcodedriver don't call VisitObjCMethodDecl

### ISSUE THREAD

**Issue by ZhiyongPan** [oclint/oclint#529]
### Issue Summary
I am attempting to debug Oclint rules in oclint-xcodedriver project, it calls "string name()"  but not call "VisitObjCMethodDecl(ObjCMethodDecl *decl)".

### Environment
Operation system name and version: MacOS 10.13.6
OCLint version:0.13.1
How OCLint is installed: prebuilt binary downloaded from github

### Reproduction Steps
Detailed steps to reproduce the issue.

#### Sample code

    virtual const string name() const override
    {
        return "unused local variable";
    }

    virtual int priority() const override
    {
        return 3;
    }

    virtual const string category() const override
    {
        return "unused";
    }
    
    bool VisitObjCMethodDecl(ObjCMethodDecl *decl)
    {
        printf("HAHA");
        string name = decl->getNameAsString();
        return true;
    }

Plus, there are 3 warnings:
ld: warning: directory not found for option '-L/Users/panzhiyong/Documents/OCLint2/oclint-0.13.1/build/llvm-install/lib/Debug'
ld: warning: directory not found for option '-L../build/oclint-core/lib/Debug'
ld: warning: directory not found for option '-L../build/oclint-metrics/lib/Debug'

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
