### ISSUE TITLE
How can I ignore error from DerivedData

### ISSUE THREAD

**Issue by wulei878** [oclint/oclint#533]
### Issue Summary
how can I ignore error from DerivedData, set '-e DerivedData' not work

### Environment
- Operation system name and version:macos
- OCLint version: 0.13
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
homebrew
### Reproduction Steps
Detailed steps to reproduce the issue.

oclint-json-compilation-database -e DerivedData -p shell/ -- \
-report-type html -o oclint_result.html \
-max-priority-1=100000 \
-max-priority-2=100000 \
-max-priority-3=100000

Command to run OCLint with the code above.

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

### Actual Behavior
What currently happens as a result of the reproduction steps?

### Even Better
Is your project open sourced? If yes, can you point us to your repository?
If not, is it possible to make a small project that fails the Travis CI?
If not, can you create a gist with your sample code for us?

**Comment by wulei878** [comment]
哈哈

**Comment by wulei878** [comment]
测试下

**Comment by wulei878** [comment]
1111

**Comment by kmarcell** [comment]
I would also like to know.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
