### ISSUE TITLE
LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by odiferousmint** [oclint/oclint#534]
### Issue Summary

Unable to run `oclint`.

### Environment
- Operation system name and version: Arch Linux
- LLVM version: 7.0.1
- OCLint version: 0.13.1-2
- How OCLint is installed: pacman using PKGBUILD from https://github.com/thodnev/oclint-aur

### Reproduction Steps

```
git clone https://github.com/thodnev/oclint-aur
cd oclint-aur
makepkg -i PKGBUILD
oclint
```

### Output

```
odiferousmint@arch $ oclint
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

It successfully could be compiled with this particular LLVM version, but I get the above error upon trying to run the program.

**Comment by mlq** [comment]
Hello,

The following patch should help tackle this:

```diff
diff --git a/oclint-driver/CMakeLists.txt b/oclint-driver/CMakeLists.txt
index bf6578b..0385536 100644
--- a/oclint-driver/CMakeLists.txt
+++ b/oclint-driver/CMakeLists.txt
@@ -33,6 +33,12 @@ ELSE()
         )
 ENDIF()
 
+IF(LLVM_LINK_LLVM_DYLIB)
+  set(USE_SHARED USE_SHARED)
+ENDIF()
+
+LLVM_CONFIG(oclint-${OCLINT_VERSION_RELEASE} ${USE_SHARED} ${REQ_LLVM_LIBRARIES})
+
 TARGET_LINK_LIBRARIES(oclint-${OCLINT_VERSION_RELEASE}
     OCLintDriver
     OCLintRuleSet
```
Tested with LLVM 9.0.1 and oclint 0.15.0

Best regards

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
