### ISSUE TITLE
ERROR: Compile command not found.

### ISSUE THREAD

**Issue by zakabluk** [oclint/oclint#543]
### Issue Summary
I have been run 
`oclint-json-compilation-database -v --include ../BLUs/. ./BLUs/. -- -rc LONG_LINE=250 -max-priority-1 10000 -max-priority-2 10000 -max-priority-3 10000 -report-type pmd -o sonar-reports/.-oclint.xml
`
### Environment
- Mac OS Mojave 10.14.5 
- OCLint version: 0.13
- How OCLint is installed: brew

### Reproduction Steps
I'm going to use Backelite/sonar-swift for scan swift code. And when scan tried do oclint-json-compilation-database i have got error.

### command result
--------------------------------------------------------------------
Skipping /Users/mac/sonarqueb-r/RBLU-iOS/BLUs/BLUs/.. Compile command not found.

**Comment by ryuichis** [comment]
See #547.
