### ISSUE TITLE
ERROR: Compile failed，Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by goodleixiao** [oclint/oclint#544]
### Issue Summary
ERROR: Compile failed，Undefined symbols for architecture x86_64:

### Environment
- Operation system name and version: 10.13.6
- OCLint version: 0.14
- How OCLint is installed: local build

LLVM_ROOT: ./sonarqube/oclint/build/llvm-install
-- Found LLVM LLVM_PACKAGE_VERSION: 8.0.0 - LLVM_VERSION_RELEASE: 8.0.0
-- Using LLVMConfig.cmake in: ./sonarqube/oclint/build/llvm-install/lib/cmake/llvm
-- Configuring done
-- Generating done
-- Build files have been written to: ./sonarqube/oclint/build/oclint-driver
[1/1] Linking CXX executable bin/oclint-0.14
FAILED: bin/oclint-0.14
: && ./sonarqube/oclint/build/llvm-install/bin/clang++  -O3 -DNDEBUG -std=c++11 -stdlib=libc++  -fno-rtti -Wno-c++11-extensions -fPIC -fcolor-diagnostics -fvisibility-inlines-hidden -mmacosx-version-min=10.14 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/oclint-0.14.dir/main.cpp.o CMakeFiles/oclint-0.14.dir/reporters_dlfcn_port.cpp.o CMakeFiles/oclint-0.14.dir/rules_dlfcn_port.cpp.o  -o bin/oclint-0.14 -L./sonarqube/oclint/build/llvm-install/lib  -L./sonarqube/oclint/build/oclint-core/lib -Wl,-rpath,./sonarqube/oclint/build/llvm-install/lib -Wl,-rpath,./sonarqube/oclint/build/oclint-core/lib lib/libOCLintDriver.a -lOCLintRuleSet -lOCLintCore -lclangStaticAnalyzerFrontend -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangRewriteFrontend -lclangRewrite -lclangCrossTU -lclangIndex -lclangTooling -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangASTMatchers -lclangAST -lclangLex -lclangBasic ./sonarqube/oclint/build/llvm-install/lib/libLLVMAsmParser.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMBitReader.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMInstrumentation.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMMCParser.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMOption.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMSupport.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMTransformUtils.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMAnalysis.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMProfileData.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMObject.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMBitReader.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMMCParser.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMCore.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMMC.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMBinaryFormat.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMDebugInfoCodeView.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMDebugInfoMSF.a ./sonarqube/oclint/build/llvm-install/lib/libLLVMSupport.a -lz -lcurses -lm ./sonarqube/oclint/build/llvm-install/lib/libLLVMDemangle.a && :
ld: warning: ld: warning: ld: warning: ignoring file lib/libOCLintDriver.a, file was built for archive which is not the architecture being linked (x86_64): lib/libOCLintDriver.aignoring file ./sonarqube/oclint/build/oclint-core/lib/libOCLintRuleSet.a, file was built for archive which is not the architecture being linked (x86_64): ./sonarqube/oclint/build/oclint-core/lib/libOCLintRuleSet.aignoring file ./sonarqube/oclint/build/oclint-core/lib/libOCLintCore.a, file was built for archive which is not the architecture being linked (x86_64): ./sonarqube/oclint/build/oclint-core/lib/libOCLintCore.a

Undefined symbols for architecture x86_64:
  "_OCLintOptionCategory", referenced from:
      _main in main.cpp.o
  "oclint::RawResults::RawResults(oclint::ResultCollector const&)", referenced from:
      getResults() in main.cpp.o
  "oclint::UniqueResults::UniqueResults(oclint::ResultCollector const&)", referenced from:
      getResults() in main.cpp.o
  "oclint::ResultCollector::getInstance()", referenced from:
      getResults() in main.cpp.o
  "oclint::GenericException::GenericException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      outStream() in main.cpp.o
      loadReporter() in reporters_dlfcn_port.cpp.o
      dynamicLoadRules(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in rules_dlfcn_port.cpp.o
  "oclint::RulesetBasedAnalyzer::RulesetBasedAnalyzer(std::__1::vector<oclint::RuleBase*, std::__1::allocator<oclint::RuleBase*> >)", referenced from:
      _main in main.cpp.o
  "oclint::Driver::run(clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, oclint::Analyzer&)", referenced from:
      _main in main.cpp.o
  "oclint::option::outputPath()", referenced from:
      outStream() in main.cpp.o
  "oclint::option::reportType()", referenced from:
      loadReporter() in reporters_dlfcn_port.cpp.o
  "oclint::option::reporterPath()", referenced from:
      loadReporter() in reporters_dlfcn_port.cpp.o
  "oclint::option::hasOutputPath()", referenced from:
      outStream() in main.cpp.o
      disposeOutStream(std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in main.cpp.o
      _main in main.cpp.o
  "oclint::option::rulesetFilter()", referenced from:
      listRules() in main.cpp.o
      _main in main.cpp.o
  "oclint::option::showEnabledRules()", referenced from:
      _main in main.cpp.o
  "oclint::option::allowDuplicatedViolations()", referenced from:
      getResults() in main.cpp.o
  "oclint::option::maxP1()", referenced from:
      numberOfViolationsExceedThreshold(oclint::Results*) in main.cpp.o
      printViolationsExceedThresholdError(oclint::Results const*) in main.cpp.o
      handleExit(oclint::Results*) in main.cpp.o
      _main in main.cpp.o
  "oclint::option::maxP2()", referenced from:
      numberOfViolationsExceedThreshold(oclint::Results*) in main.cpp.o
      printViolationsExceedThresholdError(oclint::Results const*) in main.cpp.o
      handleExit(oclint::Results*) in main.cpp.o
      _main in main.cpp.o
  "oclint::option::maxP3()", referenced from:
      numberOfViolationsExceedThreshold(oclint::Results*) in main.cpp.o
      printViolationsExceedThresholdError(oclint::Results const*) in main.cpp.o
      handleExit(oclint::Results*) in main.cpp.o
      _main in main.cpp.o
  "oclint::option::process(char const*)", referenced from:
      _main in main.cpp.o
  "oclint::option::rulesPath()", referenced from:
      consumeArgRulesPath() in main.cpp.o
  "oclint::RuleSet::numberOfRules()", referenced from:
      prepare() in main.cpp.o
  "oclint::Version::identifier()", referenced from:
      oclintVersionPrinter(llvm::raw_ostream&) in main.cpp.o
  "oclint::RulesetFilter::filteredRules() const", referenced from:
      _main in main.cpp.o
  "oclint::RulesetFilter::filteredRuleNames() const", referenced from:
      listRules() in main.cpp.o
  "vtable for oclint::GenericException", referenced from:
      oclint::GenericException::~GenericException() in main.cpp.o
      oclint::GenericException::~GenericException() in reporters_dlfcn_port.cpp.o
      oclint::GenericException::~GenericException() in rules_dlfcn_port.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for oclint::RulesetBasedAnalyzer", referenced from:
      _main in main.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by ryuichis** [comment]
Can you try the 0.15 release and see if you see the same?
