### ISSUE TITLE
./test failed, 'clang/AST/AST.h' file not found

### ISSUE THREAD

**Issue by samuelchen2015** [oclint/oclint#545]
### Issue Summary
I want to rebuild oclint, 
- first build clang/llvm with "./clang build -release", it is successful installed in folder 'build/llvm-install' 
- second build and test oclint with "./test core", it fails with following
```
/Users/samuelchen/git/oclint/oclint-core/test/RawResultsTest.cpp:1:10: fatal error: 'gtest/gtest.h' file not found
#include <gtest/gtest.h>
         ^~~~~~~~~~~~~~~
1 error generated.
[6/13] Building CXX object CMakeFiles/oclint_core.dir/lib/RuleCarrier.cpp.o
FAILED: CMakeFiles/oclint_core.dir/lib/RuleCarrier.cpp.o 
/Users/samuelchen/git/oclint/build/llvm-install/bin/clang++   -I/Users/samuelchen/git/oclint/oclint-core/include -I/Users/samuelchen/git/oclint/oclint-core/include/oclint -std=gnu++14 -MD -MT CMakeFiles/oclint_core.dir/lib/RuleCarrier.cpp.o -MF CMakeFiles/oclint_core.dir/lib/RuleCarrier.cpp.o.d -o CMakeFiles/oclint_core.dir/lib/RuleCarrier.cpp.o -c /Users/samuelchen/git/oclint/oclint-core/lib/RuleCarrier.cpp
/Users/samuelchen/git/oclint/oclint-core/lib/RuleCarrier.cpp:3:10: fatal error: 'clang/AST/AST.h' file not found
#include <clang/AST/AST.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

### Environment
- Operation system name and version: Mac OS10.13.3
- OCLint version: 0.13
- How OCLint is installed: local build

**Comment by ryuichis** [comment]
If you just want to rebuid oclint, please follow this instructions http://docs.oclint.org/en/stable/intro/build.html

If you also want to run the tests and perhaps adding new features, check out this one http://docs.oclint.org/en/stable/devel/compiletest.html. Please be advised that `countly` has been removed from the project, thus you can ignore the related section.
