### ISSUE TITLE
Issue with Xcode 11: many "error generated" and oclint.xml not generated

### ISSUE THREAD

**Issue by egr-ext** [oclint/oclint#547]
### Issue Summary
After I upgraded to Xcode 11, oclint is crashing:
- Many warning with "N error generated"
- crash on "oclint: error: cannot open report output file /Users/***/sonar-reports/oclint.xml"

The report is not generated.

### Environment
- Operation system name and version: 
macOS Mojave 10.14.6 and Xcode 11.0

- OCLint version: 
LLVM (http://llvm.org/):
  LLVM version 5.0.1
  Optimized build.
  Default target: x86_64-apple-darwin18.7.0
  Host CPU: skylake
OCLint (http://oclint.org/):
  OCLint version 0.13.1.
  Built Feb  6 2018 (09:25:36).

- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others? 
Manually installed after being downloaded from github (also tested with homebrew installation too)

### Reproduction Steps
Launch following command line:

`$ oclint -report-type=pmd -o=sonar-reports/oclint.xml -rc=LONG_LINE=200 -rc=LONG_METHOD=200 -max-priority-1=9999 -max-priority-2=9999 -max-priority-3=9999 -allow-duplicated-violations -p sonar-reports -extra-arg -Wno-everything "* all source code files"`

**Comment by deimian86** [comment]
Same here since XCode 11 update.

**Comment by skywancen** [comment]
https://github.com/oclint/oclint/pull/548

**Comment by skywancen** [comment]
You can upgrade llvm9.0 to oclint, I just resolved this issue.

**Comment by egr-ext** [comment]
Hi Skywancen,

Thanks a lot !

So I checkout your code and I have to build oclint ? I tryed to build oclint but it seems to be very difficult and takes a long time.

What script or command line I have to perform exactly ?

Regards

**Comment by skywancen** [comment]
You should do this
1. $ cd oclint-scripts
2. $ ./make
this should be a long time about an hour.
if execute successfully, you can find "oclint-release" folder in `build` folder

**Comment by egr-ext** [comment]
Hi, 

I cloned your repo then I built oclint. 

It generated a release 0.14. It  is strange or no ?

**Comment by egr-ext** [comment]
> You should do this
> 
> 1. $ cd oclint-scripts
> 2. $ ./make
>    this should be a long time about an hour.
>    if execute successfully, you can find "oclint-release" folder in `build` folder
> 
> If you want to use build cache, you can find `oclint/oclint-scripts/ci` , delete the "rm_f" lines corresponding.

Hi,

I cloned your repo then I built oclint.

It generated a release 0.14. It is strange or no ?

**Comment by ryuichis** [comment]
I just made the 0.15 release, and that would resolve the Xcode incompatibility issue.

**Comment by egr-ext** [comment]
Hi ryuichis,

I dowloaded the zip of 0.15 release, . I build it with ./make but the binairy says 0.14 ?

**Comment by ryuichis** [comment]
@egr-ext I updated the tag just now, would you please try it again?

**Comment by egr-ext** [comment]
OK I test, have you updated also the symlink oclint ~> oclint-0.15 ?

**Comment by egr-ext** [comment]
So I built this morning your last zip with sources with ./make
- I generated a binairy file named: oclint-0.14
- ./oclint-0.14 -version returns 0.15 (see screenshot)
- The symlink points to a file that does not exists (oclint-0.15)

My guess is the oclint-0.14 is wrong it should be named oclint-0.15.

Here is a screenshot of my build directory:

![oclint](https://user-images.githubusercontent.com/28352240/67673298-0c590e00-f97a-11e9-93da-8b78c52e7b22.png)

**Comment by skywancen** [comment]
Now, you can use  https://github.com/oclint/oclint, checkout the branch to master, then build with  ./make, the version number will be 0.15!

**Comment by ryuichis** [comment]
@egr-ext Thank you for your patience and letting us know the issue. I have identified one more piece that needs to be updated. Could you please give it another try, and let us know if it works for you this time?

**Comment by egr-ext** [comment]
OK I build it again.

**Comment by egr-ext** [comment]
I confirm it is fixed

**Comment by ryuichis** [comment]
@egr-ext that's very good to know. Thanks again for testing this along with us.

**Comment by LionWY** [comment]
> Now, you can use https://github.com/oclint/oclint, checkout the branch to master, then build with ./make, the version number will be 0.15!

can you upload brew, so we can brew install oclint, to get the version 0.15,  ./make takes long long long time, and often error, I am almost crazy, please help me

**Comment by LionWY** [comment]
> I confirm it is fixed

@egr-ext egr-ext can you upload brew, so we can brew install oclint, to get the version 0.15, ./make takes long long long time, and often error, I am almost crazy, please help me

**Comment by hafiz-mohsin-confiz** [comment]
@egr-ext Please upload oclint0.15 to brew so that we can incorporate the latest changes other its give following warning when you run a command on terminal.
brew upgrade oclint
Warning: oclint/formulae/oclint 0.13 already installed
Thanks,

**Comment by hafiz-mohsin-confiz** [comment]
any update on this?

**Comment by cocoay** [comment]
https://github.com/cocoay/oclint-releases

**Comment by hafiz-mohsin-confiz** [comment]
@cocoay 
Thanks for sharing the Oclint0.15 binary file.

**Comment by ShenYj** [comment]
```
╰─ oclint --version                                                                      ─╯
OCLint (http://oclint.org/):
  OCLint version 0.15.
  Built Sep  2 2020 (01:08:00).
```

without llvm version, is that right?

**Comment by ShenYj** [comment]
It's work! thks
