### ISSUE TITLE
can't install on current mac version

### ISSUE THREAD

**Issue by fetzig** [oclint/oclint#552]
### Issue Summary

unable to install from the repo or via homebrew.

```
OSError: [Errno 2] No such file or directory:
'...CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/include/c++'
```
Details see Reproduction Steps.

### Environment
- Operation system name and version: macOS 10.15.1 (19B88),
- OCLint version: --HEAD
- How OCLint is installed: local build and homebrew install

#### Additional Environment Info
Xcode 11.2
Build version 11B52

gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```
$ ls /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
ls: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1: No such file or directory
```

llvm-gcc -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

clang -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### Reproduction Steps

```
$ ./make
...
-- Installing: /Users/xxx/src/oclint/build/llvm-install/lib/cmake/llvm/./CheckLinkerFlag.cmake
Traceback (most recent call last):
  File "clang", line 131, in <module>
    copy_cpp_headers()
  File "clang", line 64, in copy_cpp_headers
    path.cp_r(xcode_cpp_headers, cpp_dir)
  File "/Users/xxx/src/oclint/oclint-scripts/oclintscripts/path.py", line 97, in cp_r
    shutil.copytree(src_path, dst_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 194, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/include/c++'
$ _
```

```
$ brew install oclint --HEAD
==> Installing oclint from oclint/formulae
==> Cloning https://github.com/oclint/oclint.git
Updating /Users/xxx/Library/Caches/Homebrew/oclint--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7c38909 Merge pull request #551 from ryuichis/release-0.15
Warning: tried to install empty array to /usr/local/Cellar/oclint/HEAD-7c38909/include
Error: An exception occurred within a child process:
  NoMethodError: undefined method `install' for "/usr/local/Cellar/oclint/HEAD-7c38909/include/c++":String
$ _
```

**Comment by ryuichis** [comment]
I am not sure if it's a change in mac Catalina, which I haven't upgraded to yet. But my toolchain dir is `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin` while yours is `/Library/Developer/CommandLineTools/usr/bin`. Besides, you don't have C++ headers under your toolchain folder.

**Comment by fetzig** [comment]
yeah. but it's a fresh macOS and xCode installation.

**Comment by ryuichis** [comment]
Right. If you can help us understand the incompatibility, that will be appreciated. Currently I don't have a Catalina to replicate your issue.

**Comment by ryuichis** [comment]
Maybe you can try something similar to this? https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15

**Comment by fetzig** [comment]
....fresh + brew install cmake

so, manual build takes way to long. tried brew install oclint. works like a charm. thx.

```
export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
```

**Comment by fetzig** [comment]
@ryuichis thx for the support.

**Comment by ryuichis** [comment]
I still don't have the luxury to run Catalina, but I gave it a try with GitHub Actions, whose [mac infrastructure runs on Catalina.](https://github.blog/changelog/2019-11-06-github-actions-macos-virtual-environment-updated-to-catalina/) It built smoothly for me https://github.com/ryuichis/oclint-make-gh-actions/runs/342071088. The build script can be found in the same repo as well: https://github.com/ryuichis/oclint-make-gh-actions/blob/master/run.sh
