### ISSUE TITLE
oclint-0.15 make fail,It's stuck

### ISSUE THREAD

**Issue by linzhesheng** [oclint/oclint#553]
![image](https://user-images.githubusercontent.com/23381925/69701062-0005d380-1127-11ea-8056-88a0046665a0.png)

**Comment by boduoduo** [comment]
+1

**Comment by Max-calibur** [comment]
+1

**Comment by ryuichis** [comment]
Depends on your network, it may take a few minutes to download the llvm/clang source code. We recently made the changes to stop dumping all of the svn co outputs to console, so it is likely not stuck, but just busy checking out files. It usually take about 3-5 minutes for me to download the files. In case you want to make sure the script is still doing things, please take a look at this commit https://github.com/oclint/oclint/commit/d76e6044021839a4150ffb9813853c9949ba0d77, and remove the `-q` locally, and run `make` again.

**Comment by linzhesheng** [comment]
I see. Thank you for your help

**Comment by linzhesheng** [comment]
> Depends on your network, it may take a few minutes to download the llvm/clang source code. We recently made the changes to stop dumping all of the svn co outputs to console, so it is likely not stuck, but just busy checking out files. It usually take about 3-5 minutes for me to download the files. In case you want to make sure the script is still doing things, please take a look at this commit [d76e604](https://github.com/oclint/oclint/commit/d76e6044021839a4150ffb9813853c9949ba0d77), and remove the `-q` locally, and run `make` again.

I see. Thank you.

**Comment by LionWY** [comment]
![image](https://user-images.githubusercontent.com/5524753/71391594-c948ad80-263f-11ea-9bee-91e0cb5c1db5.png)

**Comment by LionWY** [comment]
@linzhesheng Have you make it  completed ?
