### ISSUE TITLE
No such file or directory: '/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/include/c++'

### ISSUE THREAD

**Issue by FlyingNoob** [oclint/oclint#555]
### Issue Summary
oclint 0.15 . build ./make error
### Environment
- Operation system name and version: 10.15.2
- OCLint version: 0.15
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
github

**Comment by ryuichis** [comment]
Duplicate of #552
