### ISSUE TITLE
Exit status of command 'oclint-json-compilation-database' was 245 instead of 0.

### ISSUE THREAD

**Issue by smarciel** [oclint/oclint#557]
### Issue Summary
After I upgraded to Xcode 11, oclint is crashing and the report is not generated. 

Exit status of command 'oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -- -report-type pmd -o ../reports/2045/oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000' was 245 instead of 0.

### Environment
- Operation system name and version: 
macOS Catalina 10.15.2

- OCLint version: 
OCLint (http://oclint.org/):
OCLint version 0.15.
Built Jan 14 2020 (17:06:50).

- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others? 
Manually installed after being downloaded from github.

### Reproduction Steps
Detailed steps to reproduce the issue.

I'm running the following commands:

xcodebuild -scheme *scheme-name* -workspace ../Workespace.xcworkspace clean

xcodebuild -scheme *scheme-name* -workspace ../Workespace.xcworkspace CLANG_ENABLE_MODULE_DEBUGGING=NO CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO COMPILER_INDEX_STORE_ENABLE=NO | tee xcodebuild.log | xcpretty -r json-compilation-database --output compile_commands.json

oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -- -report-type pmd -o ../reports/2045/oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000

Instead of *scheme-name* I'm correctly putting the name of the scheme.

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Comment by smarciel** [comment]
Good morning,

I'm still having this issue. I have updated the oclint to the last version (20.11) and now I have macOS Big Sur 11.1 (20C69), but the error is the same:

`[10:09:04]: Exit status of command 'oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -- -report-type pmd -o ../sonar-reports/oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000' was 245 instead of 0.`
