### ISSUE TITLE
Linting implicit switch fallthrough

### ISSUE THREAD

**Issue by michaeleisel** [oclint/oclint#562]
### Issue Summary
Accidentally forgetting to add a `break;` at the end of a switch case is a common error. It'd be great to have a lint for this. There's `-Wimplicit-fallthrough` in clang, but it doesn't check Objective-C code, just C++.

**Comment by ryuichis** [comment]
We actually have a rule for this https://github.com/oclint/oclint/blob/master/oclint-rules/rules/convention/MissingBreakInSwitchStatementRule.cpp. Do you have an example that it is not caught for this rule?

**Comment by michaeleisel** [comment]
ah nice
