### ISSUE TITLE
IOError: [Errno 2]

### ISSUE THREAD

**Issue by SMG-IOS6Team** [oclint/oclint#563]
### Issue Summary

IOError: [Errno 2] No such file or directory: '/Users/zenggp/Documents/\xe5\xb7\xa5\xe4\xbd\x9c/code/ThirdPart/oclint-master/oclint-scripts/../llvm/tools/clang/include/clang/Basic/StmtNodes.td'

### Environment
- Operation system name and version:
- OCLint version: 0.15
downloaded from github。

### Reproduction Steps
1.downloaded from github。
2.run  ./make
3. oclint-scripts/scaffoldRule myDemoRule -t ASTVisitor 
error：
IOError: [Errno 2] No such file or directory: '/Users/zenggp/Documents/\xe5\xb7\xa5\xe4\xbd\x9c/code/ThirdPart/oclint-master/oclint-scripts/../llvm/tools/clang/include/clang/Basic/StmtNodes.td'

#### Sample code

```
C
C++
Objective-C
```

Command to run OCLint with the code above.

### Expected Behavior
create success。

![C20EA0BC-C32D-4DA3-BBB3-BA5B5189335C](https://user-images.githubusercontent.com/28804080/79292718-6045b800-7f04-11ea-8ae6-a4921c2bdf2e.png)

**Comment by lpfRoc** [comment]
+！

**Comment by xywwjf123** [comment]
+1

**Comment by xywwjf123** [comment]
> +1

请问您解决了么

**Comment by lpfRoc** [comment]
> > +1
> 
> 请问您解决了么

手动编辑XXXRule.cpp和CMakeLists.txt 可往下进行

**Comment by momoliyao** [comment]
+1
