### ISSUE TITLE
oclint getting stuck, never terminating

### ISSUE THREAD

**Issue by rahulnjs** [oclint/oclint#576]
### Issue Summary
After printing the analysis oclint is not terminating. Refer to gif added below. Tested it in 3 different environments but no luck. 

### Environment
- Operation system name and version: Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

- OCLint version:
LLVM (http://llvm.org/):
  LLVM version 5.0.0svn-r313529
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell

OCLint (http://oclint.org/):
  OCLint version 0.13.
  Built Sep 18 2017 (15:44:13).

- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
prebuilt download

### Reproduction Steps
Detailed steps to reproduce the issue.

#### Sample code
```cpp
#include<bits/stdc++.h>
using namespace std; int main(){
    int n;
    cin>>n;
    int arr[n];
    for(int i=0;i<n;i++){
        cin>>arr[i];
    }
    if(n==1){
        cout<<0<<endl;
    }else{
    queue<int>Q;
    int jump=0,cross=0;
    Q.push(0);
    while(!Q.empty()){
        int itr=Q.size();
        for(int i=0;i<itr;i++){
            int top=Q.front();
            Q.pop();
            for(int j=arr[top];j>0;j--){
                if(top+j>=n-1){
                    cross=1;
                    break;
                }
                Q.push(top+j);
            }
            if(cross==1){break;}
        }
        jump++;
        if(cross==1){break;}

    }
    if(cross==1){
    cout<<jump<<endl;
    }else{
        cout<< -1<<endl;
    }
    }
    return 0;
}
```

Command to run OCLint with the code above.
 ./oclint /root/test.cpp

### Expected Behavior
oclint should terminate 

### Actual Behavior
What currently happens as a result of the reproduction steps?

### Even Better
Is your project open sourced? If yes, can you point us to your repository?
If not, is it possible to make a small project that fails the Travis CI?
If not, can you create a gist with your sample code for us?

![Stopped after 30sec](https://i.imgur.com/MekgFjr.gif "Terminating Forcibly")

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Comment by zld** [comment]
add `-no-analytics` option works for me. 
Maybe stuck by uploading data due to network condition.

https://oclint-docs.readthedocs.io/en/stable/manual/oclint.html#other-options

**Comment by ryuichis** [comment]
@zld Analytics feature has been removed from the codebase for a while. If you build against the latest release, you shouldn't need to worry about the analytics flag.
