### ISSUE TITLE
Building 20.10 has binary is named as oclint-0.15

### ISSUE THREAD

**Issue by kmarcell** [oclint/oclint#583]
### Issue Summary
Release 20.10 has binary is named as oclint-0.15

### Environment
- macOS Catalina 10.15.7 (19H2)
- OCLint version: 20.10
- How OCLint is installed: locally buildt from github release .zip

### Reproduction Steps
- Install cmake
- Install ninja
- Run ./make
- Binary is generated in build/oclint-release/
- Symlink build/oclint-release/bin/oclint points to oclint-20.10
- Binary is named oclint-0.15

### Expected Behavior
Built binary is named oclint-20.10

### Actual Behavior
Built binary is named oclint-0.15

**Comment by ryuichis** [comment]
Thanks for pointing this out. I fixed this in the master branch, and the 20.11 release will have it addressed. (I am mainly waiting for Tuesday's Apple event and see if there are any implications before I tag it.)
