### ISSUE TITLE
Exit status of command 'oclint-json-compilation-database' was 245 instead of 0.

### ISSUE THREAD

**Issue by smarciel** [oclint/oclint#599]
### Issue Summary
After I upgraded to Xcode 11, oclint is crashing and the report is not generated. It also happens with Xcode 12. 

### Environment
Operation system name and version:
macOS Big Sur 11.1

OCLint version:
OCLint (http://oclint.org/):
  OCLint version 20.11.
  Built Dec 10 2020 (14:31:08).

How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
Manually installed after being downloaded from github.

### Reproduction Steps
xcodebuild -scheme scheme-name -workspace ../Workespace.xcworkspace clean

xcodebuild -scheme scheme-name -workspace ../Workespace.xcworkspace CLANG_ENABLE_MODULE_DEBUGGING=NO CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO COMPILER_INDEX_STORE_ENABLE=NO | tee xcodebuild.log | xcpretty -r json-compilation-database --output compile_commands.json

oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -- -report-type pmd -o ../reports/2045/oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by smarciel** [comment]
Good morning,

I have used the template partially. Please, tell me if you need more information about this issue.

Thanks a lot.

**Comment by ryuichis** [comment]
With the information provided, it's hard to understand what's going on. One thing I could suggest is to move the environment variable overrides to the front of the line, as appending them has no effect on the `xcodebuild` command you were invoking.

**Comment by smarciel** [comment]
Good morning,
I have changed the environment variables as you told me, and now I have a different error:

`sh("xcodebuild -scheme XXXX -workspace ../XXXX.xcworkspace clean")
  sh("CLANG_ENABLE_MODULE_DEBUGGING=NO CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO COMPILER_INDEX_STORE_ENABLE=NO xcodebuild -scheme XXXX -workspace ../XXXX.xcworkspace | tee xcodebuild.log | xcpretty -r json-compilation-database --output compile_commands.json")
  sh("oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -- -report-type pmd -o ." + ENV["REPORTS_DIRECTORY"] + "oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000")
  sh("rm compile_commands.json")
`
The new error:
[08:15:05]: Exit status of command 'oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -- -report-type pmd -o ../sonar-reports/oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000' was 3 instead of 0.

oclint: error: compilation contains multiple jobs:
 "/Users/smarciel/Downloads/oclint-20.11/build/oclint-release/bin/oclint-20.11" "-cc1" "-triple" "thumbv7-apple-ios10.0.0" "-Wundef-prefix=TARGET_OS_" "-Werror=undef-prefix" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "DataStore" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=all" "-fno-rounding-math" "-faligned-alloc-unavailable" "-target-sdk-version=14.3" "-fcompatibility-qualified-id-block-type-checking" "-target-cpu" "generic" "-target-feature" "+soft-float-abi" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-fallow-half-arguments-and-returns" "-debug-info-kind=standalone" "-dwarf-version=4" "-debugger-tuning=lldb" "-target-linker-version" "609" "-fprofile-instrument=clang" "-fcoverage-mapping" "-resource-dir" "/Users/smarciel/Downloads/oclint-20.11/build/oclint-release/lib/clang/11.0.0" "-dependency-file" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/Objects-normal/armv7/NSString+isNumeric.d" "-MT" "dependencies" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk" "-iquote" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-generated-files.hmap" "-ivfsoverlay" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/all-product-headers.yaml" "-iquote" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-project-headers.hmap" "-D" "DEBUG=1" "-D" "COCOAPODS=1" "-D" "OBJC_OLD_DISPATCH_PROTOTYPES=0" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-own-target-headers.hmap" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-all-non-framework-target-headers.hmap" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Products/Debug-iphoneos/include" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/AFNetworking" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/CocoaSecurity" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/DCKeyValueObjectMapping" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/AFNetworking" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/Realm" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/DCKeyValueObjectMapping" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/DerivedSources-normal/armv7" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/DerivedSources/armv7" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/DerivedSources" "-F/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Products/Debug-iphoneos" "-D" "__OCLINT__" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/usr/local/include" "-internal-isystem" "/Users/smarciel/Downloads/oclint-20.11/build/oclint-release/lib/clang/11.0.0/include" "-internal-externc-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/usr/include" "-O0" "-Wnon-modular-include-in-framework-module" "-Werror=non-modular-include-in-framework-module" "-Wno-trigraphs" "-Wno-missing-field-initializers" "-Wno-missing-prototypes" "-Werror=return-type" "-Wdocumentation" "-Wunreachable-code" "-Wno-implicit-atomic-properties" "-Werror=deprecated-objc-isa-usage" "-Wno-objc-interface-ivars" "-Werror=objc-root-class" "-Wno-arc-repeated-use-of-weak" "-Wimplicit-retain-self" "-Wduplicate-method-match" "-Wno-missing-braces" "-Wparentheses" "-Wswitch" "-Wunused-function" "-Wno-unused-label" "-Wno-unused-parameter" "-Wunused-variable" "-Wunused-value" "-Wempty-body" "-Wuninitialized" "-Wconditional-uninitialized" "-Wno-unknown-pragmas" "-Wno-shadow" "-Wno-four-char-constants" "-Wno-conversion" "-Wconstant-conversion" "-Wint-conversion" "-Wbool-conversion" "-Wenum-conversion" "-Wno-float-conversion" "-Wnon-literal-null-conversion" "-Wobjc-literal-conversion" "-Wshorten-64-to-32" "-Wpointer-sign" "-Wno-newline-eof" "-Wno-selector" "-Wno-strict-selector-match" "-Wundeclared-selector" "-Wdeprecated-implementations" "-Wprotocol" "-Wdeprecated-declarations" "-Wno-sign-conversion" "-Winfinite-recursion" "-Wcomma" "-Wblock-capture-autoreleasing" "-Wstrict-prototypes" "-Wno-semicolon-before-method-body" "-Wunguarded-availability" "-std=gnu11" "-fdebug-compilation-dir" "/" "-ferror-limit" "19" "-fmacro-backtrace-limit" "0" "-stack-protector" "1" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fmodules" "-fimplicit-module-maps" "-fmodules-cache-path=/Users/smarciel/Library/Developer/Xcode/DerivedData/ModuleCache.noindex" "-fmodule-name=ApplePaySDK" "-fmodules-prune-interval=86400" "-fmodules-prune-after=345600" "-fbuild-session-timestamp=1611558898852754973" "-fmodules-validate-once-per-build-session" "-fmodules-validate-system-headers" "-fobjc-runtime=ios-10.0.0" "-fobjc-arc" "-fobjc-weak" "-fobjc-exceptions" "-fexceptions" "-fsjlj-exceptions" "-fpascal-strings" "-fmax-type-align=16" "-fdiagnostics-show-note-include-stack" "-serialize-diagnostic-file" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/Objects-normal/armv7/NSString+isNumeric.dia" "-x" "objective-c" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Index/DataStore";  "/Users/smarciel/Downloads/oclint-20.11/build/oclint-release/bin/oclint-20.11" "-cc1" "-triple" "thumbv7-apple-ios10.0.0" "-Wundef-prefix=TARGET_OS_" "-Werror=undef-prefix" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "NSString+isNumeric.m" "-mrelocation-model" "pic" "-pic-level" "2" "-mframe-pointer=all" "-fno-rounding-math" "-faligned-alloc-unavailable" "-target-sdk-version=14.3" "-fcompatibility-qualified-id-block-type-checking" "-target-cpu" "generic" "-target-feature" "+soft-float-abi" "-target-abi" "apcs-gnu" "-mfloat-abi" "soft" "-fallow-half-arguments-and-returns" "-debug-info-kind=standalone" "-dwarf-version=4" "-debugger-tuning=lldb" "-target-linker-version" "609" "-fprofile-instrument=clang" "-fcoverage-mapping" "-resource-dir" "/Users/smarciel/Downloads/oclint-20.11/build/oclint-release/lib/clang/11.0.0" "-dependency-file" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/Objects-normal/armv7/NSString+isNumeric.d" "-MT" "dependencies" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk" "-iquote" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-generated-files.hmap" "-ivfsoverlay" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/all-product-headers.yaml" "-iquote" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-project-headers.hmap" "-D" "DEBUG=1" "-D" "COCOAPODS=1" "-D" "OBJC_OLD_DISPATCH_PROTOTYPES=0" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-own-target-headers.hmap" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/ApplePaySDK-all-non-framework-target-headers.hmap" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Products/Debug-iphoneos/include" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/AFNetworking" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/CocoaSecurity" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/DCKeyValueObjectMapping" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/AFNetworking" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/Realm" "-I" "/Users/smarciel/apple-pay-sdk/Pods/Headers/Public/DCKeyValueObjectMapping" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/DerivedSources-normal/armv7" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/DerivedSources/armv7" "-I" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/DerivedSources" "-F/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Products/Debug-iphoneos" "-D" "__OCLINT__" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/usr/local/include" "-internal-isystem" "/Users/smarciel/Downloads/oclint-20.11/build/oclint-release/lib/clang/11.0.0/include" "-internal-externc-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/usr/include" "-O0" "-Wnon-modular-include-in-framework-module" "-Werror=non-modular-include-in-framework-module" "-Wno-trigraphs" "-Wno-missing-field-initializers" "-Wno-missing-prototypes" "-Werror=return-type" "-Wdocumentation" "-Wunreachable-code" "-Wno-implicit-atomic-properties" "-Werror=deprecated-objc-isa-usage" "-Wno-objc-interface-ivars" "-Werror=objc-root-class" "-Wno-arc-repeated-use-of-weak" "-Wimplicit-retain-self" "-Wduplicate-method-match" "-Wno-missing-braces" "-Wparentheses" "-Wswitch" "-Wunused-function" "-Wno-unused-label" "-Wno-unused-parameter" "-Wunused-variable" "-Wunused-value" "-Wempty-body" "-Wuninitialized" "-Wconditional-uninitialized" "-Wno-unknown-pragmas" "-Wno-shadow" "-Wno-four-char-constants" "-Wno-conversion" "-Wconstant-conversion" "-Wint-conversion" "-Wbool-conversion" "-Wenum-conversion" "-Wno-float-conversion" "-Wnon-literal-null-conversion" "-Wobjc-literal-conversion" "-Wshorten-64-to-32" "-Wpointer-sign" "-Wno-newline-eof" "-Wno-selector" "-Wno-strict-selector-match" "-Wundeclared-selector" "-Wdeprecated-implementations" "-Wprotocol" "-Wdeprecated-declarations" "-Wno-sign-conversion" "-Winfinite-recursion" "-Wcomma" "-Wblock-capture-autoreleasing" "-Wstrict-prototypes" "-Wno-semicolon-before-method-body" "-Wunguarded-availability" "-std=gnu11" "-fdebug-compilation-dir" "/" "-ferror-limit" "19" "-fmacro-backtrace-limit" "0" "-stack-protector" "1" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fmodules" "-fimplicit-module-maps" "-fmodules-cache-path=/Users/smarciel/Library/Developer/Xcode/DerivedData/ModuleCache.noindex" "-fmodule-name=ApplePaySDK" "-fmodules-prune-interval=86400" "-fmodules-prune-after=345600" "-fbuild-session-timestamp=1611558898852754973" "-fmodules-validate-once-per-build-session" "-fmodules-validate-system-headers" "-fobjc-runtime=ios-10.0.0" "-fobjc-arc" "-fobjc-weak" "-fobjc-exceptions" "-fexceptions" "-fsjlj-exceptions" "-fpascal-strings" "-fmax-type-align=16" "-fdiagnostics-show-note-include-stack" "-serialize-diagnostic-file" "/Users/smarciel/Library/Developer/Xcode/DerivedData/ApplePaySDK-cyvlglhlwogbpgetyylzbkbjxptl/Build/Intermediates.noindex/ApplePaySDK.build/Debug-iphoneos/ApplePaySDK.build/Objects-normal/armv7/NSString+isNumeric.dia" "-x" "objective-c" "/Users/smarciel/apple-pay-sdk/ApplePaySDK/Utils/NSString+isNumeric.m";

As you can see, I have the the COMPILER_INDEX_STORE_ENABLE variable set to NO and I exclude de Pods folder.

Thanks for the help.

**Comment by smarciel** [comment]
Hello,
Any updates on this?
Thanks a lot.

**Comment by ryuichis** [comment]
Hi @smarciel, with this sample input, oclint reports the error properly. If you search semi-colons, you see there are two of them, each locates at the end of a job that is feed to oclint. Will you get the same error outside of sonar environment?

**Comment by smarciel** [comment]
Hi @ryuichis,
I don't understand your approach. I'm l running the oclint command like is explained in the doc: https://docs.oclint.org/en/stable/manual/oclint-json-compilation-database.html integrated in a fastlane lane, but I run it like a normal command. 

Which is the origin of the error "Exit status of command was 3 instead of 0."?

Thanks a lot for your help.

**Comment by ryuichis** [comment]
I saw sonar in your output, so I wonder if you can run oclint without sonar nor fast lane. I hope to filter out that the environment itself doesn't introduce anything to the problem you are facing.

**Comment by smarciel** [comment]
Hi @ryuichis,
I have run the command outside my fastlane configuration and I don't get any error, but the xml file with the result is not generated.
This is the command:
`oclint-json-compilation-database -v -e Pods -e build -e Internal -e ThirdParties -p . --debug -- -report-type pmd -o oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000`

It show me the following output in the console:
`------------------------------ OCLint ------------------------------
/usr/local/bin/oclint -p . -report-type pmd -o oclint.xml -max-priority-1=100 -max-priority-2=3000 -max-priority-3=5000 -debug /Users/smarciel/apple-pay-sdk/ApplePaySDK/Security/TripleDES.m /Users/smarciel/xxxx/xxxx/ModeloDatos/DatosAddPaymentPassRequest.m /Users/smarciel/xxxx/xxxx/Reachability/Reachability.m /Users/smarciel/xxxx/xxxx/Utils/NSString+isNumeric.m /Users/smarciel/xxxx/xxxx/Sender/WebviewSender.m /Users/smarciel/xxxx/xxxx/Sender/Sender.m /Users/smarciel/xxxx/xxxx/RequestManager.m /Users/smarciel/xxxx/xxxx/Security/RSA.m /Users/smarciel/xxxx/xxxx/ModeloDatos/PaymentPassData.m /Users/smarciel/xxxx/xxxx/ModeloDatos/IdenSello.m /Users/smarciel/xxxx/xxxx/ModeloDatos/DatosPaymentPass.m /Users/smarciel/xxxx/xxxx/ModeloDatos/DatosOTPRequest.m /Users/smarciel/xxxx/xxxx/ModeloDatos/DatosActivationPass.m /Users/smarciel/xxxx/xxxx/Sender/BareSender.m /Users/smarciel/xxxx/xxxx/ApplePayManager.m /Users/smarciel/xxxx/xxxx/LogManager/xxxxLogManager.m
--------------------------------------------------------------------`
The oclint.xml file is not created (I have tested with multiple paths and always the same result).

What can I be doing wrong?

Thanks a lot for your help!

**Comment by ryuichis** [comment]
I have no clue at this point with all the information I have. The code compilation part is provided by LLVM/Clang and its compilation database handling. It thinks two jobs are feed to compilation process, and shock on it.

To investigate this further, I will try to work on a `oclint-lintless` binary that contains only the LLVM/Clang pieces to filter out OCLint related issues with LLVM/Clang ones. I have a few deadlines before March 6, so will try to get to this after that.

**Comment by smarciel** [comment]
Hi @ryuichis,
Thank you for your support. Please, let me know if you find out what might be happening.

**Comment by smarciel** [comment]
Hello @ryuichis,
Any updates on this? 
Thank you.

**Comment by smarciel** [comment]
Hello @ryuichis,
With the 21.03 version it works perfect.
Thank you for the help.
