### ISSUE TITLE
PMD Reporter Emits Compiler Errors, Warnings, and Clang Static Analyzer Results

### ISSUE THREAD

**Issue by lqi** [oclint/oclint#60]
`Results` now collects compiler errors, warnings and clang static analyzer results while the driver compilers the source code, and PMD reporter can emit these compiler diagnostic information in the report.

**Comment by x-yang11** [comment]
Hi I'm sorry to leave a message in such an early issue. Now I'm using oclint to generate a pmd file to view the result of code inspection in Jenkins. When I us -report-type html, there is about 2000 compiler warnings in the report. But the PMD report only shows priority-1,2,3 issues. How can I show compiler errors and warnings in the PMD files?

**Comment by UnrealQuester** [comment]
This should have been added by #367. Are you using the oclint from master?

**Comment by x-yang11** [comment]
I'm using 0.10.3-darwin version， I think it's built from master branch. is right?

**Comment by ryuichis** [comment]
It doesn't. By the time you wrote the first reply, the master was 0.10.4, and now it is 0.11.1. The release build can be checked out with its corresponding tag.
