### ISSUE TITLE
TeamCity Reporter

### ISSUE THREAD

**Issue by lqi** [oclint/oclint#61]
We have a group users who use TeamCity as continuous integration system. It will be good to improve the usability and experiences by having a reporter that is fully integrated with TeamCity.

**Comment by jacebrowning** [comment]
For reference, this is the report format required by TeamCity: https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity

**Comment by tomek27** [comment]
I would like to refresh this issue, any progress on that?
Also there was TeamCity 9 release and new confluence page is available under https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity

**Comment by ryuichis** [comment]
Guess the needs for this reporter is fading, so I am closing this one, and let others submit feature requests.
