### ISSUE TITLE
faild with Xcode 13

### ISSUE THREAD

**Issue by ShenYj** [oclint/oclint#618]
### Issue Summary
A brief but thorough description of the issue.

### Environment
- Operation system name and version: Big Sur 11.6
- OCLint version: 21.05
- How OCLint is installed: downloaded from github

### Reproduction Steps
oclint faild with Xcode 13

error like this:
```
5 errors generated.
1 error generated.
1 error generated.
1 error generated.
10 errors generated.
1 error generated.
1 error generated.
1 error generated.
2 errors generated.
3 errors generated.
1 error generated.
```

long long ago, I upgrade Xcode to 11.0 had got this problem, I fixed it with build a local vertion(0.15) , it takes me a few hours. 

I meet this problem again, help, SOS  :(

**Comment by fanyufan** [comment]
i got the same errror in xcode 13.

**Comment by ShenYj** [comment]
> I got the same error

the newest version had fixed it

**Comment by SunshineTeemo** [comment]
> > I got the same error
> 
> the newest version had fixed it

@ShenYj  Hello, can you tell me how do you fix this problem? Which version do you install?

**Comment by SunshineTeemo** [comment]
> Dup #616.

Sorry, I get some problem in Xcode13.0, I use OCLint 20.11, install from homebrew. How can I fix this problem? Am I must upgrade MacOS and Xcode?

**Comment by ShenYj** [comment]
> > > I got the same error
> > 
> > 
> > the newest version had fixed it
> 
> @ShenYj Hello, can you tell me how do you fix this problem? Which version do you install?

https://github.com/oclint/oclint/releases/tag/v21.10
