### ISSUE TITLE
How to use xcpretty to filter all .s and .S files with assembly code

### ISSUE THREAD

**Issue by PrideIce** [oclint/oclint#624]
### Issue Summary
Compiling failed when compiling react RCTProfileTrampoline-x86_6.
I try to use 'oclint-json-compilation-database -e Pods -e React', but it doesn't work.
Ryuichis suggested using xcpretty to filter all .s and .S files, if someone can tell me the exact way to use xcpretty to filter all .s and .S files? Thanks a lot.

### Environment
- Operation system name and version:macOS Mojave 10.14.4
- OCLint version:0.14
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
- prebuilt binary downloaded from github.

### Reproduction Steps
Detailed steps to reproduce the issue.
Detailed steps to reproduce the issue.
Our project integrated React, When analysising, 'Compiling xxxxxxx failed' appeared, but I got the html report which compiling react failed.

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by PrideIce** [comment]
Finally I solved it by add "GCC_PRECOMPILE_PREFIX_HEADER=YES".

**Comment by fndppx** [comment]
> Finally I solved it by add "GCC_PRECOMPILE_PREFIX_HEADER=YES".

where this setting could set ？
