### ISSUE TITLE
Can not install or upgrade to 21.10 using Brew

### ISSUE THREAD

**Issue by minhadd** [oclint/oclint#629]
Hi Team 
Please help:

### Issue Summary
I have tried to upgrade from version 20.11 to version 21.10 using HomeBrew. But the Brew only installed version 20.11, not 21.10.

I tried to uninstall 20.11 and reinstall but I only got 20.11.

Installing OCLint¶
$ brew tap oclint/formulae
$ brew install oclint
Updating OCLint¶
$ brew update
$ brew upgrade oclint

### Environment
- Operation system name and version: MacOS Monterey 12.0.1
- OCLint version: upgrade 20.11 to 21.10
- How OCLint is installed: homebrew install? 
- brew version: 3.3.11

How to upgrade to 21.10 from 20.11 using Brew?

Thanks,
Minh

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichis** [comment]
Based on https://formulae.brew.sh/cask/oclint, it has the latest 21.10 version. Perhaps run `brew update` and updates homebrew itself?

**Comment by minhadd** [comment]
Hi Ryuichis,
I installed using: $ brew install --cask oclint
But It seem MacOS does not accept to open oclint-21.10. Please see the following image:

<img width="664" alt="ảnh" src="https://user-images.githubusercontent.com/11264804/150904808-fbc98d5d-1213-415c-aaf1-400f33856c03.png">

Thanks,
Minh

**Comment by ryuichis** [comment]
@minhadd https://support.apple.com/en-us/HT202491

**Comment by minhadd** [comment]
Hi Ryuichis,

It worked :)
Thank you very much for your support.

Minh
