### ISSUE TITLE
“oclint-22.02” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by YanxiFeng** [oclint/oclint#633]
### Issue Summary
I downloaded the latest oclint version and I run the oclint command, but my mac show tips that “oclint-22.02” can’t be opened because Apple cannot check it for malicious software.

### Environment
- Operation system name and version: macOS 12.3.1
- OCLint version: 22.02
- How OCLint is installed: prebuilt binary downloaded from github

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
