### ISSUE TITLE
Compile successfully but report has many compiler error but Xcode is Normal compilation success 

### ISSUE THREAD

**Issue by fndppx** [oclint/oclint#635]
### Issue Summary
report has many compiler error but Xcode is Normal compilation success #631

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/7971897/170645157-baef9dfa-77ef-48c8-9d82-95a042e33fb8.png">

### Environment
- Operation system name and version: mac os 12.3
- OCLint version:  OCLint version 22.02.
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
local build

### Reproduction Steps
Detailed steps to reproduce the issue.
oclint-json-compilation-database  result  later

#### Sample code

myworkspace=test.xcworkspace #填写workspace
myscheme=test #填写Target
reportType=html #输出类型
reportFile=oclintReport.html #输出文件名
buildJSON=compile_commands.json
totalAnalyzeOutputPath=output

# 清除缓存
xcodebuild -workspace $myworkspace -scheme $myscheme clean

xcodebuild -workspace $myworkspace -scheme $myscheme \
-configuration Debug -sdk iphoneos \
CLANG_ENABLE_MODULE_DEBUGGING=NO CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO COMPILER_INDEX_STORE_ENABLE=NO \
| xcpretty -r json-compilation-database -o compile_commands.json

oclint-json-compilation-database \
-i test \
-i Pods \
-e MMKVCore \
-e SQLiteRepairKit \
-e WCDBOptimizedSQLCipher \
-e WCDB \
-e TimeCostDetecter \
-e BaiduMobStatCodeless \
-e BDHttpDns \
-e Brotli \
-e Bugly \
-e DACircularProgress \
-e FMDB \
-e JLRoutes \
-e Masonry \
-e TTTAttributedLabel \
-e pop \
-e ReactiveCocoa \
-e XXNibBridge \
-e YYCategories \
-e YYModel \
-e YYText \
-e YYWeakProxy \
-e FSCalendar \
-e JSONModel \
-e SSZipArchive \
-e MBProgressHUD \
-e SocketRocket \
-e TZImagePickerController \
-e DerivedData \
-- \
-report-type $reportType \
>> $reportFile \
-disable-rule LongVariableName \
-disable-rule ShortVariableName \
-disable-rule UnusedMethodParameter \
-disable-rule EmptyFinallyStatement \
-disable-rule EmptyTryStatement \
-disable-rule AssignIvarOutsideAccessors \
-disable-rule InvertedLogic \
-disable-rule ParameterReassignment \
-disable-rule PreferEarlyExit \
-disable-rule TooFewBranchesInSwitchStatement \
-disable-rule UnnecessaryDefaultStatement \
-disable-rule ConstantConditionalOperator \
-extra-arg=-Wno-everything \
-rc NESTED_BLOCK_DEPTH=7 \
-rc CYCLOMATIC_COMPLEXITY=60 \
-rc NPATH_COMPLEXITY=400 \
-rc NCSS_METHOD=100 \
-rc LONG_CLASS=1000 \
-rc LONG_LINE=500 \
-rc LONG_METHOD=150 \
-rc TOO_MANY_FIELDS=20 \
-rc TOO_MANY_METHODS=50 \
-rc TOO_MANY_PARAMETERS=10 \
-rc MINIMUM_CASES_IN_SWITCH=10 \
-rc CYCLOMATIC_COMPLEXITY=15 \
-max-priority-1=20000 \
-max-priority-2=30000 \
-max-priority-3=50000 \

Command to run OCLint with the code above.

### Expected Behavior
Do not make compilation errors

### Actual Behavior
has many compilation errors

### Even Better

There are individual library cases involving company code that cannot provide demo

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ZachL1** [comment]
@fndppx Did you solve this problem? How to solve it?

I had a similar problem and it seemed to be related to the `.pch` file.

**Comment by fndppx** [comment]
> @fndppx Did you solve this problem? How to solve it?
> 
> I had a similar problem and it seemed to be related to the `.pch` file.

not solve,no thought to solve

**Comment by fndppx** [comment]
> 

i want you enable to solve ，haha

**Comment by fndppx** [comment]
> @fndppx Did you solve this problem? How to solve it?
> 
> I had a similar problem and it seemed to be related to the `.pch` file.

if you have a thought，i want you could talk to me，haha

**Comment by fndppx** [comment]
> @fndppx Did you solve this problem? How to solve it?
> 
> I had a similar problem and it seemed to be related to the `.pch` file.

i try to infer and oclint，but they are not easy to use，have you other tools recommend me？

**Comment by ZachL1** [comment]
I solved most of the problems. It was actually a problem with `compile_commands.json`, where the compile parameters for some files were missing the `.pch` file that should have been `-include`. I haven't found what the problem is that is causing this at the moment, but it may have something to do with the compile parameters.

My solution now is to locate the `.pch` that is causing the problem (usually most problems are caused by a `.pch` file) and then process `compile_commands.json` through a script to fill in the correct arguments.

**Comment by fndppx** [comment]
> I solved most of the problems. It was actually a problem with `compile_commands.json`, where the compile parameters for some files were missing the `.pch` file that should have been `-include`. I haven't found what the problem is that is causing this at the moment, but it may have something to do with the compile parameters.
> 
> My solution now is to locate the `.pch` that is causing the problem (usually most problems are caused by a `.pch` file) and then process `compile_commands.json` through a script to fill in the correct arguments.

thank you，could you shell give me one ？haha。

**Comment by ZachL1** [comment]
I'm afraid I can't. It's a matter of company secrecy.

On the other hand, my script will not work for you. Because it is only for my own problems and is not a generic approach. You have to find your own problems and target them.

**Comment by fndppx** [comment]
ok，thanks



---Original---
From: "Zach ***@***.***&gt;
Date: Fri, Aug 5, 2022 19:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [oclint/oclint] Compile successfully but report has many compiler error but Xcode is Normal compilation success  (Issue #635)




 
I'm afraid I can't. It's a matter of company secrecy.
 
On the other hand, my script will not work for you. Because it is only for my own problems and is not a generic approach. You have to find your own problems and target them.

**Comment by fndppx** [comment]
> I'm afraid I can't. It's a matter of company secrecy.
> 
> On the other hand, my script will not work for you. Because it is only for my own problems and is not a generic approach. You have to find your own problems and target them.

can you  show me key  script with ld  include code ？i do not find way to solve this issue。

**Comment by fndppx** [comment]
> I'm afraid I can't. It's a matter of company secrecy.
> 
> On the other hand, my script will not work for you. Because it is only for my own problems and is not a generic approach. You have to find your own problems and target them.

i find answer，because use mmkv library

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
