### ISSUE TITLE
project use MMKV lib could analyse error

### ISSUE THREAD

**Issue by fndppx** [oclint/oclint#638]
### Issue Summary
project use MMKV lib could analyse error，because MMKV have some class use assembly，if i remove assembly code of mmkv, that is success。 
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/7971897/185376864-198ec8b3-5637-4461-b90f-8ab42594ff69.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/7971897/185377286-b08915bd-8db6-4339-9143-c5aeaf2e5144.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/7971897/185379473-042718aa-ff27-41dd-ae31-9ee1718b4ce2.png">

### Environment
- Operation system name and version:mac os 12.5
- OCLint version:22.02
- How OCLint is installed: local build

### Reproduction Steps
Detailed steps to reproduce the issue.
project use MMKV lib could analyse error，because MMKV have 

[Uploading Test.zip…]()

this demo,enter root path , ./code-checker.h could recurrent this issue。

<img width="211" alt="image" src="https://user-images.githubusercontent.com/7971897/185380192-bd6a0b9c-f20e-43f2-abbc-accb02e1b8a3.png">

### Expected Behavior
this demo,enter root path , ./code-checker.h could recurrent this issue。

**Comment by fndppx** [comment]
[Test.zip](https://github.com/oclint/oclint/files/9373298/Test.zip)

**Comment by Lianghuajian** [comment]
MMKV has assembling file,  you need to remove those file that ends with .S or .s before xcodebuild and oclint analyse.

**Comment by fndppx** [comment]
> MMKV has assembling file, you need to remove those file that ends with .S or .s before xcodebuild and oclint analyse.

thank you issue has solved

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
