### ISSUE TITLE
How do I use the same compiler as Xcode？

### ISSUE THREAD

**Issue by fndppx** [oclint/oclint#639]
### Issue Summary
has many complie error in report result，i speculate because compiler different with xcode. 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/7971897/186835260-d5db57b3-5676-4951-9fe4-913fe45a7e31.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/7971897/186835332-c1f4425c-5f77-4f97-ba3f-f6eafef03299.png">

Because I analyzed the POD folder, I didn't find the prefix in the POD, which led to the result

### Environment
- Operation system name and version: mac 12.5
- OCLint version:22.02
- How OCLint is installed: local build
- 
### Reproduction Steps
has many complie error in report result，i speculate because compiler different with xcode。

#### Sample code
xcodebuild -workspace $myworkspace -scheme $myscheme clean

xcodebuild -workspace $myworkspace -scheme $myscheme -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' -configuration Debug \
CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=NO \
CLANG_ENABLE_MODULE_DEBUGGING=NO CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO COMPILER_INDEX_STORE_ENABLE=NO \
| tee xcodebuild.log | xcpretty --report json-compilation-database --output compile_commands.json

oclint-json-compilation-database \
$assigin_modules_analyze \
-e MMKV \
-e MMKVCore \
-e DerivedData \
-- \
-report-type $reportType \
>> $reportFile \
-disable-rule LongVariableName \
-disable-rule ShortVariableName \
-disable-rule UnusedMethodParameter \
-disable-rule EmptyFinallyStatement \
-disable-rule EmptyTryStatement \
-disable-rule AssignIvarOutsideAccessors \
-disable-rule InvertedLogic \
-disable-rule ParameterReassignment \
-disable-rule PreferEarlyExit \
-disable-rule TooFewBranchesInSwitchStatement \
-disable-rule UnnecessaryDefaultStatement \
-disable-rule ConstantConditionalOperator \
-extra-arg=-Wno-everything \
-rc NESTED_BLOCK_DEPTH=7 \
-rc CYCLOMATIC_COMPLEXITY=60 \
-rc NPATH_COMPLEXITY=400 \
-rc NCSS_METHOD=100 \
-rc LONG_CLASS=1000 \
-rc LONG_LINE=500 \
-rc LONG_METHOD=150 \
-rc TOO_MANY_FIELDS=20 \
-rc TOO_MANY_METHODS=50 \
-rc TOO_MANY_PARAMETERS=10 \
-rc MINIMUM_CASES_IN_SWITCH=10 \
-rc CYCLOMATIC_COMPLEXITY=15 \
-max-priority-1=20000 \
-max-priority-2=30000 \
-max-priority-3=50000 \
-enable-global-analysis\

Command to run OCLint with the code above.

**Comment by fndppx** [comment]
can I set custom  llvm and clang version when install oclint local build？

**Comment by KinoAndWorld** [comment]
> can I set custom llvm and clang version when install oclint local build？

i have same question, do you had been solved？（我也有相同疑问，你现在解决了吗）

**Comment by czzj0212** [comment]
> 

oclint-scripts目录下有个./makeWithSystemLLVM

**Comment by fndppx** [comment]
好的谢谢



---Original---
From: "Chen ***@***.***&gt;
Date: Wed, Oct 26, 2022 17:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [oclint/oclint] How do I use the same compiler as Xcode？ (Issue #639)




   
oclint-scripts目录下有个./makeWithSystemLLVM

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
