### ISSUE TITLE
what version are   clang and llvm  oclint version 22.02?

### ISSUE THREAD

**Issue by fndppx** [oclint/oclint#640]
### Issue Summary
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/7971897/187582980-5f8feb5d-cf42-4bd1-982e-85cc5e01eaaa.png">
I had some problems with Oclint using Xcode 13.4，because i want custom to build llvm and clang。
Can I download LLVM and CLang and compile Oclint locally?

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
