### ISSUE TITLE
xcode14 not work

### ISSUE THREAD

**Issue by CoderZbf** [oclint/oclint#643]
total files is 0

- why?
<img width="1792" alt="截屏2022-11-10 15 33 45的副本" src="https://user-images.githubusercontent.com/23694821/201028716-0a4409e5-8498-45a1-905c-647be443b8ef.png">

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Comment by iiiSongs** [comment]
> total files is 0
> 
> * why?
> 
> <img alt="截屏2022-11-10 15 33 45的副本" width="1792" src="https://user-images.githubusercontent.com/23694821/201028716-0a4409e5-8498-45a1-905c-647be443b8ef.png">

解决了吗朋友，我在xcode14.1上 oclint编译compile_commands.json生成的xml中 全是  rule="compiler error"
