### ISSUE TITLE
oclint doesn't work: a lot of compiler errors in oclint_result.html.  Xcode 14.1  oclint 22.02

### ISSUE THREAD

**Issue by imbawales** [oclint/oclint#644]
### Issue Summary
sos! my oclint doesn't work: a lot of compiler errors showed in oclint_result.html

### Environment
- Operation system name and version: 
    macOS Monterey 12.6,  Xcode 14.1

- OCLint version:  
    22.02

- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
   download package from below :
  [oclint-22.02-llvm-13.0.1-arm64-darwin-macos-12.2-xcode-13.2.tar.gz](https://github.com/oclint/oclint/releases/download/v22.02/oclint-22.02-llvm-13.0.1-arm64-darwin-macos-12.2-xcode-13.2.tar.gz)

### Reproduction Steps
1.install oclint and was successed
![image](https://user-images.githubusercontent.com/24821783/201593201-3384b665-465d-492f-b724-27ef0dd36c1c.png)

2.create my sh file and run it as the introduction . my sh code like that in the #sample code# below.

3.open the result file : oclint_result.html. It shows a lot of compiler errors:
![image](https://user-images.githubusercontent.com/24821783/201593770-e05f3f3e-b801-47c6-aa7d-3986d811b132.png)
![image](https://user-images.githubusercontent.com/24821783/201593992-38ad6366-f531-458c-a271-e04b77d86f7c.png)
6 errors generated.
1 error generated.
1 error generated.
1 error generated.
4 errors generated.
5 errors generated.
1 error generated.

#### Sample code

```

PROJECT=unzipDemo.xcodeproj
SCHEME=unzipDemo
xcodebuild -project $PROJECT -scheme $SCHEME clean&&
xcodebuild -project $PROJECT -scheme $SCHEME \
-configuration Debug \
-sdk iphonesimulator16.1 \
| xcpretty -r json-compilation-database -o compile_commands.json&&
oclint-json-compilation-database -e Pods -e Vender  -- \
-report-type html >> oclint_result.html \
-disable-rule ProblematicBaseClassDestructor \
-disable-rule DestructorOfVirtualClass \
-disable-rule AssignIvarOutsideAccessors \
-disable-rule ParameterReassignment \
-disable-rule ShortVariableName \
-disable-rule RedundantLocalVariable \
-disable-rule TooManyFields \
-disable-rule TooManyMethods \
-disable-rule UnusedLocalVariable \
-disable-rule UnusedMethodParameter \
-disable-rule HighCyclomaticComplexity \
-disable-rule HighNcssMethod \
-rc LongClass=1000 \
-rc LONG_LINE=200 \
-rc LongMethod=100 \
-rc TooManyParameters=2 \
-rc DeepNestedBlock=5 \
-max-priority-1=100000 \
-max-priority-2=100000 \
-max-priority-3=100000 \
rm compile_commands.json

```

Command to run OCLint with the code above.

### Expected Behavior
show normal code review result.

### Actual Behavior
show a lot of compiler error like above.

### Even Better
Is your project open sourced? If yes, can you point us to your repository? no ,just a simple demo project.
If not, is it possible to make a small project to illustrate the problem? yes ,my demo is a small simple demo .
If not, can you create a gist with your sample code for us?

**Comment by Lianghuajian** [comment]
Same，did you find out how to fix it ？

**Comment by RommiPlus** [comment]
same problem，use xcode 14.

**Comment by mqlsq** [comment]
Same problem

**Comment by Lianghuajian** [comment]
I just fork this git and fix it, soon I might create a pull request.

**Comment by mqlsq** [comment]
> 

How to fix it!

**Comment by mqlsq** [comment]
> I just fork this git and fix it, soon I might create a pull request.

How to fix it!

**Comment by DawnzrXie** [comment]
When will it be fixed?

**Comment by Lianghuajian** [comment]
https://github.com/Lianghuajian/oclint/tree/support_xcode14 @mqlsq @DawnzrXie Try this one, I pull a branch to fix it.

**Comment by JulesMoorhouse** [comment]
@Lianghuajian so how do you use it, once you'll pulled the branch?
I presume you mean you have to re-build it, but how ?

Thanks in advance.

**Comment by JulesMoorhouse** [comment]
@Lianghuajian 

I can't seem to get that to work...

```
source "https://rubygems.org"

ruby '3.0.3'

gem 'fastlane'
gem 'xcpretty'
gem 'cocoapods'
#gem "oclint"
gem 'oclint', github: 'Lianghuajian/oclint', branch: 'support_xcode14'
```

Could not find gem 'oclint' in https://github.com/Lianghuajian/oclint.git (at support_xcode14@89a146d)

Any suggestions?

Thanks in advance

**Comment by JulesMoorhouse** [comment]
Also

```
gem 'oclint', git: 'https://github.com/Lianghuajian/oclint.git', branch: 'support_xcode14'
```

Produces the same error

**Comment by Lianghuajian** [comment]
> Also
> 
> ```
> gem 'oclint', git: 'https://github.com/Lianghuajian/oclint.git', branch: 'support_xcode14'
> ```
> 
> Produces the same error
Try build oclint from sourceCode, I don't know how to publish to gem.
git clone -b support_xcode14 --depth=1 https://github.com/Lianghuajian/oclint.git oclint && cd oclint/oclint-scripts && ./make

**Comment by JulesMoorhouse** [comment]
Thanks...

I've got further...
But can't get passed this error....


ninja: error: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libcurses.tbd', needed by 'bin/oclint-23.0', missing and no known rule to make it


Actually my Xcode is Xcode142.app

**Comment by JulesMoorhouse** [comment]
Oh.. also you could submit a PR...

**Comment by michaelrourke** [comment]
I followed @Lianghuajian's instructions for building and produced an oclint that works for me. 
Many thanks!

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Comment by liudukun** [comment]
brew install ninja
