### ISSUE TITLE
Please upgrade oclint to llvm14.0

### ISSUE THREAD

**Issue by iiiSongs** [oclint/oclint#648]
### Issue Summary
![image](https://user-images.githubusercontent.com/15967328/217238684-3e253abf-106d-4148-9659-9a3b8a656e74.png)

Using oclint-22.02 on xcode14, the content in the generated xml file is all "rule=compiler error". I found that oclint-22.02 is based on llvm13.0.1, and the version of llvm-gcc of xcode14 is 14.0. I guess it is because the versions are inconsistent that the error will be reported.
Please upgrade oclint to llvm14.0

### Environment
- Operation system name and version:MacOS Ventura 13.0
- OCLint version:22.02
- How OCLint is installed: local build

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by iiiSongs** [comment]
> It seems like you have not followed our issue template.
> 
> To make it easier for us help you resolve this issue, please update the issue by following our template.

### Issue Summary
![image](https://user-images.githubusercontent.com/15967328/217703139-3ec81331-90fb-4bc7-b4be-949a0b291dc1.png)

Using oclint-22.02 on xcode14, the content in the generated xml file is all "rule=compiler error". I found that oclint-22.02 is based on llvm13.0.1, and the version of llvm-gcc of xcode14 is 14.0. I guess it is because the versions are inconsistent that the error will be reported.
Please upgrade oclint to llvm14.0

### Environment
- Operation system name and version:MacOS Ventura 13.0
- Xcode version: 14.1
- OCLint version:22.02
- How OCLint is installed: local build

### Reproduction Steps
1. Use the "xcodebuild -workspace" command to compile my project and generate a compile_commands.json file.
2.Executing the script makes oclint scan the compile_commands.json file

#### Sample code

lint_command = '''oclint-json-compilation-database -e Pods -- \
        --verbose \
        -extra-arg=-Wno-everything \
        -rc CYCLOMATIC_COMPLEXITY=%d \
        -rc LONG_CLASS=%d \
        -rc LONG_LINE=%d \
        -rc LONG_METHOD=%d \
        -rc MINIMUM_CASES_IN_SWITCH=%d \
        -rc NPATH_COMPLEXITY=%d \
        -rc NCSS_METHOD=%d \
        -rc NESTED_BLOCK_DEPTH=%d \
        -rc CYCLOMATIC_COMPLEXITY=20 \
        --report-type pmd \
        -max-priority-1=9999 -max-priority-2=9999 -max-priority-3=9999 \
        -o %s''' % (CYCLOMATIC_COMPLEXITY, LONG_CLASS, LONG_LINE, LONG_METHOD, MINIMUM_CASES_IN_SWITCH, NPATH_COMPLEXITY, NCSS_METHOD, NESTED_BLOCK_DEPTH, out_file)
        os.system(lint_command)

Command to run OCLint with the code above.

### Expected Behavior
During the execution of oclint-json-compilation-database, no error occurs, and the xml file is generated correctly

### Actual Behavior
During the execution of oclint-json-compilation-database, the error shown in the above figure will be generated, and all the generated xml files are "rule=compiler error"

**Comment by pusswzy** [comment]
Same problem

**Comment by wangjordy** [comment]
same problem, I try use different llvm version, and repalce oclintscripts/version.py,   llvm version,    after  compile new release oclint version, also show this problem.

Environment

mac os  12.5.1 ,    m1 cpu
xcode 14
oclint-sourcecode

**Comment by AveryKL-1213** [comment]
same problem, I changed the url of llvm in oclintscripts/path.py and it works.
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/55079072/221805060-bbc87ddd-5f0c-481b-a0e0-d9166f9e6bb5.png">
https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-apple-darwin.tar.xz

but it seems that there are no llvm 14 available for apple silicon, you may need to build llvm 14 from source code by yourself.

**Comment by ShiXianjun93** [comment]
Same problem

**Comment by A-Dirt** [comment]
> same problem, I changed the url of llvm in oclintscripts/path.py and it works. <img alt="image" width="1090" src="https://user-images.githubusercontent.com/55079072/221805060-bbc87ddd-5f0c-481b-a0e0-d9166f9e6bb5.png"> https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-apple-darwin.tar.xz
> 
> but it seems that there are no llvm 14 available for apple silicon, you may need to build llvm 14 from source code by yourself.

哥们，用你这方法后，那些奇怪的错误没了；但是oclint原本的功能也没了，圈复杂度检查、参数数量检查这些功能都失效了

**Comment by AveryKL-1213** [comment]
> 

编完之后自带的规则的动态库应该都在 oclint/build/oclint-release/lib/oclint/rules/ 路径里，自己写完规则编译完之后也是要复制到这个路径下的。看看你这个路径里有文件吗？

**Comment by AveryKL-1213** [comment]
> > same problem, I changed the url of llvm in oclintscripts/path.py and it works. <img alt="image" width="1090" src="https://user-images.githubusercontent.com/55079072/221805060-bbc87ddd-5f0c-481b-a0e0-d9166f9e6bb5.png"> https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-apple-darwin.tar.xz
> > but it seems that there are no llvm 14 available for apple silicon, you may need to build llvm 14 from source code by yourself.
> 
> 哥们，用你这方法后，那些奇怪的错误没了；但是oclint原本的功能也没了，圈复杂度检查、参数数量检查这些功能都失效了

编完之后自带的规则的动态库应该都在 oclint/build/oclint-release/lib/oclint/rules/ 路径里，自己写完规则编译完之后也是要复制到这个路径下的。看看你这个路径里有文件吗？

**Comment by liudong9109** [comment]
我也有相同的问题，希望作者能出新版本

**Comment by kevinlaunew** [comment]
终于找到了解决方案，请参考这个：
https://github.com/Lianghuajian/oclint/tree/support_xcode14

**Comment by liudukun** [comment]
xcode14.2 才可以

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by lszyyy** [comment]
when will we have llvm 14/15 working with oclint ?

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Comment by yonghuifan21** [comment]
xcode 14.3, oclint  23.0 appears 
ERROR - Command 'oclint-json-compilation-database -v --include ../test/. ./test/. -- -rc LONG_LINE=1000 -max-priority-1 10000 -max-priority-2 10000 -max-priority-3 10000 -report-type pmd -o sonar-reports/.-oclint.xml' failed with error code: 3

**Comment by Lianghuajian** [comment]
Try the commands below. This setup supports Xcode 15 on ARM64 (not x86_64) Mac, including the fix for '-ivfsstatcache'
```
git clone -b support_xcode15 https://github.com/Lianghuajian/oclint.git oclint 

cd oclint/oclint-scripts && ./make && cd ..
``` @lszyyy @yonghuifan21
