### ISSUE TITLE
Feature request: adjust threshold for one function

### ISSUE THREAD

**Issue by jackdigitalinsight** [oclint/oclint#649]
### Issue Summary
It would be useful to be able to adjust rule thresholds on a per-function level.

### Environment
- Linux 5.4.0 Ubuntu
- OCLint version: 21.05

### Details
I'd like to run OCLint with e.g. "CYCLOMATIC_COMPLEXITY=10", but a few functions can't be effectively refactored to avoid needing a somewhat higher threshold. I'd rather not increase the threshold project-wide. I can add an attribute oclint:suppress to disable that check for a specific function, but it would be even better if I could bump the threshold for that function, indicating that it was reviewed and is acceptable as-is. Then if the function gets modified to be even worse, it will be caught.

e.g. I'd like to setting the attribute to "oclint:threshold[high cyclomatic complexity]=15"

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
