### ISSUE TITLE
With the same compilation options, clang compiles successfully, but oclint encounters problems during compilation

### ISSUE THREAD

**Issue by bettertang** [oclint/oclint#653]
With the same compilation options, clang compiles successfully, but oclint encounters problems during compilation

### Environment
- Operation system name and version:
- 14.1 (23B74)
- OCLint version:23.0
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
-  local build

### Reproduction Steps

oclint /Users/yst/Documents/IOS_Learn_project/IOS_learn/SampleApp/ListLoad.m -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c  -xxxxxx
e -target arm64-apple-ios12.1-simulator -fmessage-length\=0 -xxxxx
 -c /Users/yst/Documents/IOS_Learn_project/IOS_learn/SampleApp/ListLoad.m 
1 error generated.

Compiler Errors:
(please be aware that these errors will prevent OCLint from analyzing this source code)

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:120:47: type argument 'nw_proxy_config_t' (aka 'struct nw_proxy_config *') is neither an Objective-C object nor a block type
/Users/yst/Documents/IOS_Learn_project/IOS_learn/SampleApp/ListLoad.m:12:9: could not build module 'WebKit'

OCLint Report

Summary: TotalFiles=0 FilesWithViolations=0 P1=0 P2=0 P3=0

#### Sample code

```
Objective-C
```

### Expected Behavior
compile successfully
### Actual Behavior
Compiler Error
### Even Better
This file appears to be a project file that has added the header file #import <WebKit/WebKit.h>

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by bettertang** [comment]
> It seems like you have not followed our issue template.
> 
> To make it easier for us help you resolve this issue, please update the issue by following our template.

hello，update the issue now

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
