### ISSUE TITLE
Use llvm-cov for code coverage

### ISSUE THREAD

**Issue by lqi** [oclint/oclint#82]

**Comment by UnrealQuester** [comment]
@ryuichis is there anything else that needs to be done for this issue or can we close this?

**Comment by ryuichis** [comment]
@UnrealQuester was thinking to show the coverage report locally in addition to travis ci.

**Comment by UnrealQuester** [comment]
Tinkering with lcov and genhtml as per [this blog post](http://logan.tw/posts/2015/04/28/check-code-coverage-with-clang-and-lcov/) fails on llvm-cov. It looks like lcov tries to pass a '-v' parameter to its gcov invocation. `llvm-cov gcov` does not have such a parameter and aborts.

Running the test script at least generates the .gcda files needed for `llvm-cov gcov`. I still need to find an easy way to get a nice human readable output out of that.

**Comment by ryuichis** [comment]
@UnrealQuester lcov has been used at very early stage of oclint development. https://github.com/oclint/oclint-04/blob/master/script/moCIBuild.sh And at a certain point of time, it stopped working. Will `llvm-cov show` or `llvm-cov report` returns us any useful information? Another tool that might worths to look into is `llvm-profdata`. 

As first step, a readable text output should be sufficient enough. HTML can come later, if technical doable. Thanks again.
