### ISSUE TITLE
Exclude multiple classes from oclint-json-compilation-database?

### ISSUE THREAD

**Issue by bruceflowers** [oclint/oclint#86]
This is a question about command line usage: I would like to exclude a number of filename patterns from the final report, and I'm not having much luck figuring out how to send in a list of patterns to the -e (-exclude) argument of oclint-json-compilation-database.

Here is a scratch example what I'm trying to do (I've also tried many other combinations of syntax):
-exclude=JSONKit.m,_Test_,Debug.m

Can you provide a simple usage example that would let me exclude say 2-3 patterns?

**Comment by ljfantin** [comment]
is possible to use reg expression ?
