### ISSUE TITLE
Build OCLint against out-of-tree llvm/clang

### ISSUE THREAD

**Issue by sylvestre** [oclint/oclint#93]
It would be nice if we could build oclint without having to build llvm/clang.

We should be able to build oclint just with the -dev packages of our favorites distributions.

**Comment by ryuichis** [comment]
Several recent changes had addressed this issue. To mention a few: #242, #272, @57729a670f67abbdc5b2c3332f18313d1569a5a3, etc. Future improvements will be worked on separately with new open issues.
